// Code generated by ent, DO NOT EDIT.

package sessionfilter

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the sessionfilter type in the database.
	Label = "session_filter"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldSessionID holds the string denoting the session_id field in the database.
	FieldSessionID = "session_id"
	// FieldFilterID holds the string denoting the filter_id field in the database.
	FieldFilterID = "filter_id"
	// FieldMatchesCount holds the string denoting the matches_count field in the database.
	FieldMatchesCount = "matches_count"
	// EdgeSession holds the string denoting the session edge name in mutations.
	EdgeSession = "session"
	// EdgeFilter holds the string denoting the filter edge name in mutations.
	EdgeFilter = "filter"
	// EdgeMatchedPackets holds the string denoting the matched_packets edge name in mutations.
	EdgeMatchedPackets = "matched_packets"
	// Table holds the table name of the sessionfilter in the database.
	Table = "session_filters"
	// SessionTable is the table that holds the session relation/edge.
	SessionTable = "session_filters"
	// SessionInverseTable is the table name for the Session entity.
	// It exists in this package in order to avoid circular dependency with the "session" package.
	SessionInverseTable = "sessions"
	// SessionColumn is the table column denoting the session relation/edge.
	SessionColumn = "session_id"
	// FilterTable is the table that holds the filter relation/edge.
	FilterTable = "session_filters"
	// FilterInverseTable is the table name for the Filter entity.
	// It exists in this package in order to avoid circular dependency with the "filter" package.
	FilterInverseTable = "filters"
	// FilterColumn is the table column denoting the filter relation/edge.
	FilterColumn = "filter_id"
	// MatchedPacketsTable is the table that holds the matched_packets relation/edge.
	MatchedPacketsTable = "matched_packets"
	// MatchedPacketsInverseTable is the table name for the MatchedPacket entity.
	// It exists in this package in order to avoid circular dependency with the "matchedpacket" package.
	MatchedPacketsInverseTable = "matched_packets"
	// MatchedPacketsColumn is the table column denoting the matched_packets relation/edge.
	MatchedPacketsColumn = "session_filter_id"
)

// Columns holds all SQL columns for sessionfilter fields.
var Columns = []string{
	FieldID,
	FieldSessionID,
	FieldFilterID,
	FieldMatchesCount,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultMatchesCount holds the default value on creation for the "matches_count" field.
	DefaultMatchesCount int
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// OrderOption defines the ordering options for the SessionFilter queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// BySessionID orders the results by the session_id field.
func BySessionID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSessionID, opts...).ToFunc()
}

// ByFilterID orders the results by the filter_id field.
func ByFilterID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFilterID, opts...).ToFunc()
}

// ByMatchesCount orders the results by the matches_count field.
func ByMatchesCount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMatchesCount, opts...).ToFunc()
}

// BySessionField orders the results by session field.
func BySessionField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newSessionStep(), sql.OrderByField(field, opts...))
	}
}

// ByFilterField orders the results by filter field.
func ByFilterField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newFilterStep(), sql.OrderByField(field, opts...))
	}
}

// ByMatchedPacketsCount orders the results by matched_packets count.
func ByMatchedPacketsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newMatchedPacketsStep(), opts...)
	}
}

// ByMatchedPackets orders the results by matched_packets terms.
func ByMatchedPackets(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newMatchedPacketsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newSessionStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(SessionInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, SessionTable, SessionColumn),
	)
}
func newFilterStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(FilterInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, FilterTable, FilterColumn),
	)
}
func newMatchedPacketsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(MatchedPacketsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, MatchedPacketsTable, MatchedPacketsColumn),
	)
}
