version: '3.9'
volumes:
  postgres_data:
  redis_data:

services:
  frontend:
    container_name: frontend
    depends_on:
      - core
    build:
      context: ./frontend
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - 80:80
    networks:
      altron_network:
        aliases:
          - altron.frontend.loc

  db:
    container_name: db
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: altron_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass
      PGPORT: 5432
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres -d altron_db']
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      altron_network:
        ipv4_address: 172.28.0.10
        aliases:
          - altron.db.loc

  rabbitmq:
    container_name: rabbitmq
    build:
      context: ./
      dockerfile: ./docker/rabbitmq.dockerfile
    image: rabbitmq:docker
    environment:
      - RABBITMQ_DEFAULT_USER=${AMQP_USER:-user}
      - RABBITMQ_DEFAULT_PASS=${AMQP_PASS:-pass}
    env_file:
      - .env
    networks:
      altron_network:
        ipv4_address: 172.28.0.11
        aliases:
          - altron.rabbitmq.loc

  redis:
    container_name: redis
    image: redis
    command: redis-server --port 6379 --save 20 1 --loglevel warning --requirepass pass
    volumes: 
      - redis_data:/data
    networks:
      altron_network:
        ipv4_address: 172.28.0.12
        aliases:
          - altron.redis.loc

  core:
    container_name: core
    depends_on:
      - db
      - sftp
      - rabbitmq
      - redis
      - plugin
      - session
      - converter
      - connection
    restart: always
    build:
      context: .
      dockerfile: ./docker/core.dockerfile
    env_file:
      - .env
    networks:
      altron_network:
        ipv4_address: 172.28.0.13
        aliases:
          - altron.core.loc

  plugin:
    container_name: plugin
    restart: always
    build: 
      context: .
      dockerfile: ./docker/plugin.dockerfile
    env_file:
      - .env
    networks:
      altron_network:
        ipv4_address: 172.28.0.14
        aliases:
          - altron.plugin.loc

  session:
    container_name: session
    depends_on:
      - rabbitmq
      - redis
      - sftp
    restart: always
    build:
      context: .
      dockerfile: ./docker/session.dockerfile
    privileged: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    env_file:
      - .env
    ports:
      - 64005:64005
    network_mode: host
    extra_hosts:
      - "altron.core.loc:172.28.0.13"
      - "altron.rabbitmq.loc:172.28.0.11"
      - "altron.redis.loc:172.28.0.12"
      - "altron.sftp.loc:172.28.0.15"

  converter:
    container_name: converter
    restart: always
    build:
      context: .
      dockerfile: ./docker/converter.dockerfile
    networks:
      altron_network:
        ipv4_address: 172.28.0.16
        aliases:
          - altron.converter.loc

  sftp:
    container_name: sftp
    image: drakkan/sftpgo:latest
    ports:
      - 8080:8080
      - 21:2022
    networks:
      altron_network:
        ipv4_address: 172.28.0.15
        aliases:
          - altron.sftp.loc

  connection:
    container_name: connection
    depends_on:
      - rabbitmq
      - redis
    restart: always
    build:
      context: .
      dockerfile: ./docker/connection.dockerfile
    env_file:
      - .env
    networks:
      altron_network:
        ipv4_address: 172.28.0.17
        aliases:
          - altron.connection.loc

networks:
  altron_network:
    ipam:
      config:
        - subnet: "172.28.0.0/16"