apiVersion: v1
kind: Secret
type: kubernetes.io/dockerconfigjson
metadata:
  name: altron-secret
data:
  .dockerconfigjson: eyJhdXRocyI6eyJkb2NrZXIuaW8iOnsidXNlcm5hbWUiOiJlbm1leCIsInBhc3N3b3JkIjoiRjN5QUdNZUpYRCJ9fX0=
