apiVersion: v1
kind: Service
metadata:
  name: altron-service
spec:
  selector:
    app: altron
  ports:
    - name: frontend
      protocol: TCP
      port: 31000
      targetPort: 31000
  type: NodePort
