// Code generated by ent, DO NOT EDIT.

package workspace

import (
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the workspace type in the database.
	Label = "workspace"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// EdgeSessions holds the string denoting the sessions edge name in mutations.
	EdgeSessions = "sessions"
	// EdgeService holds the string denoting the service edge name in mutations.
	EdgeService = "service"
	// EdgeAnalyzerPayloads holds the string denoting the analyzer_payloads edge name in mutations.
	EdgeAnalyzerPayloads = "analyzer_payloads"
	// EdgeCartSessions holds the string denoting the cart_sessions edge name in mutations.
	EdgeCartSessions = "cart_sessions"
	// Table holds the table name of the workspace in the database.
	Table = "workspaces"
	// SessionsTable is the table that holds the sessions relation/edge.
	SessionsTable = "sessions"
	// SessionsInverseTable is the table name for the Session entity.
	// It exists in this package in order to avoid circular dependency with the "session" package.
	SessionsInverseTable = "sessions"
	// SessionsColumn is the table column denoting the sessions relation/edge.
	SessionsColumn = "workspace_sessions"
	// ServiceTable is the table that holds the service relation/edge.
	ServiceTable = "workspaces"
	// ServiceInverseTable is the table name for the Service entity.
	// It exists in this package in order to avoid circular dependency with the "service" package.
	ServiceInverseTable = "services"
	// ServiceColumn is the table column denoting the service relation/edge.
	ServiceColumn = "service_workspaces"
	// AnalyzerPayloadsTable is the table that holds the analyzer_payloads relation/edge.
	AnalyzerPayloadsTable = "analyzer_payloads"
	// AnalyzerPayloadsInverseTable is the table name for the AnalyzerPayload entity.
	// It exists in this package in order to avoid circular dependency with the "analyzerpayload" package.
	AnalyzerPayloadsInverseTable = "analyzer_payloads"
	// AnalyzerPayloadsColumn is the table column denoting the analyzer_payloads relation/edge.
	AnalyzerPayloadsColumn = "workspace_id"
	// CartSessionsTable is the table that holds the cart_sessions relation/edge.
	CartSessionsTable = "cart_sessions"
	// CartSessionsInverseTable is the table name for the CartSession entity.
	// It exists in this package in order to avoid circular dependency with the "cartsession" package.
	CartSessionsInverseTable = "cart_sessions"
	// CartSessionsColumn is the table column denoting the cart_sessions relation/edge.
	CartSessionsColumn = "workspace_id"
)

// Columns holds all SQL columns for workspace fields.
var Columns = []string{
	FieldID,
	FieldName,
	FieldStatus,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "workspaces"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"service_workspaces",
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// Status defines the type for the "status" enum field.
type Status string

// Status values.
const (
	StatusLISTENING Status = "LISTENING"
	StatusCOMPLETED Status = "COMPLETED"
	StatusWAITING   Status = "WAITING"
)

func (s Status) String() string {
	return string(s)
}

// StatusValidator is a validator for the "status" field enum values. It is called by the builders before save.
func StatusValidator(s Status) error {
	switch s {
	case StatusLISTENING, StatusCOMPLETED, StatusWAITING:
		return nil
	default:
		return fmt.Errorf("workspace: invalid enum value for status field: %q", s)
	}
}

// OrderOption defines the ordering options for the Workspace queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// BySessionsCount orders the results by sessions count.
func BySessionsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newSessionsStep(), opts...)
	}
}

// BySessions orders the results by sessions terms.
func BySessions(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newSessionsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByServiceField orders the results by service field.
func ByServiceField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newServiceStep(), sql.OrderByField(field, opts...))
	}
}

// ByAnalyzerPayloadsCount orders the results by analyzer_payloads count.
func ByAnalyzerPayloadsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newAnalyzerPayloadsStep(), opts...)
	}
}

// ByAnalyzerPayloads orders the results by analyzer_payloads terms.
func ByAnalyzerPayloads(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newAnalyzerPayloadsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByCartSessionsCount orders the results by cart_sessions count.
func ByCartSessionsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newCartSessionsStep(), opts...)
	}
}

// ByCartSessions orders the results by cart_sessions terms.
func ByCartSessions(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newCartSessionsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newSessionsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(SessionsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, SessionsTable, SessionsColumn),
	)
}
func newServiceStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ServiceInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, ServiceTable, ServiceColumn),
	)
}
func newAnalyzerPayloadsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(AnalyzerPayloadsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, AnalyzerPayloadsTable, AnalyzerPayloadsColumn),
	)
}
func newCartSessionsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(CartSessionsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, CartSessionsTable, CartSessionsColumn),
	)
}
