// Code generated by ent, DO NOT EDIT.

package user

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the user type in the database.
	Label = "user"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldUsername holds the string denoting the username field in the database.
	FieldUsername = "username"
	// FieldPassword holds the string denoting the password field in the database.
	FieldPassword = "password"
	// EdgeServices holds the string denoting the services edge name in mutations.
	EdgeServices = "services"
	// EdgePcapworkspaces holds the string denoting the pcapworkspaces edge name in mutations.
	EdgePcapworkspaces = "pcapworkspaces"
	// EdgeFilters holds the string denoting the filters edge name in mutations.
	EdgeFilters = "filters"
	// Table holds the table name of the user in the database.
	Table = "users"
	// ServicesTable is the table that holds the services relation/edge.
	ServicesTable = "services"
	// ServicesInverseTable is the table name for the Service entity.
	// It exists in this package in order to avoid circular dependency with the "service" package.
	ServicesInverseTable = "services"
	// ServicesColumn is the table column denoting the services relation/edge.
	ServicesColumn = "user_id"
	// PcapworkspacesTable is the table that holds the pcapworkspaces relation/edge.
	PcapworkspacesTable = "pcap_workspaces"
	// PcapworkspacesInverseTable is the table name for the PcapWorkspace entity.
	// It exists in this package in order to avoid circular dependency with the "pcapworkspace" package.
	PcapworkspacesInverseTable = "pcap_workspaces"
	// PcapworkspacesColumn is the table column denoting the pcapworkspaces relation/edge.
	PcapworkspacesColumn = "user_id"
	// FiltersTable is the table that holds the filters relation/edge.
	FiltersTable = "filters"
	// FiltersInverseTable is the table name for the Filter entity.
	// It exists in this package in order to avoid circular dependency with the "filter" package.
	FiltersInverseTable = "filters"
	// FiltersColumn is the table column denoting the filters relation/edge.
	FiltersColumn = "user_id"
)

// Columns holds all SQL columns for user fields.
var Columns = []string{
	FieldID,
	FieldUsername,
	FieldPassword,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// OrderOption defines the ordering options for the User queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByUsername orders the results by the username field.
func ByUsername(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUsername, opts...).ToFunc()
}

// ByPassword orders the results by the password field.
func ByPassword(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPassword, opts...).ToFunc()
}

// ByServicesCount orders the results by services count.
func ByServicesCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newServicesStep(), opts...)
	}
}

// ByServices orders the results by services terms.
func ByServices(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newServicesStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByPcapworkspacesCount orders the results by pcapworkspaces count.
func ByPcapworkspacesCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newPcapworkspacesStep(), opts...)
	}
}

// ByPcapworkspaces orders the results by pcapworkspaces terms.
func ByPcapworkspaces(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newPcapworkspacesStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByFiltersCount orders the results by filters count.
func ByFiltersCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newFiltersStep(), opts...)
	}
}

// ByFilters orders the results by filters terms.
func ByFilters(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newFiltersStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newServicesStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ServicesInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, ServicesTable, ServicesColumn),
	)
}
func newPcapworkspacesStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(PcapworkspacesInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, PcapworkspacesTable, PcapworkspacesColumn),
	)
}
func newFiltersStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(FiltersInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, FiltersTable, FiltersColumn),
	)
}
