// Code generated by ent, DO NOT EDIT.

package service

import (
	"altron/core/repositories/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.Service {
	return predicate.Service(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.Service {
	return predicate.Service(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.Service {
	return predicate.Service(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.Service {
	return predicate.Service(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.Service {
	return predicate.Service(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.Service {
	return predicate.Service(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.Service {
	return predicate.Service(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.Service {
	return predicate.Service(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.Service {
	return predicate.Service(sql.FieldLTE(FieldID, id))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v uuid.UUID) predicate.Service {
	return predicate.Service(sql.FieldEQ(FieldUserID, v))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.Service {
	return predicate.Service(sql.FieldEQ(FieldName, v))
}

// Link applies equality check predicate on the "link" field. It's identical to LinkEQ.
func Link(v string) predicate.Service {
	return predicate.Service(sql.FieldEQ(FieldLink, v))
}

// Port applies equality check predicate on the "port" field. It's identical to PortEQ.
func Port(v uint32) predicate.Service {
	return predicate.Service(sql.FieldEQ(FieldPort, v))
}

// ContainerID applies equality check predicate on the "container_id" field. It's identical to ContainerIDEQ.
func ContainerID(v string) predicate.Service {
	return predicate.Service(sql.FieldEQ(FieldContainerID, v))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v uuid.UUID) predicate.Service {
	return predicate.Service(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v uuid.UUID) predicate.Service {
	return predicate.Service(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...uuid.UUID) predicate.Service {
	return predicate.Service(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...uuid.UUID) predicate.Service {
	return predicate.Service(sql.FieldNotIn(FieldUserID, vs...))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.Service {
	return predicate.Service(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.Service {
	return predicate.Service(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.Service {
	return predicate.Service(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.Service {
	return predicate.Service(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.Service {
	return predicate.Service(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.Service {
	return predicate.Service(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.Service {
	return predicate.Service(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.Service {
	return predicate.Service(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.Service {
	return predicate.Service(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.Service {
	return predicate.Service(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.Service {
	return predicate.Service(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.Service {
	return predicate.Service(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.Service {
	return predicate.Service(sql.FieldContainsFold(FieldName, v))
}

// LinkEQ applies the EQ predicate on the "link" field.
func LinkEQ(v string) predicate.Service {
	return predicate.Service(sql.FieldEQ(FieldLink, v))
}

// LinkNEQ applies the NEQ predicate on the "link" field.
func LinkNEQ(v string) predicate.Service {
	return predicate.Service(sql.FieldNEQ(FieldLink, v))
}

// LinkIn applies the In predicate on the "link" field.
func LinkIn(vs ...string) predicate.Service {
	return predicate.Service(sql.FieldIn(FieldLink, vs...))
}

// LinkNotIn applies the NotIn predicate on the "link" field.
func LinkNotIn(vs ...string) predicate.Service {
	return predicate.Service(sql.FieldNotIn(FieldLink, vs...))
}

// LinkGT applies the GT predicate on the "link" field.
func LinkGT(v string) predicate.Service {
	return predicate.Service(sql.FieldGT(FieldLink, v))
}

// LinkGTE applies the GTE predicate on the "link" field.
func LinkGTE(v string) predicate.Service {
	return predicate.Service(sql.FieldGTE(FieldLink, v))
}

// LinkLT applies the LT predicate on the "link" field.
func LinkLT(v string) predicate.Service {
	return predicate.Service(sql.FieldLT(FieldLink, v))
}

// LinkLTE applies the LTE predicate on the "link" field.
func LinkLTE(v string) predicate.Service {
	return predicate.Service(sql.FieldLTE(FieldLink, v))
}

// LinkContains applies the Contains predicate on the "link" field.
func LinkContains(v string) predicate.Service {
	return predicate.Service(sql.FieldContains(FieldLink, v))
}

// LinkHasPrefix applies the HasPrefix predicate on the "link" field.
func LinkHasPrefix(v string) predicate.Service {
	return predicate.Service(sql.FieldHasPrefix(FieldLink, v))
}

// LinkHasSuffix applies the HasSuffix predicate on the "link" field.
func LinkHasSuffix(v string) predicate.Service {
	return predicate.Service(sql.FieldHasSuffix(FieldLink, v))
}

// LinkEqualFold applies the EqualFold predicate on the "link" field.
func LinkEqualFold(v string) predicate.Service {
	return predicate.Service(sql.FieldEqualFold(FieldLink, v))
}

// LinkContainsFold applies the ContainsFold predicate on the "link" field.
func LinkContainsFold(v string) predicate.Service {
	return predicate.Service(sql.FieldContainsFold(FieldLink, v))
}

// PortEQ applies the EQ predicate on the "port" field.
func PortEQ(v uint32) predicate.Service {
	return predicate.Service(sql.FieldEQ(FieldPort, v))
}

// PortNEQ applies the NEQ predicate on the "port" field.
func PortNEQ(v uint32) predicate.Service {
	return predicate.Service(sql.FieldNEQ(FieldPort, v))
}

// PortIn applies the In predicate on the "port" field.
func PortIn(vs ...uint32) predicate.Service {
	return predicate.Service(sql.FieldIn(FieldPort, vs...))
}

// PortNotIn applies the NotIn predicate on the "port" field.
func PortNotIn(vs ...uint32) predicate.Service {
	return predicate.Service(sql.FieldNotIn(FieldPort, vs...))
}

// PortGT applies the GT predicate on the "port" field.
func PortGT(v uint32) predicate.Service {
	return predicate.Service(sql.FieldGT(FieldPort, v))
}

// PortGTE applies the GTE predicate on the "port" field.
func PortGTE(v uint32) predicate.Service {
	return predicate.Service(sql.FieldGTE(FieldPort, v))
}

// PortLT applies the LT predicate on the "port" field.
func PortLT(v uint32) predicate.Service {
	return predicate.Service(sql.FieldLT(FieldPort, v))
}

// PortLTE applies the LTE predicate on the "port" field.
func PortLTE(v uint32) predicate.Service {
	return predicate.Service(sql.FieldLTE(FieldPort, v))
}

// ContainerIDEQ applies the EQ predicate on the "container_id" field.
func ContainerIDEQ(v string) predicate.Service {
	return predicate.Service(sql.FieldEQ(FieldContainerID, v))
}

// ContainerIDNEQ applies the NEQ predicate on the "container_id" field.
func ContainerIDNEQ(v string) predicate.Service {
	return predicate.Service(sql.FieldNEQ(FieldContainerID, v))
}

// ContainerIDIn applies the In predicate on the "container_id" field.
func ContainerIDIn(vs ...string) predicate.Service {
	return predicate.Service(sql.FieldIn(FieldContainerID, vs...))
}

// ContainerIDNotIn applies the NotIn predicate on the "container_id" field.
func ContainerIDNotIn(vs ...string) predicate.Service {
	return predicate.Service(sql.FieldNotIn(FieldContainerID, vs...))
}

// ContainerIDGT applies the GT predicate on the "container_id" field.
func ContainerIDGT(v string) predicate.Service {
	return predicate.Service(sql.FieldGT(FieldContainerID, v))
}

// ContainerIDGTE applies the GTE predicate on the "container_id" field.
func ContainerIDGTE(v string) predicate.Service {
	return predicate.Service(sql.FieldGTE(FieldContainerID, v))
}

// ContainerIDLT applies the LT predicate on the "container_id" field.
func ContainerIDLT(v string) predicate.Service {
	return predicate.Service(sql.FieldLT(FieldContainerID, v))
}

// ContainerIDLTE applies the LTE predicate on the "container_id" field.
func ContainerIDLTE(v string) predicate.Service {
	return predicate.Service(sql.FieldLTE(FieldContainerID, v))
}

// ContainerIDContains applies the Contains predicate on the "container_id" field.
func ContainerIDContains(v string) predicate.Service {
	return predicate.Service(sql.FieldContains(FieldContainerID, v))
}

// ContainerIDHasPrefix applies the HasPrefix predicate on the "container_id" field.
func ContainerIDHasPrefix(v string) predicate.Service {
	return predicate.Service(sql.FieldHasPrefix(FieldContainerID, v))
}

// ContainerIDHasSuffix applies the HasSuffix predicate on the "container_id" field.
func ContainerIDHasSuffix(v string) predicate.Service {
	return predicate.Service(sql.FieldHasSuffix(FieldContainerID, v))
}

// ContainerIDIsNil applies the IsNil predicate on the "container_id" field.
func ContainerIDIsNil() predicate.Service {
	return predicate.Service(sql.FieldIsNull(FieldContainerID))
}

// ContainerIDNotNil applies the NotNil predicate on the "container_id" field.
func ContainerIDNotNil() predicate.Service {
	return predicate.Service(sql.FieldNotNull(FieldContainerID))
}

// ContainerIDEqualFold applies the EqualFold predicate on the "container_id" field.
func ContainerIDEqualFold(v string) predicate.Service {
	return predicate.Service(sql.FieldEqualFold(FieldContainerID, v))
}

// ContainerIDContainsFold applies the ContainsFold predicate on the "container_id" field.
func ContainerIDContainsFold(v string) predicate.Service {
	return predicate.Service(sql.FieldContainsFold(FieldContainerID, v))
}

// HasUser applies the HasEdge predicate on the "user" edge.
func HasUser() predicate.Service {
	return predicate.Service(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, UserTable, UserColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUserWith applies the HasEdge predicate on the "user" edge with a given conditions (other predicates).
func HasUserWith(preds ...predicate.User) predicate.Service {
	return predicate.Service(func(s *sql.Selector) {
		step := newUserStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasPlugins applies the HasEdge predicate on the "plugins" edge.
func HasPlugins() predicate.Service {
	return predicate.Service(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2M, false, PluginsTable, PluginsPrimaryKey...),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasPluginsWith applies the HasEdge predicate on the "plugins" edge with a given conditions (other predicates).
func HasPluginsWith(preds ...predicate.Plugin) predicate.Service {
	return predicate.Service(func(s *sql.Selector) {
		step := newPluginsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasWorkspaces applies the HasEdge predicate on the "workspaces" edge.
func HasWorkspaces() predicate.Service {
	return predicate.Service(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, WorkspacesTable, WorkspacesColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasWorkspacesWith applies the HasEdge predicate on the "workspaces" edge with a given conditions (other predicates).
func HasWorkspacesWith(preds ...predicate.Workspace) predicate.Service {
	return predicate.Service(func(s *sql.Selector) {
		step := newWorkspacesStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasFilters applies the HasEdge predicate on the "filters" edge.
func HasFilters() predicate.Service {
	return predicate.Service(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, FiltersTable, FiltersColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasFiltersWith applies the HasEdge predicate on the "filters" edge with a given conditions (other predicates).
func HasFiltersWith(preds ...predicate.Filter) predicate.Service {
	return predicate.Service(func(s *sql.Selector) {
		step := newFiltersStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasSessions applies the HasEdge predicate on the "sessions" edge.
func HasSessions() predicate.Service {
	return predicate.Service(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, SessionsTable, SessionsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasSessionsWith applies the HasEdge predicate on the "sessions" edge with a given conditions (other predicates).
func HasSessionsWith(preds ...predicate.Session) predicate.Service {
	return predicate.Service(func(s *sql.Selector) {
		step := newSessionsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Service) predicate.Service {
	return predicate.Service(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Service) predicate.Service {
	return predicate.Service(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Service) predicate.Service {
	return predicate.Service(sql.NotPredicates(p))
}
