// Code generated by ent, DO NOT EDIT.

package ent

import (
	"altron/core/repositories/ent/analyzercomponent"
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
)

// AnalyzerComponent is the model entity for the AnalyzerComponent schema.
type AnalyzerComponent struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the AnalyzerComponentQuery when eager-loading is set.
	Edges        AnalyzerComponentEdges `json:"edges"`
	selectValues sql.SelectValues
}

// AnalyzerComponentEdges holds the relations/edges for other nodes in the graph.
type AnalyzerComponentEdges struct {
	// AnalyzerPayloads holds the value of the analyzer_payloads edge.
	AnalyzerPayloads []*AnalyzerPayload `json:"analyzer_payloads,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// AnalyzerPayloadsOrErr returns the AnalyzerPayloads value or an error if the edge
// was not loaded in eager-loading.
func (e AnalyzerComponentEdges) AnalyzerPayloadsOrErr() ([]*AnalyzerPayload, error) {
	if e.loadedTypes[0] {
		return e.AnalyzerPayloads, nil
	}
	return nil, &NotLoadedError{edge: "analyzer_payloads"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*AnalyzerComponent) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case analyzercomponent.FieldName:
			values[i] = new(sql.NullString)
		case analyzercomponent.FieldID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the AnalyzerComponent fields.
func (ac *AnalyzerComponent) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case analyzercomponent.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				ac.ID = *value
			}
		case analyzercomponent.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				ac.Name = value.String
			}
		default:
			ac.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the AnalyzerComponent.
// This includes values selected through modifiers, order, etc.
func (ac *AnalyzerComponent) Value(name string) (ent.Value, error) {
	return ac.selectValues.Get(name)
}

// QueryAnalyzerPayloads queries the "analyzer_payloads" edge of the AnalyzerComponent entity.
func (ac *AnalyzerComponent) QueryAnalyzerPayloads() *AnalyzerPayloadQuery {
	return NewAnalyzerComponentClient(ac.config).QueryAnalyzerPayloads(ac)
}

// Update returns a builder for updating this AnalyzerComponent.
// Note that you need to call AnalyzerComponent.Unwrap() before calling this method if this AnalyzerComponent
// was returned from a transaction, and the transaction was committed or rolled back.
func (ac *AnalyzerComponent) Update() *AnalyzerComponentUpdateOne {
	return NewAnalyzerComponentClient(ac.config).UpdateOne(ac)
}

// Unwrap unwraps the AnalyzerComponent entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (ac *AnalyzerComponent) Unwrap() *AnalyzerComponent {
	_tx, ok := ac.config.driver.(*txDriver)
	if !ok {
		panic("ent: AnalyzerComponent is not a transactional entity")
	}
	ac.config.driver = _tx.drv
	return ac
}

// String implements the fmt.Stringer.
func (ac *AnalyzerComponent) String() string {
	var builder strings.Builder
	builder.WriteString("AnalyzerComponent(")
	builder.WriteString(fmt.Sprintf("id=%v, ", ac.ID))
	builder.WriteString("name=")
	builder.WriteString(ac.Name)
	builder.WriteByte(')')
	return builder.String()
}

// AnalyzerComponents is a parsable slice of AnalyzerComponent.
type AnalyzerComponents []*AnalyzerComponent
