// Code generated by ent, DO NOT EDIT.

package ent

import (
	"altron/core/repositories/ent/analyzercomponent"
	"altron/core/repositories/ent/predicate"
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// AnalyzerComponentDelete is the builder for deleting a AnalyzerComponent entity.
type AnalyzerComponentDelete struct {
	config
	hooks    []Hook
	mutation *AnalyzerComponentMutation
}

// Where appends a list predicates to the AnalyzerComponentDelete builder.
func (acd *AnalyzerComponentDelete) Where(ps ...predicate.AnalyzerComponent) *AnalyzerComponentDelete {
	acd.mutation.Where(ps...)
	return acd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (acd *AnalyzerComponentDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, acd.sqlExec, acd.mutation, acd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (acd *AnalyzerComponentDelete) ExecX(ctx context.Context) int {
	n, err := acd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (acd *AnalyzerComponentDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(analyzercomponent.Table, sqlgraph.NewFieldSpec(analyzercomponent.FieldID, field.TypeUUID))
	if ps := acd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, acd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	acd.mutation.done = true
	return affected, err
}

// AnalyzerComponentDeleteOne is the builder for deleting a single AnalyzerComponent entity.
type AnalyzerComponentDeleteOne struct {
	acd *AnalyzerComponentDelete
}

// Where appends a list predicates to the AnalyzerComponentDelete builder.
func (acdo *AnalyzerComponentDeleteOne) Where(ps ...predicate.AnalyzerComponent) *AnalyzerComponentDeleteOne {
	acdo.acd.mutation.Where(ps...)
	return acdo
}

// Exec executes the deletion query.
func (acdo *AnalyzerComponentDeleteOne) Exec(ctx context.Context) error {
	n, err := acdo.acd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{analyzercomponent.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (acdo *AnalyzerComponentDeleteOne) ExecX(ctx context.Context) {
	if err := acdo.Exec(ctx); err != nil {
		panic(err)
	}
}
