// Code generated by ent, DO NOT EDIT.

package ent

import (
	"altron/core/repositories/ent/analyzercomponent"
	"altron/core/repositories/ent/analyzerpayload"
	"altron/core/repositories/ent/workspace"
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
)

// AnalyzerPayload is the model entity for the AnalyzerPayload schema.
type AnalyzerPayload struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// WorkspaceID holds the value of the "workspace_id" field.
	WorkspaceID uuid.UUID `json:"workspace_id,omitempty"`
	// Value holds the value of the "value" field.
	Value string `json:"value,omitempty"`
	// Number holds the value of the "number" field.
	Number int `json:"number,omitempty"`
	// AnalyzerComponentID holds the value of the "analyzer_component_id" field.
	AnalyzerComponentID uuid.UUID `json:"analyzer_component_id,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the AnalyzerPayloadQuery when eager-loading is set.
	Edges        AnalyzerPayloadEdges `json:"edges"`
	selectValues sql.SelectValues
}

// AnalyzerPayloadEdges holds the relations/edges for other nodes in the graph.
type AnalyzerPayloadEdges struct {
	// Workspace holds the value of the workspace edge.
	Workspace *Workspace `json:"workspace,omitempty"`
	// AnalyzerComponent holds the value of the analyzer_component edge.
	AnalyzerComponent *AnalyzerComponent `json:"analyzer_component,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// WorkspaceOrErr returns the Workspace value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e AnalyzerPayloadEdges) WorkspaceOrErr() (*Workspace, error) {
	if e.loadedTypes[0] {
		if e.Workspace == nil {
			// Edge was loaded but was not found.
			return nil, &NotFoundError{label: workspace.Label}
		}
		return e.Workspace, nil
	}
	return nil, &NotLoadedError{edge: "workspace"}
}

// AnalyzerComponentOrErr returns the AnalyzerComponent value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e AnalyzerPayloadEdges) AnalyzerComponentOrErr() (*AnalyzerComponent, error) {
	if e.loadedTypes[1] {
		if e.AnalyzerComponent == nil {
			// Edge was loaded but was not found.
			return nil, &NotFoundError{label: analyzercomponent.Label}
		}
		return e.AnalyzerComponent, nil
	}
	return nil, &NotLoadedError{edge: "analyzer_component"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*AnalyzerPayload) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case analyzerpayload.FieldNumber:
			values[i] = new(sql.NullInt64)
		case analyzerpayload.FieldValue:
			values[i] = new(sql.NullString)
		case analyzerpayload.FieldID, analyzerpayload.FieldWorkspaceID, analyzerpayload.FieldAnalyzerComponentID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the AnalyzerPayload fields.
func (ap *AnalyzerPayload) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case analyzerpayload.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				ap.ID = *value
			}
		case analyzerpayload.FieldWorkspaceID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field workspace_id", values[i])
			} else if value != nil {
				ap.WorkspaceID = *value
			}
		case analyzerpayload.FieldValue:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field value", values[i])
			} else if value.Valid {
				ap.Value = value.String
			}
		case analyzerpayload.FieldNumber:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field number", values[i])
			} else if value.Valid {
				ap.Number = int(value.Int64)
			}
		case analyzerpayload.FieldAnalyzerComponentID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field analyzer_component_id", values[i])
			} else if value != nil {
				ap.AnalyzerComponentID = *value
			}
		default:
			ap.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// GetValue returns the ent.Value that was dynamically selected and assigned to the AnalyzerPayload.
// This includes values selected through modifiers, order, etc.
func (ap *AnalyzerPayload) GetValue(name string) (ent.Value, error) {
	return ap.selectValues.Get(name)
}

// QueryWorkspace queries the "workspace" edge of the AnalyzerPayload entity.
func (ap *AnalyzerPayload) QueryWorkspace() *WorkspaceQuery {
	return NewAnalyzerPayloadClient(ap.config).QueryWorkspace(ap)
}

// QueryAnalyzerComponent queries the "analyzer_component" edge of the AnalyzerPayload entity.
func (ap *AnalyzerPayload) QueryAnalyzerComponent() *AnalyzerComponentQuery {
	return NewAnalyzerPayloadClient(ap.config).QueryAnalyzerComponent(ap)
}

// Update returns a builder for updating this AnalyzerPayload.
// Note that you need to call AnalyzerPayload.Unwrap() before calling this method if this AnalyzerPayload
// was returned from a transaction, and the transaction was committed or rolled back.
func (ap *AnalyzerPayload) Update() *AnalyzerPayloadUpdateOne {
	return NewAnalyzerPayloadClient(ap.config).UpdateOne(ap)
}

// Unwrap unwraps the AnalyzerPayload entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (ap *AnalyzerPayload) Unwrap() *AnalyzerPayload {
	_tx, ok := ap.config.driver.(*txDriver)
	if !ok {
		panic("ent: AnalyzerPayload is not a transactional entity")
	}
	ap.config.driver = _tx.drv
	return ap
}

// String implements the fmt.Stringer.
func (ap *AnalyzerPayload) String() string {
	var builder strings.Builder
	builder.WriteString("AnalyzerPayload(")
	builder.WriteString(fmt.Sprintf("id=%v, ", ap.ID))
	builder.WriteString("workspace_id=")
	builder.WriteString(fmt.Sprintf("%v", ap.WorkspaceID))
	builder.WriteString(", ")
	builder.WriteString("value=")
	builder.WriteString(ap.Value)
	builder.WriteString(", ")
	builder.WriteString("number=")
	builder.WriteString(fmt.Sprintf("%v", ap.Number))
	builder.WriteString(", ")
	builder.WriteString("analyzer_component_id=")
	builder.WriteString(fmt.Sprintf("%v", ap.AnalyzerComponentID))
	builder.WriteByte(')')
	return builder.String()
}

// AnalyzerPayloads is a parsable slice of AnalyzerPayload.
type AnalyzerPayloads []*AnalyzerPayload
