// Code generated by ent, DO NOT EDIT.

package ent

import (
	"altron/core/repositories/ent/analyzercomponent"
	"altron/core/repositories/ent/analyzerpayload"
	"altron/core/repositories/ent/workspace"
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// AnalyzerPayloadCreate is the builder for creating a AnalyzerPayload entity.
type AnalyzerPayloadCreate struct {
	config
	mutation *AnalyzerPayloadMutation
	hooks    []Hook
}

// SetWorkspaceID sets the "workspace_id" field.
func (apc *AnalyzerPayloadCreate) SetWorkspaceID(u uuid.UUID) *AnalyzerPayloadCreate {
	apc.mutation.SetWorkspaceID(u)
	return apc
}

// SetValue sets the "value" field.
func (apc *AnalyzerPayloadCreate) SetValue(s string) *AnalyzerPayloadCreate {
	apc.mutation.SetValue(s)
	return apc
}

// SetNumber sets the "number" field.
func (apc *AnalyzerPayloadCreate) SetNumber(i int) *AnalyzerPayloadCreate {
	apc.mutation.SetNumber(i)
	return apc
}

// SetAnalyzerComponentID sets the "analyzer_component_id" field.
func (apc *AnalyzerPayloadCreate) SetAnalyzerComponentID(u uuid.UUID) *AnalyzerPayloadCreate {
	apc.mutation.SetAnalyzerComponentID(u)
	return apc
}

// SetID sets the "id" field.
func (apc *AnalyzerPayloadCreate) SetID(u uuid.UUID) *AnalyzerPayloadCreate {
	apc.mutation.SetID(u)
	return apc
}

// SetNillableID sets the "id" field if the given value is not nil.
func (apc *AnalyzerPayloadCreate) SetNillableID(u *uuid.UUID) *AnalyzerPayloadCreate {
	if u != nil {
		apc.SetID(*u)
	}
	return apc
}

// SetWorkspace sets the "workspace" edge to the Workspace entity.
func (apc *AnalyzerPayloadCreate) SetWorkspace(w *Workspace) *AnalyzerPayloadCreate {
	return apc.SetWorkspaceID(w.ID)
}

// SetAnalyzerComponent sets the "analyzer_component" edge to the AnalyzerComponent entity.
func (apc *AnalyzerPayloadCreate) SetAnalyzerComponent(a *AnalyzerComponent) *AnalyzerPayloadCreate {
	return apc.SetAnalyzerComponentID(a.ID)
}

// Mutation returns the AnalyzerPayloadMutation object of the builder.
func (apc *AnalyzerPayloadCreate) Mutation() *AnalyzerPayloadMutation {
	return apc.mutation
}

// Save creates the AnalyzerPayload in the database.
func (apc *AnalyzerPayloadCreate) Save(ctx context.Context) (*AnalyzerPayload, error) {
	apc.defaults()
	return withHooks(ctx, apc.sqlSave, apc.mutation, apc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (apc *AnalyzerPayloadCreate) SaveX(ctx context.Context) *AnalyzerPayload {
	v, err := apc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (apc *AnalyzerPayloadCreate) Exec(ctx context.Context) error {
	_, err := apc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (apc *AnalyzerPayloadCreate) ExecX(ctx context.Context) {
	if err := apc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (apc *AnalyzerPayloadCreate) defaults() {
	if _, ok := apc.mutation.ID(); !ok {
		v := analyzerpayload.DefaultID()
		apc.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (apc *AnalyzerPayloadCreate) check() error {
	if _, ok := apc.mutation.WorkspaceID(); !ok {
		return &ValidationError{Name: "workspace_id", err: errors.New(`ent: missing required field "AnalyzerPayload.workspace_id"`)}
	}
	if _, ok := apc.mutation.Value(); !ok {
		return &ValidationError{Name: "value", err: errors.New(`ent: missing required field "AnalyzerPayload.value"`)}
	}
	if _, ok := apc.mutation.Number(); !ok {
		return &ValidationError{Name: "number", err: errors.New(`ent: missing required field "AnalyzerPayload.number"`)}
	}
	if _, ok := apc.mutation.AnalyzerComponentID(); !ok {
		return &ValidationError{Name: "analyzer_component_id", err: errors.New(`ent: missing required field "AnalyzerPayload.analyzer_component_id"`)}
	}
	if _, ok := apc.mutation.WorkspaceID(); !ok {
		return &ValidationError{Name: "workspace", err: errors.New(`ent: missing required edge "AnalyzerPayload.workspace"`)}
	}
	if _, ok := apc.mutation.AnalyzerComponentID(); !ok {
		return &ValidationError{Name: "analyzer_component", err: errors.New(`ent: missing required edge "AnalyzerPayload.analyzer_component"`)}
	}
	return nil
}

func (apc *AnalyzerPayloadCreate) sqlSave(ctx context.Context) (*AnalyzerPayload, error) {
	if err := apc.check(); err != nil {
		return nil, err
	}
	_node, _spec := apc.createSpec()
	if err := sqlgraph.CreateNode(ctx, apc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	apc.mutation.id = &_node.ID
	apc.mutation.done = true
	return _node, nil
}

func (apc *AnalyzerPayloadCreate) createSpec() (*AnalyzerPayload, *sqlgraph.CreateSpec) {
	var (
		_node = &AnalyzerPayload{config: apc.config}
		_spec = sqlgraph.NewCreateSpec(analyzerpayload.Table, sqlgraph.NewFieldSpec(analyzerpayload.FieldID, field.TypeUUID))
	)
	if id, ok := apc.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := apc.mutation.Value(); ok {
		_spec.SetField(analyzerpayload.FieldValue, field.TypeString, value)
		_node.Value = value
	}
	if value, ok := apc.mutation.Number(); ok {
		_spec.SetField(analyzerpayload.FieldNumber, field.TypeInt, value)
		_node.Number = value
	}
	if nodes := apc.mutation.WorkspaceIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   analyzerpayload.WorkspaceTable,
			Columns: []string{analyzerpayload.WorkspaceColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(workspace.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.WorkspaceID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := apc.mutation.AnalyzerComponentIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   analyzerpayload.AnalyzerComponentTable,
			Columns: []string{analyzerpayload.AnalyzerComponentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(analyzercomponent.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.AnalyzerComponentID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// AnalyzerPayloadCreateBulk is the builder for creating many AnalyzerPayload entities in bulk.
type AnalyzerPayloadCreateBulk struct {
	config
	err      error
	builders []*AnalyzerPayloadCreate
}

// Save creates the AnalyzerPayload entities in the database.
func (apcb *AnalyzerPayloadCreateBulk) Save(ctx context.Context) ([]*AnalyzerPayload, error) {
	if apcb.err != nil {
		return nil, apcb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(apcb.builders))
	nodes := make([]*AnalyzerPayload, len(apcb.builders))
	mutators := make([]Mutator, len(apcb.builders))
	for i := range apcb.builders {
		func(i int, root context.Context) {
			builder := apcb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*AnalyzerPayloadMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, apcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, apcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, apcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (apcb *AnalyzerPayloadCreateBulk) SaveX(ctx context.Context) []*AnalyzerPayload {
	v, err := apcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (apcb *AnalyzerPayloadCreateBulk) Exec(ctx context.Context) error {
	_, err := apcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (apcb *AnalyzerPayloadCreateBulk) ExecX(ctx context.Context) {
	if err := apcb.Exec(ctx); err != nil {
		panic(err)
	}
}
