// Code generated by ent, DO NOT EDIT.

package ent

import (
	"altron/core/repositories/ent/analyzercomponent"
	"altron/core/repositories/ent/analyzerpayload"
	"altron/core/repositories/ent/predicate"
	"altron/core/repositories/ent/workspace"
	"context"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// AnalyzerPayloadQuery is the builder for querying AnalyzerPayload entities.
type AnalyzerPayloadQuery struct {
	config
	ctx                   *QueryContext
	order                 []analyzerpayload.OrderOption
	inters                []Interceptor
	predicates            []predicate.AnalyzerPayload
	withWorkspace         *WorkspaceQuery
	withAnalyzerComponent *AnalyzerComponentQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the AnalyzerPayloadQuery builder.
func (apq *AnalyzerPayloadQuery) Where(ps ...predicate.AnalyzerPayload) *AnalyzerPayloadQuery {
	apq.predicates = append(apq.predicates, ps...)
	return apq
}

// Limit the number of records to be returned by this query.
func (apq *AnalyzerPayloadQuery) Limit(limit int) *AnalyzerPayloadQuery {
	apq.ctx.Limit = &limit
	return apq
}

// Offset to start from.
func (apq *AnalyzerPayloadQuery) Offset(offset int) *AnalyzerPayloadQuery {
	apq.ctx.Offset = &offset
	return apq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (apq *AnalyzerPayloadQuery) Unique(unique bool) *AnalyzerPayloadQuery {
	apq.ctx.Unique = &unique
	return apq
}

// Order specifies how the records should be ordered.
func (apq *AnalyzerPayloadQuery) Order(o ...analyzerpayload.OrderOption) *AnalyzerPayloadQuery {
	apq.order = append(apq.order, o...)
	return apq
}

// QueryWorkspace chains the current query on the "workspace" edge.
func (apq *AnalyzerPayloadQuery) QueryWorkspace() *WorkspaceQuery {
	query := (&WorkspaceClient{config: apq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := apq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := apq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(analyzerpayload.Table, analyzerpayload.FieldID, selector),
			sqlgraph.To(workspace.Table, workspace.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, analyzerpayload.WorkspaceTable, analyzerpayload.WorkspaceColumn),
		)
		fromU = sqlgraph.SetNeighbors(apq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryAnalyzerComponent chains the current query on the "analyzer_component" edge.
func (apq *AnalyzerPayloadQuery) QueryAnalyzerComponent() *AnalyzerComponentQuery {
	query := (&AnalyzerComponentClient{config: apq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := apq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := apq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(analyzerpayload.Table, analyzerpayload.FieldID, selector),
			sqlgraph.To(analyzercomponent.Table, analyzercomponent.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, analyzerpayload.AnalyzerComponentTable, analyzerpayload.AnalyzerComponentColumn),
		)
		fromU = sqlgraph.SetNeighbors(apq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first AnalyzerPayload entity from the query.
// Returns a *NotFoundError when no AnalyzerPayload was found.
func (apq *AnalyzerPayloadQuery) First(ctx context.Context) (*AnalyzerPayload, error) {
	nodes, err := apq.Limit(1).All(setContextOp(ctx, apq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{analyzerpayload.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (apq *AnalyzerPayloadQuery) FirstX(ctx context.Context) *AnalyzerPayload {
	node, err := apq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first AnalyzerPayload ID from the query.
// Returns a *NotFoundError when no AnalyzerPayload ID was found.
func (apq *AnalyzerPayloadQuery) FirstID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = apq.Limit(1).IDs(setContextOp(ctx, apq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{analyzerpayload.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (apq *AnalyzerPayloadQuery) FirstIDX(ctx context.Context) uuid.UUID {
	id, err := apq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single AnalyzerPayload entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one AnalyzerPayload entity is found.
// Returns a *NotFoundError when no AnalyzerPayload entities are found.
func (apq *AnalyzerPayloadQuery) Only(ctx context.Context) (*AnalyzerPayload, error) {
	nodes, err := apq.Limit(2).All(setContextOp(ctx, apq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{analyzerpayload.Label}
	default:
		return nil, &NotSingularError{analyzerpayload.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (apq *AnalyzerPayloadQuery) OnlyX(ctx context.Context) *AnalyzerPayload {
	node, err := apq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only AnalyzerPayload ID in the query.
// Returns a *NotSingularError when more than one AnalyzerPayload ID is found.
// Returns a *NotFoundError when no entities are found.
func (apq *AnalyzerPayloadQuery) OnlyID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = apq.Limit(2).IDs(setContextOp(ctx, apq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{analyzerpayload.Label}
	default:
		err = &NotSingularError{analyzerpayload.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (apq *AnalyzerPayloadQuery) OnlyIDX(ctx context.Context) uuid.UUID {
	id, err := apq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of AnalyzerPayloads.
func (apq *AnalyzerPayloadQuery) All(ctx context.Context) ([]*AnalyzerPayload, error) {
	ctx = setContextOp(ctx, apq.ctx, "All")
	if err := apq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*AnalyzerPayload, *AnalyzerPayloadQuery]()
	return withInterceptors[[]*AnalyzerPayload](ctx, apq, qr, apq.inters)
}

// AllX is like All, but panics if an error occurs.
func (apq *AnalyzerPayloadQuery) AllX(ctx context.Context) []*AnalyzerPayload {
	nodes, err := apq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of AnalyzerPayload IDs.
func (apq *AnalyzerPayloadQuery) IDs(ctx context.Context) (ids []uuid.UUID, err error) {
	if apq.ctx.Unique == nil && apq.path != nil {
		apq.Unique(true)
	}
	ctx = setContextOp(ctx, apq.ctx, "IDs")
	if err = apq.Select(analyzerpayload.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (apq *AnalyzerPayloadQuery) IDsX(ctx context.Context) []uuid.UUID {
	ids, err := apq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (apq *AnalyzerPayloadQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, apq.ctx, "Count")
	if err := apq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, apq, querierCount[*AnalyzerPayloadQuery](), apq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (apq *AnalyzerPayloadQuery) CountX(ctx context.Context) int {
	count, err := apq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (apq *AnalyzerPayloadQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, apq.ctx, "Exist")
	switch _, err := apq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (apq *AnalyzerPayloadQuery) ExistX(ctx context.Context) bool {
	exist, err := apq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the AnalyzerPayloadQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (apq *AnalyzerPayloadQuery) Clone() *AnalyzerPayloadQuery {
	if apq == nil {
		return nil
	}
	return &AnalyzerPayloadQuery{
		config:                apq.config,
		ctx:                   apq.ctx.Clone(),
		order:                 append([]analyzerpayload.OrderOption{}, apq.order...),
		inters:                append([]Interceptor{}, apq.inters...),
		predicates:            append([]predicate.AnalyzerPayload{}, apq.predicates...),
		withWorkspace:         apq.withWorkspace.Clone(),
		withAnalyzerComponent: apq.withAnalyzerComponent.Clone(),
		// clone intermediate query.
		sql:  apq.sql.Clone(),
		path: apq.path,
	}
}

// WithWorkspace tells the query-builder to eager-load the nodes that are connected to
// the "workspace" edge. The optional arguments are used to configure the query builder of the edge.
func (apq *AnalyzerPayloadQuery) WithWorkspace(opts ...func(*WorkspaceQuery)) *AnalyzerPayloadQuery {
	query := (&WorkspaceClient{config: apq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	apq.withWorkspace = query
	return apq
}

// WithAnalyzerComponent tells the query-builder to eager-load the nodes that are connected to
// the "analyzer_component" edge. The optional arguments are used to configure the query builder of the edge.
func (apq *AnalyzerPayloadQuery) WithAnalyzerComponent(opts ...func(*AnalyzerComponentQuery)) *AnalyzerPayloadQuery {
	query := (&AnalyzerComponentClient{config: apq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	apq.withAnalyzerComponent = query
	return apq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		WorkspaceID uuid.UUID `json:"workspace_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.AnalyzerPayload.Query().
//		GroupBy(analyzerpayload.FieldWorkspaceID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (apq *AnalyzerPayloadQuery) GroupBy(field string, fields ...string) *AnalyzerPayloadGroupBy {
	apq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &AnalyzerPayloadGroupBy{build: apq}
	grbuild.flds = &apq.ctx.Fields
	grbuild.label = analyzerpayload.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		WorkspaceID uuid.UUID `json:"workspace_id,omitempty"`
//	}
//
//	client.AnalyzerPayload.Query().
//		Select(analyzerpayload.FieldWorkspaceID).
//		Scan(ctx, &v)
func (apq *AnalyzerPayloadQuery) Select(fields ...string) *AnalyzerPayloadSelect {
	apq.ctx.Fields = append(apq.ctx.Fields, fields...)
	sbuild := &AnalyzerPayloadSelect{AnalyzerPayloadQuery: apq}
	sbuild.label = analyzerpayload.Label
	sbuild.flds, sbuild.scan = &apq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a AnalyzerPayloadSelect configured with the given aggregations.
func (apq *AnalyzerPayloadQuery) Aggregate(fns ...AggregateFunc) *AnalyzerPayloadSelect {
	return apq.Select().Aggregate(fns...)
}

func (apq *AnalyzerPayloadQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range apq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, apq); err != nil {
				return err
			}
		}
	}
	for _, f := range apq.ctx.Fields {
		if !analyzerpayload.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if apq.path != nil {
		prev, err := apq.path(ctx)
		if err != nil {
			return err
		}
		apq.sql = prev
	}
	return nil
}

func (apq *AnalyzerPayloadQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*AnalyzerPayload, error) {
	var (
		nodes       = []*AnalyzerPayload{}
		_spec       = apq.querySpec()
		loadedTypes = [2]bool{
			apq.withWorkspace != nil,
			apq.withAnalyzerComponent != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*AnalyzerPayload).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &AnalyzerPayload{config: apq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, apq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := apq.withWorkspace; query != nil {
		if err := apq.loadWorkspace(ctx, query, nodes, nil,
			func(n *AnalyzerPayload, e *Workspace) { n.Edges.Workspace = e }); err != nil {
			return nil, err
		}
	}
	if query := apq.withAnalyzerComponent; query != nil {
		if err := apq.loadAnalyzerComponent(ctx, query, nodes, nil,
			func(n *AnalyzerPayload, e *AnalyzerComponent) { n.Edges.AnalyzerComponent = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (apq *AnalyzerPayloadQuery) loadWorkspace(ctx context.Context, query *WorkspaceQuery, nodes []*AnalyzerPayload, init func(*AnalyzerPayload), assign func(*AnalyzerPayload, *Workspace)) error {
	ids := make([]uuid.UUID, 0, len(nodes))
	nodeids := make(map[uuid.UUID][]*AnalyzerPayload)
	for i := range nodes {
		fk := nodes[i].WorkspaceID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(workspace.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "workspace_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (apq *AnalyzerPayloadQuery) loadAnalyzerComponent(ctx context.Context, query *AnalyzerComponentQuery, nodes []*AnalyzerPayload, init func(*AnalyzerPayload), assign func(*AnalyzerPayload, *AnalyzerComponent)) error {
	ids := make([]uuid.UUID, 0, len(nodes))
	nodeids := make(map[uuid.UUID][]*AnalyzerPayload)
	for i := range nodes {
		fk := nodes[i].AnalyzerComponentID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(analyzercomponent.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "analyzer_component_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (apq *AnalyzerPayloadQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := apq.querySpec()
	_spec.Node.Columns = apq.ctx.Fields
	if len(apq.ctx.Fields) > 0 {
		_spec.Unique = apq.ctx.Unique != nil && *apq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, apq.driver, _spec)
}

func (apq *AnalyzerPayloadQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(analyzerpayload.Table, analyzerpayload.Columns, sqlgraph.NewFieldSpec(analyzerpayload.FieldID, field.TypeUUID))
	_spec.From = apq.sql
	if unique := apq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if apq.path != nil {
		_spec.Unique = true
	}
	if fields := apq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, analyzerpayload.FieldID)
		for i := range fields {
			if fields[i] != analyzerpayload.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if apq.withWorkspace != nil {
			_spec.Node.AddColumnOnce(analyzerpayload.FieldWorkspaceID)
		}
		if apq.withAnalyzerComponent != nil {
			_spec.Node.AddColumnOnce(analyzerpayload.FieldAnalyzerComponentID)
		}
	}
	if ps := apq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := apq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := apq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := apq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (apq *AnalyzerPayloadQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(apq.driver.Dialect())
	t1 := builder.Table(analyzerpayload.Table)
	columns := apq.ctx.Fields
	if len(columns) == 0 {
		columns = analyzerpayload.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if apq.sql != nil {
		selector = apq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if apq.ctx.Unique != nil && *apq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range apq.predicates {
		p(selector)
	}
	for _, p := range apq.order {
		p(selector)
	}
	if offset := apq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := apq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// AnalyzerPayloadGroupBy is the group-by builder for AnalyzerPayload entities.
type AnalyzerPayloadGroupBy struct {
	selector
	build *AnalyzerPayloadQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (apgb *AnalyzerPayloadGroupBy) Aggregate(fns ...AggregateFunc) *AnalyzerPayloadGroupBy {
	apgb.fns = append(apgb.fns, fns...)
	return apgb
}

// Scan applies the selector query and scans the result into the given value.
func (apgb *AnalyzerPayloadGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, apgb.build.ctx, "GroupBy")
	if err := apgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*AnalyzerPayloadQuery, *AnalyzerPayloadGroupBy](ctx, apgb.build, apgb, apgb.build.inters, v)
}

func (apgb *AnalyzerPayloadGroupBy) sqlScan(ctx context.Context, root *AnalyzerPayloadQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(apgb.fns))
	for _, fn := range apgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*apgb.flds)+len(apgb.fns))
		for _, f := range *apgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*apgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := apgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// AnalyzerPayloadSelect is the builder for selecting fields of AnalyzerPayload entities.
type AnalyzerPayloadSelect struct {
	*AnalyzerPayloadQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (aps *AnalyzerPayloadSelect) Aggregate(fns ...AggregateFunc) *AnalyzerPayloadSelect {
	aps.fns = append(aps.fns, fns...)
	return aps
}

// Scan applies the selector query and scans the result into the given value.
func (aps *AnalyzerPayloadSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, aps.ctx, "Select")
	if err := aps.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*AnalyzerPayloadQuery, *AnalyzerPayloadSelect](ctx, aps.AnalyzerPayloadQuery, aps, aps.inters, v)
}

func (aps *AnalyzerPayloadSelect) sqlScan(ctx context.Context, root *AnalyzerPayloadQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(aps.fns))
	for _, fn := range aps.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*aps.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := aps.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
