// Code generated by ent, DO NOT EDIT.

package ent

import (
	"altron/core/repositories/ent/cartsession"
	"altron/core/repositories/ent/predicate"
	"altron/core/repositories/ent/session"
	"altron/core/repositories/ent/workspace"
	"context"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// CartSessionQuery is the builder for querying CartSession entities.
type CartSessionQuery struct {
	config
	ctx           *QueryContext
	order         []cartsession.OrderOption
	inters        []Interceptor
	predicates    []predicate.CartSession
	withSession   *SessionQuery
	withWorkspace *WorkspaceQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the CartSessionQuery builder.
func (csq *CartSessionQuery) Where(ps ...predicate.CartSession) *CartSessionQuery {
	csq.predicates = append(csq.predicates, ps...)
	return csq
}

// Limit the number of records to be returned by this query.
func (csq *CartSessionQuery) Limit(limit int) *CartSessionQuery {
	csq.ctx.Limit = &limit
	return csq
}

// Offset to start from.
func (csq *CartSessionQuery) Offset(offset int) *CartSessionQuery {
	csq.ctx.Offset = &offset
	return csq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (csq *CartSessionQuery) Unique(unique bool) *CartSessionQuery {
	csq.ctx.Unique = &unique
	return csq
}

// Order specifies how the records should be ordered.
func (csq *CartSessionQuery) Order(o ...cartsession.OrderOption) *CartSessionQuery {
	csq.order = append(csq.order, o...)
	return csq
}

// QuerySession chains the current query on the "session" edge.
func (csq *CartSessionQuery) QuerySession() *SessionQuery {
	query := (&SessionClient{config: csq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := csq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := csq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(cartsession.Table, cartsession.FieldID, selector),
			sqlgraph.To(session.Table, session.FieldID),
			sqlgraph.Edge(sqlgraph.O2O, true, cartsession.SessionTable, cartsession.SessionColumn),
		)
		fromU = sqlgraph.SetNeighbors(csq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryWorkspace chains the current query on the "workspace" edge.
func (csq *CartSessionQuery) QueryWorkspace() *WorkspaceQuery {
	query := (&WorkspaceClient{config: csq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := csq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := csq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(cartsession.Table, cartsession.FieldID, selector),
			sqlgraph.To(workspace.Table, workspace.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, cartsession.WorkspaceTable, cartsession.WorkspaceColumn),
		)
		fromU = sqlgraph.SetNeighbors(csq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first CartSession entity from the query.
// Returns a *NotFoundError when no CartSession was found.
func (csq *CartSessionQuery) First(ctx context.Context) (*CartSession, error) {
	nodes, err := csq.Limit(1).All(setContextOp(ctx, csq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{cartsession.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (csq *CartSessionQuery) FirstX(ctx context.Context) *CartSession {
	node, err := csq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first CartSession ID from the query.
// Returns a *NotFoundError when no CartSession ID was found.
func (csq *CartSessionQuery) FirstID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = csq.Limit(1).IDs(setContextOp(ctx, csq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{cartsession.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (csq *CartSessionQuery) FirstIDX(ctx context.Context) uuid.UUID {
	id, err := csq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single CartSession entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one CartSession entity is found.
// Returns a *NotFoundError when no CartSession entities are found.
func (csq *CartSessionQuery) Only(ctx context.Context) (*CartSession, error) {
	nodes, err := csq.Limit(2).All(setContextOp(ctx, csq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{cartsession.Label}
	default:
		return nil, &NotSingularError{cartsession.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (csq *CartSessionQuery) OnlyX(ctx context.Context) *CartSession {
	node, err := csq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only CartSession ID in the query.
// Returns a *NotSingularError when more than one CartSession ID is found.
// Returns a *NotFoundError when no entities are found.
func (csq *CartSessionQuery) OnlyID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = csq.Limit(2).IDs(setContextOp(ctx, csq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{cartsession.Label}
	default:
		err = &NotSingularError{cartsession.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (csq *CartSessionQuery) OnlyIDX(ctx context.Context) uuid.UUID {
	id, err := csq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of CartSessions.
func (csq *CartSessionQuery) All(ctx context.Context) ([]*CartSession, error) {
	ctx = setContextOp(ctx, csq.ctx, "All")
	if err := csq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*CartSession, *CartSessionQuery]()
	return withInterceptors[[]*CartSession](ctx, csq, qr, csq.inters)
}

// AllX is like All, but panics if an error occurs.
func (csq *CartSessionQuery) AllX(ctx context.Context) []*CartSession {
	nodes, err := csq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of CartSession IDs.
func (csq *CartSessionQuery) IDs(ctx context.Context) (ids []uuid.UUID, err error) {
	if csq.ctx.Unique == nil && csq.path != nil {
		csq.Unique(true)
	}
	ctx = setContextOp(ctx, csq.ctx, "IDs")
	if err = csq.Select(cartsession.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (csq *CartSessionQuery) IDsX(ctx context.Context) []uuid.UUID {
	ids, err := csq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (csq *CartSessionQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, csq.ctx, "Count")
	if err := csq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, csq, querierCount[*CartSessionQuery](), csq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (csq *CartSessionQuery) CountX(ctx context.Context) int {
	count, err := csq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (csq *CartSessionQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, csq.ctx, "Exist")
	switch _, err := csq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (csq *CartSessionQuery) ExistX(ctx context.Context) bool {
	exist, err := csq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the CartSessionQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (csq *CartSessionQuery) Clone() *CartSessionQuery {
	if csq == nil {
		return nil
	}
	return &CartSessionQuery{
		config:        csq.config,
		ctx:           csq.ctx.Clone(),
		order:         append([]cartsession.OrderOption{}, csq.order...),
		inters:        append([]Interceptor{}, csq.inters...),
		predicates:    append([]predicate.CartSession{}, csq.predicates...),
		withSession:   csq.withSession.Clone(),
		withWorkspace: csq.withWorkspace.Clone(),
		// clone intermediate query.
		sql:  csq.sql.Clone(),
		path: csq.path,
	}
}

// WithSession tells the query-builder to eager-load the nodes that are connected to
// the "session" edge. The optional arguments are used to configure the query builder of the edge.
func (csq *CartSessionQuery) WithSession(opts ...func(*SessionQuery)) *CartSessionQuery {
	query := (&SessionClient{config: csq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	csq.withSession = query
	return csq
}

// WithWorkspace tells the query-builder to eager-load the nodes that are connected to
// the "workspace" edge. The optional arguments are used to configure the query builder of the edge.
func (csq *CartSessionQuery) WithWorkspace(opts ...func(*WorkspaceQuery)) *CartSessionQuery {
	query := (&WorkspaceClient{config: csq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	csq.withWorkspace = query
	return csq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		WorkspaceID uuid.UUID `json:"workspace_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.CartSession.Query().
//		GroupBy(cartsession.FieldWorkspaceID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (csq *CartSessionQuery) GroupBy(field string, fields ...string) *CartSessionGroupBy {
	csq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &CartSessionGroupBy{build: csq}
	grbuild.flds = &csq.ctx.Fields
	grbuild.label = cartsession.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		WorkspaceID uuid.UUID `json:"workspace_id,omitempty"`
//	}
//
//	client.CartSession.Query().
//		Select(cartsession.FieldWorkspaceID).
//		Scan(ctx, &v)
func (csq *CartSessionQuery) Select(fields ...string) *CartSessionSelect {
	csq.ctx.Fields = append(csq.ctx.Fields, fields...)
	sbuild := &CartSessionSelect{CartSessionQuery: csq}
	sbuild.label = cartsession.Label
	sbuild.flds, sbuild.scan = &csq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a CartSessionSelect configured with the given aggregations.
func (csq *CartSessionQuery) Aggregate(fns ...AggregateFunc) *CartSessionSelect {
	return csq.Select().Aggregate(fns...)
}

func (csq *CartSessionQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range csq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, csq); err != nil {
				return err
			}
		}
	}
	for _, f := range csq.ctx.Fields {
		if !cartsession.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if csq.path != nil {
		prev, err := csq.path(ctx)
		if err != nil {
			return err
		}
		csq.sql = prev
	}
	return nil
}

func (csq *CartSessionQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*CartSession, error) {
	var (
		nodes       = []*CartSession{}
		_spec       = csq.querySpec()
		loadedTypes = [2]bool{
			csq.withSession != nil,
			csq.withWorkspace != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*CartSession).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &CartSession{config: csq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, csq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := csq.withSession; query != nil {
		if err := csq.loadSession(ctx, query, nodes, nil,
			func(n *CartSession, e *Session) { n.Edges.Session = e }); err != nil {
			return nil, err
		}
	}
	if query := csq.withWorkspace; query != nil {
		if err := csq.loadWorkspace(ctx, query, nodes, nil,
			func(n *CartSession, e *Workspace) { n.Edges.Workspace = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (csq *CartSessionQuery) loadSession(ctx context.Context, query *SessionQuery, nodes []*CartSession, init func(*CartSession), assign func(*CartSession, *Session)) error {
	ids := make([]uuid.UUID, 0, len(nodes))
	nodeids := make(map[uuid.UUID][]*CartSession)
	for i := range nodes {
		fk := nodes[i].SessionID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(session.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "session_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (csq *CartSessionQuery) loadWorkspace(ctx context.Context, query *WorkspaceQuery, nodes []*CartSession, init func(*CartSession), assign func(*CartSession, *Workspace)) error {
	ids := make([]uuid.UUID, 0, len(nodes))
	nodeids := make(map[uuid.UUID][]*CartSession)
	for i := range nodes {
		fk := nodes[i].WorkspaceID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(workspace.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "workspace_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (csq *CartSessionQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := csq.querySpec()
	_spec.Node.Columns = csq.ctx.Fields
	if len(csq.ctx.Fields) > 0 {
		_spec.Unique = csq.ctx.Unique != nil && *csq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, csq.driver, _spec)
}

func (csq *CartSessionQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(cartsession.Table, cartsession.Columns, sqlgraph.NewFieldSpec(cartsession.FieldID, field.TypeUUID))
	_spec.From = csq.sql
	if unique := csq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if csq.path != nil {
		_spec.Unique = true
	}
	if fields := csq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, cartsession.FieldID)
		for i := range fields {
			if fields[i] != cartsession.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if csq.withSession != nil {
			_spec.Node.AddColumnOnce(cartsession.FieldSessionID)
		}
		if csq.withWorkspace != nil {
			_spec.Node.AddColumnOnce(cartsession.FieldWorkspaceID)
		}
	}
	if ps := csq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := csq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := csq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := csq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (csq *CartSessionQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(csq.driver.Dialect())
	t1 := builder.Table(cartsession.Table)
	columns := csq.ctx.Fields
	if len(columns) == 0 {
		columns = cartsession.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if csq.sql != nil {
		selector = csq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if csq.ctx.Unique != nil && *csq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range csq.predicates {
		p(selector)
	}
	for _, p := range csq.order {
		p(selector)
	}
	if offset := csq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := csq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// CartSessionGroupBy is the group-by builder for CartSession entities.
type CartSessionGroupBy struct {
	selector
	build *CartSessionQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (csgb *CartSessionGroupBy) Aggregate(fns ...AggregateFunc) *CartSessionGroupBy {
	csgb.fns = append(csgb.fns, fns...)
	return csgb
}

// Scan applies the selector query and scans the result into the given value.
func (csgb *CartSessionGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, csgb.build.ctx, "GroupBy")
	if err := csgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*CartSessionQuery, *CartSessionGroupBy](ctx, csgb.build, csgb, csgb.build.inters, v)
}

func (csgb *CartSessionGroupBy) sqlScan(ctx context.Context, root *CartSessionQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(csgb.fns))
	for _, fn := range csgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*csgb.flds)+len(csgb.fns))
		for _, f := range *csgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*csgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := csgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// CartSessionSelect is the builder for selecting fields of CartSession entities.
type CartSessionSelect struct {
	*CartSessionQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (css *CartSessionSelect) Aggregate(fns ...AggregateFunc) *CartSessionSelect {
	css.fns = append(css.fns, fns...)
	return css
}

// Scan applies the selector query and scans the result into the given value.
func (css *CartSessionSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, css.ctx, "Select")
	if err := css.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*CartSessionQuery, *CartSessionSelect](ctx, css.CartSessionQuery, css, css.inters, v)
}

func (css *CartSessionSelect) sqlScan(ctx context.Context, root *CartSessionQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(css.fns))
	for _, fn := range css.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*css.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := css.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
