// Code generated by ent, DO NOT EDIT.

package ent

import (
	"altron/core/repositories/ent/cartsession"
	"altron/core/repositories/ent/session"
	"altron/core/repositories/ent/workspace"
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
)

// CartSession is the model entity for the CartSession schema.
type CartSession struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// WorkspaceID holds the value of the "workspace_id" field.
	WorkspaceID uuid.UUID `json:"workspace_id,omitempty"`
	// SessionID holds the value of the "session_id" field.
	SessionID uuid.UUID `json:"session_id,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the CartSessionQuery when eager-loading is set.
	Edges        CartSessionEdges `json:"edges"`
	selectValues sql.SelectValues
}

// CartSessionEdges holds the relations/edges for other nodes in the graph.
type CartSessionEdges struct {
	// Session holds the value of the session edge.
	Session *Session `json:"session,omitempty"`
	// Workspace holds the value of the workspace edge.
	Workspace *Workspace `json:"workspace,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// SessionOrErr returns the Session value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e CartSessionEdges) SessionOrErr() (*Session, error) {
	if e.loadedTypes[0] {
		if e.Session == nil {
			// Edge was loaded but was not found.
			return nil, &NotFoundError{label: session.Label}
		}
		return e.Session, nil
	}
	return nil, &NotLoadedError{edge: "session"}
}

// WorkspaceOrErr returns the Workspace value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e CartSessionEdges) WorkspaceOrErr() (*Workspace, error) {
	if e.loadedTypes[1] {
		if e.Workspace == nil {
			// Edge was loaded but was not found.
			return nil, &NotFoundError{label: workspace.Label}
		}
		return e.Workspace, nil
	}
	return nil, &NotLoadedError{edge: "workspace"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*CartSession) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case cartsession.FieldID, cartsession.FieldWorkspaceID, cartsession.FieldSessionID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the CartSession fields.
func (cs *CartSession) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case cartsession.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				cs.ID = *value
			}
		case cartsession.FieldWorkspaceID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field workspace_id", values[i])
			} else if value != nil {
				cs.WorkspaceID = *value
			}
		case cartsession.FieldSessionID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field session_id", values[i])
			} else if value != nil {
				cs.SessionID = *value
			}
		default:
			cs.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the CartSession.
// This includes values selected through modifiers, order, etc.
func (cs *CartSession) Value(name string) (ent.Value, error) {
	return cs.selectValues.Get(name)
}

// QuerySession queries the "session" edge of the CartSession entity.
func (cs *CartSession) QuerySession() *SessionQuery {
	return NewCartSessionClient(cs.config).QuerySession(cs)
}

// QueryWorkspace queries the "workspace" edge of the CartSession entity.
func (cs *CartSession) QueryWorkspace() *WorkspaceQuery {
	return NewCartSessionClient(cs.config).QueryWorkspace(cs)
}

// Update returns a builder for updating this CartSession.
// Note that you need to call CartSession.Unwrap() before calling this method if this CartSession
// was returned from a transaction, and the transaction was committed or rolled back.
func (cs *CartSession) Update() *CartSessionUpdateOne {
	return NewCartSessionClient(cs.config).UpdateOne(cs)
}

// Unwrap unwraps the CartSession entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (cs *CartSession) Unwrap() *CartSession {
	_tx, ok := cs.config.driver.(*txDriver)
	if !ok {
		panic("ent: CartSession is not a transactional entity")
	}
	cs.config.driver = _tx.drv
	return cs
}

// String implements the fmt.Stringer.
func (cs *CartSession) String() string {
	var builder strings.Builder
	builder.WriteString("CartSession(")
	builder.WriteString(fmt.Sprintf("id=%v, ", cs.ID))
	builder.WriteString("workspace_id=")
	builder.WriteString(fmt.Sprintf("%v", cs.WorkspaceID))
	builder.WriteString(", ")
	builder.WriteString("session_id=")
	builder.WriteString(fmt.Sprintf("%v", cs.SessionID))
	builder.WriteByte(')')
	return builder.String()
}

// CartSessions is a parsable slice of CartSession.
type CartSessions []*CartSession
