// Code generated by ent, DO NOT EDIT.

package ent

import (
	"altron/core/repositories/ent/filter"
	"altron/core/repositories/ent/service"
	"altron/core/repositories/ent/sessionfilter"
	"altron/core/repositories/ent/user"
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// FilterCreate is the builder for creating a Filter entity.
type FilterCreate struct {
	config
	mutation *FilterMutation
	hooks    []Hook
}

// SetUserID sets the "user_id" field.
func (fc *FilterCreate) SetUserID(u uuid.UUID) *FilterCreate {
	fc.mutation.SetUserID(u)
	return fc
}

// SetServiceID sets the "service_id" field.
func (fc *FilterCreate) SetServiceID(u uuid.UUID) *FilterCreate {
	fc.mutation.SetServiceID(u)
	return fc
}

// SetNillableServiceID sets the "service_id" field if the given value is not nil.
func (fc *FilterCreate) SetNillableServiceID(u *uuid.UUID) *FilterCreate {
	if u != nil {
		fc.SetServiceID(*u)
	}
	return fc
}

// SetName sets the "name" field.
func (fc *FilterCreate) SetName(s string) *FilterCreate {
	fc.mutation.SetName(s)
	return fc
}

// SetRegex sets the "regex" field.
func (fc *FilterCreate) SetRegex(s string) *FilterCreate {
	fc.mutation.SetRegex(s)
	return fc
}

// SetNillableRegex sets the "regex" field if the given value is not nil.
func (fc *FilterCreate) SetNillableRegex(s *string) *FilterCreate {
	if s != nil {
		fc.SetRegex(*s)
	}
	return fc
}

// SetTTL sets the "ttl" field.
func (fc *FilterCreate) SetTTL(u uint8) *FilterCreate {
	fc.mutation.SetTTL(u)
	return fc
}

// SetNillableTTL sets the "ttl" field if the given value is not nil.
func (fc *FilterCreate) SetNillableTTL(u *uint8) *FilterCreate {
	if u != nil {
		fc.SetTTL(*u)
	}
	return fc
}

// SetTotalPackets sets the "total_packets" field.
func (fc *FilterCreate) SetTotalPackets(i int) *FilterCreate {
	fc.mutation.SetTotalPackets(i)
	return fc
}

// SetNillableTotalPackets sets the "total_packets" field if the given value is not nil.
func (fc *FilterCreate) SetNillableTotalPackets(i *int) *FilterCreate {
	if i != nil {
		fc.SetTotalPackets(*i)
	}
	return fc
}

// SetIsBlocking sets the "is_blocking" field.
func (fc *FilterCreate) SetIsBlocking(b bool) *FilterCreate {
	fc.mutation.SetIsBlocking(b)
	return fc
}

// SetInRequest sets the "in_request" field.
func (fc *FilterCreate) SetInRequest(b bool) *FilterCreate {
	fc.mutation.SetInRequest(b)
	return fc
}

// SetInResponse sets the "in_response" field.
func (fc *FilterCreate) SetInResponse(b bool) *FilterCreate {
	fc.mutation.SetInResponse(b)
	return fc
}

// SetColor sets the "color" field.
func (fc *FilterCreate) SetColor(s string) *FilterCreate {
	fc.mutation.SetColor(s)
	return fc
}

// SetID sets the "id" field.
func (fc *FilterCreate) SetID(u uuid.UUID) *FilterCreate {
	fc.mutation.SetID(u)
	return fc
}

// SetNillableID sets the "id" field if the given value is not nil.
func (fc *FilterCreate) SetNillableID(u *uuid.UUID) *FilterCreate {
	if u != nil {
		fc.SetID(*u)
	}
	return fc
}

// SetUser sets the "user" edge to the User entity.
func (fc *FilterCreate) SetUser(u *User) *FilterCreate {
	return fc.SetUserID(u.ID)
}

// SetService sets the "service" edge to the Service entity.
func (fc *FilterCreate) SetService(s *Service) *FilterCreate {
	return fc.SetServiceID(s.ID)
}

// AddSessionFilterIDs adds the "session_filter" edge to the SessionFilter entity by IDs.
func (fc *FilterCreate) AddSessionFilterIDs(ids ...uuid.UUID) *FilterCreate {
	fc.mutation.AddSessionFilterIDs(ids...)
	return fc
}

// AddSessionFilter adds the "session_filter" edges to the SessionFilter entity.
func (fc *FilterCreate) AddSessionFilter(s ...*SessionFilter) *FilterCreate {
	ids := make([]uuid.UUID, len(s))
	for i := range s {
		ids[i] = s[i].ID
	}
	return fc.AddSessionFilterIDs(ids...)
}

// Mutation returns the FilterMutation object of the builder.
func (fc *FilterCreate) Mutation() *FilterMutation {
	return fc.mutation
}

// Save creates the Filter in the database.
func (fc *FilterCreate) Save(ctx context.Context) (*Filter, error) {
	fc.defaults()
	return withHooks(ctx, fc.sqlSave, fc.mutation, fc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (fc *FilterCreate) SaveX(ctx context.Context) *Filter {
	v, err := fc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (fc *FilterCreate) Exec(ctx context.Context) error {
	_, err := fc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (fc *FilterCreate) ExecX(ctx context.Context) {
	if err := fc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (fc *FilterCreate) defaults() {
	if _, ok := fc.mutation.ID(); !ok {
		v := filter.DefaultID()
		fc.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (fc *FilterCreate) check() error {
	if _, ok := fc.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "Filter.user_id"`)}
	}
	if _, ok := fc.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "Filter.name"`)}
	}
	if _, ok := fc.mutation.IsBlocking(); !ok {
		return &ValidationError{Name: "is_blocking", err: errors.New(`ent: missing required field "Filter.is_blocking"`)}
	}
	if _, ok := fc.mutation.InRequest(); !ok {
		return &ValidationError{Name: "in_request", err: errors.New(`ent: missing required field "Filter.in_request"`)}
	}
	if _, ok := fc.mutation.InResponse(); !ok {
		return &ValidationError{Name: "in_response", err: errors.New(`ent: missing required field "Filter.in_response"`)}
	}
	if _, ok := fc.mutation.Color(); !ok {
		return &ValidationError{Name: "color", err: errors.New(`ent: missing required field "Filter.color"`)}
	}
	if _, ok := fc.mutation.UserID(); !ok {
		return &ValidationError{Name: "user", err: errors.New(`ent: missing required edge "Filter.user"`)}
	}
	return nil
}

func (fc *FilterCreate) sqlSave(ctx context.Context) (*Filter, error) {
	if err := fc.check(); err != nil {
		return nil, err
	}
	_node, _spec := fc.createSpec()
	if err := sqlgraph.CreateNode(ctx, fc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	fc.mutation.id = &_node.ID
	fc.mutation.done = true
	return _node, nil
}

func (fc *FilterCreate) createSpec() (*Filter, *sqlgraph.CreateSpec) {
	var (
		_node = &Filter{config: fc.config}
		_spec = sqlgraph.NewCreateSpec(filter.Table, sqlgraph.NewFieldSpec(filter.FieldID, field.TypeUUID))
	)
	if id, ok := fc.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := fc.mutation.Name(); ok {
		_spec.SetField(filter.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := fc.mutation.Regex(); ok {
		_spec.SetField(filter.FieldRegex, field.TypeString, value)
		_node.Regex = value
	}
	if value, ok := fc.mutation.TTL(); ok {
		_spec.SetField(filter.FieldTTL, field.TypeUint8, value)
		_node.TTL = value
	}
	if value, ok := fc.mutation.TotalPackets(); ok {
		_spec.SetField(filter.FieldTotalPackets, field.TypeInt, value)
		_node.TotalPackets = value
	}
	if value, ok := fc.mutation.IsBlocking(); ok {
		_spec.SetField(filter.FieldIsBlocking, field.TypeBool, value)
		_node.IsBlocking = value
	}
	if value, ok := fc.mutation.InRequest(); ok {
		_spec.SetField(filter.FieldInRequest, field.TypeBool, value)
		_node.InRequest = value
	}
	if value, ok := fc.mutation.InResponse(); ok {
		_spec.SetField(filter.FieldInResponse, field.TypeBool, value)
		_node.InResponse = value
	}
	if value, ok := fc.mutation.Color(); ok {
		_spec.SetField(filter.FieldColor, field.TypeString, value)
		_node.Color = value
	}
	if nodes := fc.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   filter.UserTable,
			Columns: []string{filter.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.UserID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := fc.mutation.ServiceIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   filter.ServiceTable,
			Columns: []string{filter.ServiceColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(service.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.ServiceID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := fc.mutation.SessionFilterIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   filter.SessionFilterTable,
			Columns: []string{filter.SessionFilterColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(sessionfilter.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// FilterCreateBulk is the builder for creating many Filter entities in bulk.
type FilterCreateBulk struct {
	config
	err      error
	builders []*FilterCreate
}

// Save creates the Filter entities in the database.
func (fcb *FilterCreateBulk) Save(ctx context.Context) ([]*Filter, error) {
	if fcb.err != nil {
		return nil, fcb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(fcb.builders))
	nodes := make([]*Filter, len(fcb.builders))
	mutators := make([]Mutator, len(fcb.builders))
	for i := range fcb.builders {
		func(i int, root context.Context) {
			builder := fcb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*FilterMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, fcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, fcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, fcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (fcb *FilterCreateBulk) SaveX(ctx context.Context) []*Filter {
	v, err := fcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (fcb *FilterCreateBulk) Exec(ctx context.Context) error {
	_, err := fcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (fcb *FilterCreateBulk) ExecX(ctx context.Context) {
	if err := fcb.Exec(ctx); err != nil {
		panic(err)
	}
}
