// Code generated by ent, DO NOT EDIT.

package ent

import (
	"altron/core/repositories/ent/matchedpacket"
	"altron/core/repositories/ent/predicate"
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// MatchedPacketDelete is the builder for deleting a MatchedPacket entity.
type MatchedPacketDelete struct {
	config
	hooks    []Hook
	mutation *MatchedPacketMutation
}

// Where appends a list predicates to the MatchedPacketDelete builder.
func (mpd *MatchedPacketDelete) Where(ps ...predicate.MatchedPacket) *MatchedPacketDelete {
	mpd.mutation.Where(ps...)
	return mpd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (mpd *MatchedPacketDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, mpd.sqlExec, mpd.mutation, mpd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (mpd *MatchedPacketDelete) ExecX(ctx context.Context) int {
	n, err := mpd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (mpd *MatchedPacketDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(matchedpacket.Table, sqlgraph.NewFieldSpec(matchedpacket.FieldID, field.TypeUUID))
	if ps := mpd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, mpd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	mpd.mutation.done = true
	return affected, err
}

// MatchedPacketDeleteOne is the builder for deleting a single MatchedPacket entity.
type MatchedPacketDeleteOne struct {
	mpd *MatchedPacketDelete
}

// Where appends a list predicates to the MatchedPacketDelete builder.
func (mpdo *MatchedPacketDeleteOne) Where(ps ...predicate.MatchedPacket) *MatchedPacketDeleteOne {
	mpdo.mpd.mutation.Where(ps...)
	return mpdo
}

// Exec executes the deletion query.
func (mpdo *MatchedPacketDeleteOne) Exec(ctx context.Context) error {
	n, err := mpdo.mpd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{matchedpacket.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (mpdo *MatchedPacketDeleteOne) ExecX(ctx context.Context) {
	if err := mpdo.Exec(ctx); err != nil {
		panic(err)
	}
}
