// Code generated by ent, DO NOT EDIT.

package ent

import (
	"altron/core/repositories/ent/matchedpacket"
	"altron/core/repositories/ent/sessionfilter"
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
)

// MatchedPacket is the model entity for the MatchedPacket schema.
type MatchedPacket struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// SessionFilterID holds the value of the "session_filter_id" field.
	SessionFilterID uuid.UUID `json:"session_filter_id,omitempty"`
	// PacketIdx holds the value of the "packet_idx" field.
	PacketIdx int `json:"packet_idx,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the MatchedPacketQuery when eager-loading is set.
	Edges        MatchedPacketEdges `json:"edges"`
	selectValues sql.SelectValues
}

// MatchedPacketEdges holds the relations/edges for other nodes in the graph.
type MatchedPacketEdges struct {
	// SessionFilter holds the value of the session_filter edge.
	SessionFilter *SessionFilter `json:"session_filter,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// SessionFilterOrErr returns the SessionFilter value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e MatchedPacketEdges) SessionFilterOrErr() (*SessionFilter, error) {
	if e.loadedTypes[0] {
		if e.SessionFilter == nil {
			// Edge was loaded but was not found.
			return nil, &NotFoundError{label: sessionfilter.Label}
		}
		return e.SessionFilter, nil
	}
	return nil, &NotLoadedError{edge: "session_filter"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*MatchedPacket) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case matchedpacket.FieldPacketIdx:
			values[i] = new(sql.NullInt64)
		case matchedpacket.FieldID, matchedpacket.FieldSessionFilterID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the MatchedPacket fields.
func (mp *MatchedPacket) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case matchedpacket.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				mp.ID = *value
			}
		case matchedpacket.FieldSessionFilterID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field session_filter_id", values[i])
			} else if value != nil {
				mp.SessionFilterID = *value
			}
		case matchedpacket.FieldPacketIdx:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field packet_idx", values[i])
			} else if value.Valid {
				mp.PacketIdx = int(value.Int64)
			}
		default:
			mp.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the MatchedPacket.
// This includes values selected through modifiers, order, etc.
func (mp *MatchedPacket) Value(name string) (ent.Value, error) {
	return mp.selectValues.Get(name)
}

// QuerySessionFilter queries the "session_filter" edge of the MatchedPacket entity.
func (mp *MatchedPacket) QuerySessionFilter() *SessionFilterQuery {
	return NewMatchedPacketClient(mp.config).QuerySessionFilter(mp)
}

// Update returns a builder for updating this MatchedPacket.
// Note that you need to call MatchedPacket.Unwrap() before calling this method if this MatchedPacket
// was returned from a transaction, and the transaction was committed or rolled back.
func (mp *MatchedPacket) Update() *MatchedPacketUpdateOne {
	return NewMatchedPacketClient(mp.config).UpdateOne(mp)
}

// Unwrap unwraps the MatchedPacket entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (mp *MatchedPacket) Unwrap() *MatchedPacket {
	_tx, ok := mp.config.driver.(*txDriver)
	if !ok {
		panic("ent: MatchedPacket is not a transactional entity")
	}
	mp.config.driver = _tx.drv
	return mp
}

// String implements the fmt.Stringer.
func (mp *MatchedPacket) String() string {
	var builder strings.Builder
	builder.WriteString("MatchedPacket(")
	builder.WriteString(fmt.Sprintf("id=%v, ", mp.ID))
	builder.WriteString("session_filter_id=")
	builder.WriteString(fmt.Sprintf("%v", mp.SessionFilterID))
	builder.WriteString(", ")
	builder.WriteString("packet_idx=")
	builder.WriteString(fmt.Sprintf("%v", mp.PacketIdx))
	builder.WriteByte(')')
	return builder.String()
}

// MatchedPackets is a parsable slice of MatchedPacket.
type MatchedPackets []*MatchedPacket
