// Code generated by ent, DO NOT EDIT.

package ent

import (
	"altron/core/repositories/ent/packet"
	"altron/core/repositories/ent/session"
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// PacketCreate is the builder for creating a Packet entity.
type PacketCreate struct {
	config
	mutation *PacketMutation
	hooks    []Hook
}

// SetSessionID sets the "session_id" field.
func (pc *PacketCreate) SetSessionID(u uuid.UUID) *PacketCreate {
	pc.mutation.SetSessionID(u)
	return pc
}

// SetSentAt sets the "sent_at" field.
func (pc *PacketCreate) SetSentAt(t time.Time) *PacketCreate {
	pc.mutation.SetSentAt(t)
	return pc
}

// SetIsRequest sets the "is_request" field.
func (pc *PacketCreate) SetIsRequest(b bool) *PacketCreate {
	pc.mutation.SetIsRequest(b)
	return pc
}

// SetPayload sets the "payload" field.
func (pc *PacketCreate) SetPayload(s string) *PacketCreate {
	pc.mutation.SetPayload(s)
	return pc
}

// SetID sets the "id" field.
func (pc *PacketCreate) SetID(u uuid.UUID) *PacketCreate {
	pc.mutation.SetID(u)
	return pc
}

// SetNillableID sets the "id" field if the given value is not nil.
func (pc *PacketCreate) SetNillableID(u *uuid.UUID) *PacketCreate {
	if u != nil {
		pc.SetID(*u)
	}
	return pc
}

// SetSession sets the "session" edge to the Session entity.
func (pc *PacketCreate) SetSession(s *Session) *PacketCreate {
	return pc.SetSessionID(s.ID)
}

// Mutation returns the PacketMutation object of the builder.
func (pc *PacketCreate) Mutation() *PacketMutation {
	return pc.mutation
}

// Save creates the Packet in the database.
func (pc *PacketCreate) Save(ctx context.Context) (*Packet, error) {
	pc.defaults()
	return withHooks(ctx, pc.sqlSave, pc.mutation, pc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (pc *PacketCreate) SaveX(ctx context.Context) *Packet {
	v, err := pc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (pc *PacketCreate) Exec(ctx context.Context) error {
	_, err := pc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (pc *PacketCreate) ExecX(ctx context.Context) {
	if err := pc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (pc *PacketCreate) defaults() {
	if _, ok := pc.mutation.ID(); !ok {
		v := packet.DefaultID()
		pc.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (pc *PacketCreate) check() error {
	if _, ok := pc.mutation.SessionID(); !ok {
		return &ValidationError{Name: "session_id", err: errors.New(`ent: missing required field "Packet.session_id"`)}
	}
	if _, ok := pc.mutation.SentAt(); !ok {
		return &ValidationError{Name: "sent_at", err: errors.New(`ent: missing required field "Packet.sent_at"`)}
	}
	if _, ok := pc.mutation.IsRequest(); !ok {
		return &ValidationError{Name: "is_request", err: errors.New(`ent: missing required field "Packet.is_request"`)}
	}
	if _, ok := pc.mutation.Payload(); !ok {
		return &ValidationError{Name: "payload", err: errors.New(`ent: missing required field "Packet.payload"`)}
	}
	if _, ok := pc.mutation.SessionID(); !ok {
		return &ValidationError{Name: "session", err: errors.New(`ent: missing required edge "Packet.session"`)}
	}
	return nil
}

func (pc *PacketCreate) sqlSave(ctx context.Context) (*Packet, error) {
	if err := pc.check(); err != nil {
		return nil, err
	}
	_node, _spec := pc.createSpec()
	if err := sqlgraph.CreateNode(ctx, pc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	pc.mutation.id = &_node.ID
	pc.mutation.done = true
	return _node, nil
}

func (pc *PacketCreate) createSpec() (*Packet, *sqlgraph.CreateSpec) {
	var (
		_node = &Packet{config: pc.config}
		_spec = sqlgraph.NewCreateSpec(packet.Table, sqlgraph.NewFieldSpec(packet.FieldID, field.TypeUUID))
	)
	if id, ok := pc.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := pc.mutation.SentAt(); ok {
		_spec.SetField(packet.FieldSentAt, field.TypeTime, value)
		_node.SentAt = value
	}
	if value, ok := pc.mutation.IsRequest(); ok {
		_spec.SetField(packet.FieldIsRequest, field.TypeBool, value)
		_node.IsRequest = value
	}
	if value, ok := pc.mutation.Payload(); ok {
		_spec.SetField(packet.FieldPayload, field.TypeString, value)
		_node.Payload = value
	}
	if nodes := pc.mutation.SessionIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   packet.SessionTable,
			Columns: []string{packet.SessionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(session.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.SessionID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// PacketCreateBulk is the builder for creating many Packet entities in bulk.
type PacketCreateBulk struct {
	config
	err      error
	builders []*PacketCreate
}

// Save creates the Packet entities in the database.
func (pcb *PacketCreateBulk) Save(ctx context.Context) ([]*Packet, error) {
	if pcb.err != nil {
		return nil, pcb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(pcb.builders))
	nodes := make([]*Packet, len(pcb.builders))
	mutators := make([]Mutator, len(pcb.builders))
	for i := range pcb.builders {
		func(i int, root context.Context) {
			builder := pcb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*PacketMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, pcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, pcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, pcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (pcb *PacketCreateBulk) SaveX(ctx context.Context) []*Packet {
	v, err := pcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (pcb *PacketCreateBulk) Exec(ctx context.Context) error {
	_, err := pcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (pcb *PacketCreateBulk) ExecX(ctx context.Context) {
	if err := pcb.Exec(ctx); err != nil {
		panic(err)
	}
}
