// Code generated by ent, DO NOT EDIT.

package ent

import (
	"altron/core/repositories/ent/pcapworkspace"
	"altron/core/repositories/ent/predicate"
	"altron/core/repositories/ent/session"
	"altron/core/repositories/ent/user"
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// PcapWorkspaceUpdate is the builder for updating PcapWorkspace entities.
type PcapWorkspaceUpdate struct {
	config
	hooks    []Hook
	mutation *PcapWorkspaceMutation
}

// Where appends a list predicates to the PcapWorkspaceUpdate builder.
func (pwu *PcapWorkspaceUpdate) Where(ps ...predicate.PcapWorkspace) *PcapWorkspaceUpdate {
	pwu.mutation.Where(ps...)
	return pwu
}

// SetUserID sets the "user_id" field.
func (pwu *PcapWorkspaceUpdate) SetUserID(u uuid.UUID) *PcapWorkspaceUpdate {
	pwu.mutation.SetUserID(u)
	return pwu
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (pwu *PcapWorkspaceUpdate) SetNillableUserID(u *uuid.UUID) *PcapWorkspaceUpdate {
	if u != nil {
		pwu.SetUserID(*u)
	}
	return pwu
}

// SetFileName sets the "file_name" field.
func (pwu *PcapWorkspaceUpdate) SetFileName(s string) *PcapWorkspaceUpdate {
	pwu.mutation.SetFileName(s)
	return pwu
}

// SetNillableFileName sets the "file_name" field if the given value is not nil.
func (pwu *PcapWorkspaceUpdate) SetNillableFileName(s *string) *PcapWorkspaceUpdate {
	if s != nil {
		pwu.SetFileName(*s)
	}
	return pwu
}

// SetStatus sets the "status" field.
func (pwu *PcapWorkspaceUpdate) SetStatus(pc pcapworkspace.Status) *PcapWorkspaceUpdate {
	pwu.mutation.SetStatus(pc)
	return pwu
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (pwu *PcapWorkspaceUpdate) SetNillableStatus(pc *pcapworkspace.Status) *PcapWorkspaceUpdate {
	if pc != nil {
		pwu.SetStatus(*pc)
	}
	return pwu
}

// SetUser sets the "user" edge to the User entity.
func (pwu *PcapWorkspaceUpdate) SetUser(u *User) *PcapWorkspaceUpdate {
	return pwu.SetUserID(u.ID)
}

// AddSessionIDs adds the "sessions" edge to the Session entity by IDs.
func (pwu *PcapWorkspaceUpdate) AddSessionIDs(ids ...uuid.UUID) *PcapWorkspaceUpdate {
	pwu.mutation.AddSessionIDs(ids...)
	return pwu
}

// AddSessions adds the "sessions" edges to the Session entity.
func (pwu *PcapWorkspaceUpdate) AddSessions(s ...*Session) *PcapWorkspaceUpdate {
	ids := make([]uuid.UUID, len(s))
	for i := range s {
		ids[i] = s[i].ID
	}
	return pwu.AddSessionIDs(ids...)
}

// Mutation returns the PcapWorkspaceMutation object of the builder.
func (pwu *PcapWorkspaceUpdate) Mutation() *PcapWorkspaceMutation {
	return pwu.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (pwu *PcapWorkspaceUpdate) ClearUser() *PcapWorkspaceUpdate {
	pwu.mutation.ClearUser()
	return pwu
}

// ClearSessions clears all "sessions" edges to the Session entity.
func (pwu *PcapWorkspaceUpdate) ClearSessions() *PcapWorkspaceUpdate {
	pwu.mutation.ClearSessions()
	return pwu
}

// RemoveSessionIDs removes the "sessions" edge to Session entities by IDs.
func (pwu *PcapWorkspaceUpdate) RemoveSessionIDs(ids ...uuid.UUID) *PcapWorkspaceUpdate {
	pwu.mutation.RemoveSessionIDs(ids...)
	return pwu
}

// RemoveSessions removes "sessions" edges to Session entities.
func (pwu *PcapWorkspaceUpdate) RemoveSessions(s ...*Session) *PcapWorkspaceUpdate {
	ids := make([]uuid.UUID, len(s))
	for i := range s {
		ids[i] = s[i].ID
	}
	return pwu.RemoveSessionIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (pwu *PcapWorkspaceUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, pwu.sqlSave, pwu.mutation, pwu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (pwu *PcapWorkspaceUpdate) SaveX(ctx context.Context) int {
	affected, err := pwu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (pwu *PcapWorkspaceUpdate) Exec(ctx context.Context) error {
	_, err := pwu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (pwu *PcapWorkspaceUpdate) ExecX(ctx context.Context) {
	if err := pwu.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (pwu *PcapWorkspaceUpdate) check() error {
	if v, ok := pwu.mutation.Status(); ok {
		if err := pcapworkspace.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "PcapWorkspace.status": %w`, err)}
		}
	}
	if _, ok := pwu.mutation.UserID(); pwu.mutation.UserCleared() && !ok {
		return errors.New(`ent: clearing a required unique edge "PcapWorkspace.user"`)
	}
	return nil
}

func (pwu *PcapWorkspaceUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := pwu.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(pcapworkspace.Table, pcapworkspace.Columns, sqlgraph.NewFieldSpec(pcapworkspace.FieldID, field.TypeUUID))
	if ps := pwu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := pwu.mutation.FileName(); ok {
		_spec.SetField(pcapworkspace.FieldFileName, field.TypeString, value)
	}
	if value, ok := pwu.mutation.Status(); ok {
		_spec.SetField(pcapworkspace.FieldStatus, field.TypeEnum, value)
	}
	if pwu.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   pcapworkspace.UserTable,
			Columns: []string{pcapworkspace.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := pwu.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   pcapworkspace.UserTable,
			Columns: []string{pcapworkspace.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if pwu.mutation.SessionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   pcapworkspace.SessionsTable,
			Columns: pcapworkspace.SessionsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(session.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := pwu.mutation.RemovedSessionsIDs(); len(nodes) > 0 && !pwu.mutation.SessionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   pcapworkspace.SessionsTable,
			Columns: pcapworkspace.SessionsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(session.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := pwu.mutation.SessionsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   pcapworkspace.SessionsTable,
			Columns: pcapworkspace.SessionsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(session.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, pwu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{pcapworkspace.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	pwu.mutation.done = true
	return n, nil
}

// PcapWorkspaceUpdateOne is the builder for updating a single PcapWorkspace entity.
type PcapWorkspaceUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *PcapWorkspaceMutation
}

// SetUserID sets the "user_id" field.
func (pwuo *PcapWorkspaceUpdateOne) SetUserID(u uuid.UUID) *PcapWorkspaceUpdateOne {
	pwuo.mutation.SetUserID(u)
	return pwuo
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (pwuo *PcapWorkspaceUpdateOne) SetNillableUserID(u *uuid.UUID) *PcapWorkspaceUpdateOne {
	if u != nil {
		pwuo.SetUserID(*u)
	}
	return pwuo
}

// SetFileName sets the "file_name" field.
func (pwuo *PcapWorkspaceUpdateOne) SetFileName(s string) *PcapWorkspaceUpdateOne {
	pwuo.mutation.SetFileName(s)
	return pwuo
}

// SetNillableFileName sets the "file_name" field if the given value is not nil.
func (pwuo *PcapWorkspaceUpdateOne) SetNillableFileName(s *string) *PcapWorkspaceUpdateOne {
	if s != nil {
		pwuo.SetFileName(*s)
	}
	return pwuo
}

// SetStatus sets the "status" field.
func (pwuo *PcapWorkspaceUpdateOne) SetStatus(pc pcapworkspace.Status) *PcapWorkspaceUpdateOne {
	pwuo.mutation.SetStatus(pc)
	return pwuo
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (pwuo *PcapWorkspaceUpdateOne) SetNillableStatus(pc *pcapworkspace.Status) *PcapWorkspaceUpdateOne {
	if pc != nil {
		pwuo.SetStatus(*pc)
	}
	return pwuo
}

// SetUser sets the "user" edge to the User entity.
func (pwuo *PcapWorkspaceUpdateOne) SetUser(u *User) *PcapWorkspaceUpdateOne {
	return pwuo.SetUserID(u.ID)
}

// AddSessionIDs adds the "sessions" edge to the Session entity by IDs.
func (pwuo *PcapWorkspaceUpdateOne) AddSessionIDs(ids ...uuid.UUID) *PcapWorkspaceUpdateOne {
	pwuo.mutation.AddSessionIDs(ids...)
	return pwuo
}

// AddSessions adds the "sessions" edges to the Session entity.
func (pwuo *PcapWorkspaceUpdateOne) AddSessions(s ...*Session) *PcapWorkspaceUpdateOne {
	ids := make([]uuid.UUID, len(s))
	for i := range s {
		ids[i] = s[i].ID
	}
	return pwuo.AddSessionIDs(ids...)
}

// Mutation returns the PcapWorkspaceMutation object of the builder.
func (pwuo *PcapWorkspaceUpdateOne) Mutation() *PcapWorkspaceMutation {
	return pwuo.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (pwuo *PcapWorkspaceUpdateOne) ClearUser() *PcapWorkspaceUpdateOne {
	pwuo.mutation.ClearUser()
	return pwuo
}

// ClearSessions clears all "sessions" edges to the Session entity.
func (pwuo *PcapWorkspaceUpdateOne) ClearSessions() *PcapWorkspaceUpdateOne {
	pwuo.mutation.ClearSessions()
	return pwuo
}

// RemoveSessionIDs removes the "sessions" edge to Session entities by IDs.
func (pwuo *PcapWorkspaceUpdateOne) RemoveSessionIDs(ids ...uuid.UUID) *PcapWorkspaceUpdateOne {
	pwuo.mutation.RemoveSessionIDs(ids...)
	return pwuo
}

// RemoveSessions removes "sessions" edges to Session entities.
func (pwuo *PcapWorkspaceUpdateOne) RemoveSessions(s ...*Session) *PcapWorkspaceUpdateOne {
	ids := make([]uuid.UUID, len(s))
	for i := range s {
		ids[i] = s[i].ID
	}
	return pwuo.RemoveSessionIDs(ids...)
}

// Where appends a list predicates to the PcapWorkspaceUpdate builder.
func (pwuo *PcapWorkspaceUpdateOne) Where(ps ...predicate.PcapWorkspace) *PcapWorkspaceUpdateOne {
	pwuo.mutation.Where(ps...)
	return pwuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (pwuo *PcapWorkspaceUpdateOne) Select(field string, fields ...string) *PcapWorkspaceUpdateOne {
	pwuo.fields = append([]string{field}, fields...)
	return pwuo
}

// Save executes the query and returns the updated PcapWorkspace entity.
func (pwuo *PcapWorkspaceUpdateOne) Save(ctx context.Context) (*PcapWorkspace, error) {
	return withHooks(ctx, pwuo.sqlSave, pwuo.mutation, pwuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (pwuo *PcapWorkspaceUpdateOne) SaveX(ctx context.Context) *PcapWorkspace {
	node, err := pwuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (pwuo *PcapWorkspaceUpdateOne) Exec(ctx context.Context) error {
	_, err := pwuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (pwuo *PcapWorkspaceUpdateOne) ExecX(ctx context.Context) {
	if err := pwuo.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (pwuo *PcapWorkspaceUpdateOne) check() error {
	if v, ok := pwuo.mutation.Status(); ok {
		if err := pcapworkspace.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "PcapWorkspace.status": %w`, err)}
		}
	}
	if _, ok := pwuo.mutation.UserID(); pwuo.mutation.UserCleared() && !ok {
		return errors.New(`ent: clearing a required unique edge "PcapWorkspace.user"`)
	}
	return nil
}

func (pwuo *PcapWorkspaceUpdateOne) sqlSave(ctx context.Context) (_node *PcapWorkspace, err error) {
	if err := pwuo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(pcapworkspace.Table, pcapworkspace.Columns, sqlgraph.NewFieldSpec(pcapworkspace.FieldID, field.TypeUUID))
	id, ok := pwuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "PcapWorkspace.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := pwuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, pcapworkspace.FieldID)
		for _, f := range fields {
			if !pcapworkspace.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != pcapworkspace.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := pwuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := pwuo.mutation.FileName(); ok {
		_spec.SetField(pcapworkspace.FieldFileName, field.TypeString, value)
	}
	if value, ok := pwuo.mutation.Status(); ok {
		_spec.SetField(pcapworkspace.FieldStatus, field.TypeEnum, value)
	}
	if pwuo.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   pcapworkspace.UserTable,
			Columns: []string{pcapworkspace.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := pwuo.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   pcapworkspace.UserTable,
			Columns: []string{pcapworkspace.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if pwuo.mutation.SessionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   pcapworkspace.SessionsTable,
			Columns: pcapworkspace.SessionsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(session.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := pwuo.mutation.RemovedSessionsIDs(); len(nodes) > 0 && !pwuo.mutation.SessionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   pcapworkspace.SessionsTable,
			Columns: pcapworkspace.SessionsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(session.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := pwuo.mutation.SessionsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   pcapworkspace.SessionsTable,
			Columns: pcapworkspace.SessionsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(session.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &PcapWorkspace{config: pwuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, pwuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{pcapworkspace.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	pwuo.mutation.done = true
	return _node, nil
}
