// Code generated by ent, DO NOT EDIT.

package ent

import (
	"altron/core/repositories/ent/pcapworkspace"
	"altron/core/repositories/ent/predicate"
	"altron/core/repositories/ent/session"
	"altron/core/repositories/ent/user"
	"context"
	"database/sql/driver"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// PcapWorkspaceQuery is the builder for querying PcapWorkspace entities.
type PcapWorkspaceQuery struct {
	config
	ctx          *QueryContext
	order        []pcapworkspace.OrderOption
	inters       []Interceptor
	predicates   []predicate.PcapWorkspace
	withUser     *UserQuery
	withSessions *SessionQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the PcapWorkspaceQuery builder.
func (pwq *PcapWorkspaceQuery) Where(ps ...predicate.PcapWorkspace) *PcapWorkspaceQuery {
	pwq.predicates = append(pwq.predicates, ps...)
	return pwq
}

// Limit the number of records to be returned by this query.
func (pwq *PcapWorkspaceQuery) Limit(limit int) *PcapWorkspaceQuery {
	pwq.ctx.Limit = &limit
	return pwq
}

// Offset to start from.
func (pwq *PcapWorkspaceQuery) Offset(offset int) *PcapWorkspaceQuery {
	pwq.ctx.Offset = &offset
	return pwq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (pwq *PcapWorkspaceQuery) Unique(unique bool) *PcapWorkspaceQuery {
	pwq.ctx.Unique = &unique
	return pwq
}

// Order specifies how the records should be ordered.
func (pwq *PcapWorkspaceQuery) Order(o ...pcapworkspace.OrderOption) *PcapWorkspaceQuery {
	pwq.order = append(pwq.order, o...)
	return pwq
}

// QueryUser chains the current query on the "user" edge.
func (pwq *PcapWorkspaceQuery) QueryUser() *UserQuery {
	query := (&UserClient{config: pwq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := pwq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := pwq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(pcapworkspace.Table, pcapworkspace.FieldID, selector),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, pcapworkspace.UserTable, pcapworkspace.UserColumn),
		)
		fromU = sqlgraph.SetNeighbors(pwq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QuerySessions chains the current query on the "sessions" edge.
func (pwq *PcapWorkspaceQuery) QuerySessions() *SessionQuery {
	query := (&SessionClient{config: pwq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := pwq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := pwq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(pcapworkspace.Table, pcapworkspace.FieldID, selector),
			sqlgraph.To(session.Table, session.FieldID),
			sqlgraph.Edge(sqlgraph.M2M, false, pcapworkspace.SessionsTable, pcapworkspace.SessionsPrimaryKey...),
		)
		fromU = sqlgraph.SetNeighbors(pwq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first PcapWorkspace entity from the query.
// Returns a *NotFoundError when no PcapWorkspace was found.
func (pwq *PcapWorkspaceQuery) First(ctx context.Context) (*PcapWorkspace, error) {
	nodes, err := pwq.Limit(1).All(setContextOp(ctx, pwq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{pcapworkspace.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (pwq *PcapWorkspaceQuery) FirstX(ctx context.Context) *PcapWorkspace {
	node, err := pwq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first PcapWorkspace ID from the query.
// Returns a *NotFoundError when no PcapWorkspace ID was found.
func (pwq *PcapWorkspaceQuery) FirstID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = pwq.Limit(1).IDs(setContextOp(ctx, pwq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{pcapworkspace.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (pwq *PcapWorkspaceQuery) FirstIDX(ctx context.Context) uuid.UUID {
	id, err := pwq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single PcapWorkspace entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one PcapWorkspace entity is found.
// Returns a *NotFoundError when no PcapWorkspace entities are found.
func (pwq *PcapWorkspaceQuery) Only(ctx context.Context) (*PcapWorkspace, error) {
	nodes, err := pwq.Limit(2).All(setContextOp(ctx, pwq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{pcapworkspace.Label}
	default:
		return nil, &NotSingularError{pcapworkspace.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (pwq *PcapWorkspaceQuery) OnlyX(ctx context.Context) *PcapWorkspace {
	node, err := pwq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only PcapWorkspace ID in the query.
// Returns a *NotSingularError when more than one PcapWorkspace ID is found.
// Returns a *NotFoundError when no entities are found.
func (pwq *PcapWorkspaceQuery) OnlyID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = pwq.Limit(2).IDs(setContextOp(ctx, pwq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{pcapworkspace.Label}
	default:
		err = &NotSingularError{pcapworkspace.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (pwq *PcapWorkspaceQuery) OnlyIDX(ctx context.Context) uuid.UUID {
	id, err := pwq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of PcapWorkspaces.
func (pwq *PcapWorkspaceQuery) All(ctx context.Context) ([]*PcapWorkspace, error) {
	ctx = setContextOp(ctx, pwq.ctx, "All")
	if err := pwq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*PcapWorkspace, *PcapWorkspaceQuery]()
	return withInterceptors[[]*PcapWorkspace](ctx, pwq, qr, pwq.inters)
}

// AllX is like All, but panics if an error occurs.
func (pwq *PcapWorkspaceQuery) AllX(ctx context.Context) []*PcapWorkspace {
	nodes, err := pwq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of PcapWorkspace IDs.
func (pwq *PcapWorkspaceQuery) IDs(ctx context.Context) (ids []uuid.UUID, err error) {
	if pwq.ctx.Unique == nil && pwq.path != nil {
		pwq.Unique(true)
	}
	ctx = setContextOp(ctx, pwq.ctx, "IDs")
	if err = pwq.Select(pcapworkspace.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (pwq *PcapWorkspaceQuery) IDsX(ctx context.Context) []uuid.UUID {
	ids, err := pwq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (pwq *PcapWorkspaceQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, pwq.ctx, "Count")
	if err := pwq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, pwq, querierCount[*PcapWorkspaceQuery](), pwq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (pwq *PcapWorkspaceQuery) CountX(ctx context.Context) int {
	count, err := pwq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (pwq *PcapWorkspaceQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, pwq.ctx, "Exist")
	switch _, err := pwq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (pwq *PcapWorkspaceQuery) ExistX(ctx context.Context) bool {
	exist, err := pwq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the PcapWorkspaceQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (pwq *PcapWorkspaceQuery) Clone() *PcapWorkspaceQuery {
	if pwq == nil {
		return nil
	}
	return &PcapWorkspaceQuery{
		config:       pwq.config,
		ctx:          pwq.ctx.Clone(),
		order:        append([]pcapworkspace.OrderOption{}, pwq.order...),
		inters:       append([]Interceptor{}, pwq.inters...),
		predicates:   append([]predicate.PcapWorkspace{}, pwq.predicates...),
		withUser:     pwq.withUser.Clone(),
		withSessions: pwq.withSessions.Clone(),
		// clone intermediate query.
		sql:  pwq.sql.Clone(),
		path: pwq.path,
	}
}

// WithUser tells the query-builder to eager-load the nodes that are connected to
// the "user" edge. The optional arguments are used to configure the query builder of the edge.
func (pwq *PcapWorkspaceQuery) WithUser(opts ...func(*UserQuery)) *PcapWorkspaceQuery {
	query := (&UserClient{config: pwq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	pwq.withUser = query
	return pwq
}

// WithSessions tells the query-builder to eager-load the nodes that are connected to
// the "sessions" edge. The optional arguments are used to configure the query builder of the edge.
func (pwq *PcapWorkspaceQuery) WithSessions(opts ...func(*SessionQuery)) *PcapWorkspaceQuery {
	query := (&SessionClient{config: pwq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	pwq.withSessions = query
	return pwq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		UserID uuid.UUID `json:"user_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.PcapWorkspace.Query().
//		GroupBy(pcapworkspace.FieldUserID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (pwq *PcapWorkspaceQuery) GroupBy(field string, fields ...string) *PcapWorkspaceGroupBy {
	pwq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &PcapWorkspaceGroupBy{build: pwq}
	grbuild.flds = &pwq.ctx.Fields
	grbuild.label = pcapworkspace.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		UserID uuid.UUID `json:"user_id,omitempty"`
//	}
//
//	client.PcapWorkspace.Query().
//		Select(pcapworkspace.FieldUserID).
//		Scan(ctx, &v)
func (pwq *PcapWorkspaceQuery) Select(fields ...string) *PcapWorkspaceSelect {
	pwq.ctx.Fields = append(pwq.ctx.Fields, fields...)
	sbuild := &PcapWorkspaceSelect{PcapWorkspaceQuery: pwq}
	sbuild.label = pcapworkspace.Label
	sbuild.flds, sbuild.scan = &pwq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a PcapWorkspaceSelect configured with the given aggregations.
func (pwq *PcapWorkspaceQuery) Aggregate(fns ...AggregateFunc) *PcapWorkspaceSelect {
	return pwq.Select().Aggregate(fns...)
}

func (pwq *PcapWorkspaceQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range pwq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, pwq); err != nil {
				return err
			}
		}
	}
	for _, f := range pwq.ctx.Fields {
		if !pcapworkspace.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if pwq.path != nil {
		prev, err := pwq.path(ctx)
		if err != nil {
			return err
		}
		pwq.sql = prev
	}
	return nil
}

func (pwq *PcapWorkspaceQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*PcapWorkspace, error) {
	var (
		nodes       = []*PcapWorkspace{}
		_spec       = pwq.querySpec()
		loadedTypes = [2]bool{
			pwq.withUser != nil,
			pwq.withSessions != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*PcapWorkspace).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &PcapWorkspace{config: pwq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, pwq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := pwq.withUser; query != nil {
		if err := pwq.loadUser(ctx, query, nodes, nil,
			func(n *PcapWorkspace, e *User) { n.Edges.User = e }); err != nil {
			return nil, err
		}
	}
	if query := pwq.withSessions; query != nil {
		if err := pwq.loadSessions(ctx, query, nodes,
			func(n *PcapWorkspace) { n.Edges.Sessions = []*Session{} },
			func(n *PcapWorkspace, e *Session) { n.Edges.Sessions = append(n.Edges.Sessions, e) }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (pwq *PcapWorkspaceQuery) loadUser(ctx context.Context, query *UserQuery, nodes []*PcapWorkspace, init func(*PcapWorkspace), assign func(*PcapWorkspace, *User)) error {
	ids := make([]uuid.UUID, 0, len(nodes))
	nodeids := make(map[uuid.UUID][]*PcapWorkspace)
	for i := range nodes {
		fk := nodes[i].UserID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(user.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "user_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (pwq *PcapWorkspaceQuery) loadSessions(ctx context.Context, query *SessionQuery, nodes []*PcapWorkspace, init func(*PcapWorkspace), assign func(*PcapWorkspace, *Session)) error {
	edgeIDs := make([]driver.Value, len(nodes))
	byID := make(map[uuid.UUID]*PcapWorkspace)
	nids := make(map[uuid.UUID]map[*PcapWorkspace]struct{})
	for i, node := range nodes {
		edgeIDs[i] = node.ID
		byID[node.ID] = node
		if init != nil {
			init(node)
		}
	}
	query.Where(func(s *sql.Selector) {
		joinT := sql.Table(pcapworkspace.SessionsTable)
		s.Join(joinT).On(s.C(session.FieldID), joinT.C(pcapworkspace.SessionsPrimaryKey[1]))
		s.Where(sql.InValues(joinT.C(pcapworkspace.SessionsPrimaryKey[0]), edgeIDs...))
		columns := s.SelectedColumns()
		s.Select(joinT.C(pcapworkspace.SessionsPrimaryKey[0]))
		s.AppendSelect(columns...)
		s.SetDistinct(false)
	})
	if err := query.prepareQuery(ctx); err != nil {
		return err
	}
	qr := QuerierFunc(func(ctx context.Context, q Query) (Value, error) {
		return query.sqlAll(ctx, func(_ context.Context, spec *sqlgraph.QuerySpec) {
			assign := spec.Assign
			values := spec.ScanValues
			spec.ScanValues = func(columns []string) ([]any, error) {
				values, err := values(columns[1:])
				if err != nil {
					return nil, err
				}
				return append([]any{new(uuid.UUID)}, values...), nil
			}
			spec.Assign = func(columns []string, values []any) error {
				outValue := *values[0].(*uuid.UUID)
				inValue := *values[1].(*uuid.UUID)
				if nids[inValue] == nil {
					nids[inValue] = map[*PcapWorkspace]struct{}{byID[outValue]: {}}
					return assign(columns[1:], values[1:])
				}
				nids[inValue][byID[outValue]] = struct{}{}
				return nil
			}
		})
	})
	neighbors, err := withInterceptors[[]*Session](ctx, query, qr, query.inters)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected "sessions" node returned %v`, n.ID)
		}
		for kn := range nodes {
			assign(kn, n)
		}
	}
	return nil
}

func (pwq *PcapWorkspaceQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := pwq.querySpec()
	_spec.Node.Columns = pwq.ctx.Fields
	if len(pwq.ctx.Fields) > 0 {
		_spec.Unique = pwq.ctx.Unique != nil && *pwq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, pwq.driver, _spec)
}

func (pwq *PcapWorkspaceQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(pcapworkspace.Table, pcapworkspace.Columns, sqlgraph.NewFieldSpec(pcapworkspace.FieldID, field.TypeUUID))
	_spec.From = pwq.sql
	if unique := pwq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if pwq.path != nil {
		_spec.Unique = true
	}
	if fields := pwq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, pcapworkspace.FieldID)
		for i := range fields {
			if fields[i] != pcapworkspace.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if pwq.withUser != nil {
			_spec.Node.AddColumnOnce(pcapworkspace.FieldUserID)
		}
	}
	if ps := pwq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := pwq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := pwq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := pwq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (pwq *PcapWorkspaceQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(pwq.driver.Dialect())
	t1 := builder.Table(pcapworkspace.Table)
	columns := pwq.ctx.Fields
	if len(columns) == 0 {
		columns = pcapworkspace.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if pwq.sql != nil {
		selector = pwq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if pwq.ctx.Unique != nil && *pwq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range pwq.predicates {
		p(selector)
	}
	for _, p := range pwq.order {
		p(selector)
	}
	if offset := pwq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := pwq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// PcapWorkspaceGroupBy is the group-by builder for PcapWorkspace entities.
type PcapWorkspaceGroupBy struct {
	selector
	build *PcapWorkspaceQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (pwgb *PcapWorkspaceGroupBy) Aggregate(fns ...AggregateFunc) *PcapWorkspaceGroupBy {
	pwgb.fns = append(pwgb.fns, fns...)
	return pwgb
}

// Scan applies the selector query and scans the result into the given value.
func (pwgb *PcapWorkspaceGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, pwgb.build.ctx, "GroupBy")
	if err := pwgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*PcapWorkspaceQuery, *PcapWorkspaceGroupBy](ctx, pwgb.build, pwgb, pwgb.build.inters, v)
}

func (pwgb *PcapWorkspaceGroupBy) sqlScan(ctx context.Context, root *PcapWorkspaceQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(pwgb.fns))
	for _, fn := range pwgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*pwgb.flds)+len(pwgb.fns))
		for _, f := range *pwgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*pwgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := pwgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// PcapWorkspaceSelect is the builder for selecting fields of PcapWorkspace entities.
type PcapWorkspaceSelect struct {
	*PcapWorkspaceQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (pws *PcapWorkspaceSelect) Aggregate(fns ...AggregateFunc) *PcapWorkspaceSelect {
	pws.fns = append(pws.fns, fns...)
	return pws
}

// Scan applies the selector query and scans the result into the given value.
func (pws *PcapWorkspaceSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, pws.ctx, "Select")
	if err := pws.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*PcapWorkspaceQuery, *PcapWorkspaceSelect](ctx, pws.PcapWorkspaceQuery, pws, pws.inters, v)
}

func (pws *PcapWorkspaceSelect) sqlScan(ctx context.Context, root *PcapWorkspaceQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(pws.fns))
	for _, fn := range pws.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*pws.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := pws.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
