// Code generated by ent, DO NOT EDIT.

package ent

import (
	"altron/core/repositories/ent/pcapworkspace"
	"altron/core/repositories/ent/session"
	"altron/core/repositories/ent/user"
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// PcapWorkspaceCreate is the builder for creating a PcapWorkspace entity.
type PcapWorkspaceCreate struct {
	config
	mutation *PcapWorkspaceMutation
	hooks    []Hook
}

// SetUserID sets the "user_id" field.
func (pwc *PcapWorkspaceCreate) SetUserID(u uuid.UUID) *PcapWorkspaceCreate {
	pwc.mutation.SetUserID(u)
	return pwc
}

// SetFileName sets the "file_name" field.
func (pwc *PcapWorkspaceCreate) SetFileName(s string) *PcapWorkspaceCreate {
	pwc.mutation.SetFileName(s)
	return pwc
}

// SetStatus sets the "status" field.
func (pwc *PcapWorkspaceCreate) SetStatus(pc pcapworkspace.Status) *PcapWorkspaceCreate {
	pwc.mutation.SetStatus(pc)
	return pwc
}

// SetID sets the "id" field.
func (pwc *PcapWorkspaceCreate) SetID(u uuid.UUID) *PcapWorkspaceCreate {
	pwc.mutation.SetID(u)
	return pwc
}

// SetNillableID sets the "id" field if the given value is not nil.
func (pwc *PcapWorkspaceCreate) SetNillableID(u *uuid.UUID) *PcapWorkspaceCreate {
	if u != nil {
		pwc.SetID(*u)
	}
	return pwc
}

// SetUser sets the "user" edge to the User entity.
func (pwc *PcapWorkspaceCreate) SetUser(u *User) *PcapWorkspaceCreate {
	return pwc.SetUserID(u.ID)
}

// AddSessionIDs adds the "sessions" edge to the Session entity by IDs.
func (pwc *PcapWorkspaceCreate) AddSessionIDs(ids ...uuid.UUID) *PcapWorkspaceCreate {
	pwc.mutation.AddSessionIDs(ids...)
	return pwc
}

// AddSessions adds the "sessions" edges to the Session entity.
func (pwc *PcapWorkspaceCreate) AddSessions(s ...*Session) *PcapWorkspaceCreate {
	ids := make([]uuid.UUID, len(s))
	for i := range s {
		ids[i] = s[i].ID
	}
	return pwc.AddSessionIDs(ids...)
}

// Mutation returns the PcapWorkspaceMutation object of the builder.
func (pwc *PcapWorkspaceCreate) Mutation() *PcapWorkspaceMutation {
	return pwc.mutation
}

// Save creates the PcapWorkspace in the database.
func (pwc *PcapWorkspaceCreate) Save(ctx context.Context) (*PcapWorkspace, error) {
	pwc.defaults()
	return withHooks(ctx, pwc.sqlSave, pwc.mutation, pwc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (pwc *PcapWorkspaceCreate) SaveX(ctx context.Context) *PcapWorkspace {
	v, err := pwc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (pwc *PcapWorkspaceCreate) Exec(ctx context.Context) error {
	_, err := pwc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (pwc *PcapWorkspaceCreate) ExecX(ctx context.Context) {
	if err := pwc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (pwc *PcapWorkspaceCreate) defaults() {
	if _, ok := pwc.mutation.ID(); !ok {
		v := pcapworkspace.DefaultID()
		pwc.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (pwc *PcapWorkspaceCreate) check() error {
	if _, ok := pwc.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "PcapWorkspace.user_id"`)}
	}
	if _, ok := pwc.mutation.FileName(); !ok {
		return &ValidationError{Name: "file_name", err: errors.New(`ent: missing required field "PcapWorkspace.file_name"`)}
	}
	if _, ok := pwc.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "PcapWorkspace.status"`)}
	}
	if v, ok := pwc.mutation.Status(); ok {
		if err := pcapworkspace.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "PcapWorkspace.status": %w`, err)}
		}
	}
	if _, ok := pwc.mutation.UserID(); !ok {
		return &ValidationError{Name: "user", err: errors.New(`ent: missing required edge "PcapWorkspace.user"`)}
	}
	return nil
}

func (pwc *PcapWorkspaceCreate) sqlSave(ctx context.Context) (*PcapWorkspace, error) {
	if err := pwc.check(); err != nil {
		return nil, err
	}
	_node, _spec := pwc.createSpec()
	if err := sqlgraph.CreateNode(ctx, pwc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	pwc.mutation.id = &_node.ID
	pwc.mutation.done = true
	return _node, nil
}

func (pwc *PcapWorkspaceCreate) createSpec() (*PcapWorkspace, *sqlgraph.CreateSpec) {
	var (
		_node = &PcapWorkspace{config: pwc.config}
		_spec = sqlgraph.NewCreateSpec(pcapworkspace.Table, sqlgraph.NewFieldSpec(pcapworkspace.FieldID, field.TypeUUID))
	)
	if id, ok := pwc.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := pwc.mutation.FileName(); ok {
		_spec.SetField(pcapworkspace.FieldFileName, field.TypeString, value)
		_node.FileName = value
	}
	if value, ok := pwc.mutation.Status(); ok {
		_spec.SetField(pcapworkspace.FieldStatus, field.TypeEnum, value)
		_node.Status = value
	}
	if nodes := pwc.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   pcapworkspace.UserTable,
			Columns: []string{pcapworkspace.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.UserID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := pwc.mutation.SessionsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   pcapworkspace.SessionsTable,
			Columns: pcapworkspace.SessionsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(session.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// PcapWorkspaceCreateBulk is the builder for creating many PcapWorkspace entities in bulk.
type PcapWorkspaceCreateBulk struct {
	config
	err      error
	builders []*PcapWorkspaceCreate
}

// Save creates the PcapWorkspace entities in the database.
func (pwcb *PcapWorkspaceCreateBulk) Save(ctx context.Context) ([]*PcapWorkspace, error) {
	if pwcb.err != nil {
		return nil, pwcb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(pwcb.builders))
	nodes := make([]*PcapWorkspace, len(pwcb.builders))
	mutators := make([]Mutator, len(pwcb.builders))
	for i := range pwcb.builders {
		func(i int, root context.Context) {
			builder := pwcb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*PcapWorkspaceMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, pwcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, pwcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, pwcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (pwcb *PcapWorkspaceCreateBulk) SaveX(ctx context.Context) []*PcapWorkspace {
	v, err := pwcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (pwcb *PcapWorkspaceCreateBulk) Exec(ctx context.Context) error {
	_, err := pwcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (pwcb *PcapWorkspaceCreateBulk) ExecX(ctx context.Context) {
	if err := pwcb.Exec(ctx); err != nil {
		panic(err)
	}
}
