// Code generated by ent, DO NOT EDIT.

package ent

import (
	"altron/core/repositories/ent/pcapworkspace"
	"altron/core/repositories/ent/user"
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
)

// PcapWorkspace is the model entity for the PcapWorkspace schema.
type PcapWorkspace struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// UserID holds the value of the "user_id" field.
	UserID uuid.UUID `json:"user_id,omitempty"`
	// FileName holds the value of the "file_name" field.
	FileName string `json:"file_name,omitempty"`
	// Status holds the value of the "status" field.
	Status pcapworkspace.Status `json:"status,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the PcapWorkspaceQuery when eager-loading is set.
	Edges        PcapWorkspaceEdges `json:"edges"`
	selectValues sql.SelectValues
}

// PcapWorkspaceEdges holds the relations/edges for other nodes in the graph.
type PcapWorkspaceEdges struct {
	// User holds the value of the user edge.
	User *User `json:"user,omitempty"`
	// Sessions holds the value of the sessions edge.
	Sessions []*Session `json:"sessions,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// UserOrErr returns the User value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e PcapWorkspaceEdges) UserOrErr() (*User, error) {
	if e.loadedTypes[0] {
		if e.User == nil {
			// Edge was loaded but was not found.
			return nil, &NotFoundError{label: user.Label}
		}
		return e.User, nil
	}
	return nil, &NotLoadedError{edge: "user"}
}

// SessionsOrErr returns the Sessions value or an error if the edge
// was not loaded in eager-loading.
func (e PcapWorkspaceEdges) SessionsOrErr() ([]*Session, error) {
	if e.loadedTypes[1] {
		return e.Sessions, nil
	}
	return nil, &NotLoadedError{edge: "sessions"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*PcapWorkspace) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case pcapworkspace.FieldFileName, pcapworkspace.FieldStatus:
			values[i] = new(sql.NullString)
		case pcapworkspace.FieldID, pcapworkspace.FieldUserID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the PcapWorkspace fields.
func (pw *PcapWorkspace) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case pcapworkspace.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				pw.ID = *value
			}
		case pcapworkspace.FieldUserID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value != nil {
				pw.UserID = *value
			}
		case pcapworkspace.FieldFileName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field file_name", values[i])
			} else if value.Valid {
				pw.FileName = value.String
			}
		case pcapworkspace.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				pw.Status = pcapworkspace.Status(value.String)
			}
		default:
			pw.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the PcapWorkspace.
// This includes values selected through modifiers, order, etc.
func (pw *PcapWorkspace) Value(name string) (ent.Value, error) {
	return pw.selectValues.Get(name)
}

// QueryUser queries the "user" edge of the PcapWorkspace entity.
func (pw *PcapWorkspace) QueryUser() *UserQuery {
	return NewPcapWorkspaceClient(pw.config).QueryUser(pw)
}

// QuerySessions queries the "sessions" edge of the PcapWorkspace entity.
func (pw *PcapWorkspace) QuerySessions() *SessionQuery {
	return NewPcapWorkspaceClient(pw.config).QuerySessions(pw)
}

// Update returns a builder for updating this PcapWorkspace.
// Note that you need to call PcapWorkspace.Unwrap() before calling this method if this PcapWorkspace
// was returned from a transaction, and the transaction was committed or rolled back.
func (pw *PcapWorkspace) Update() *PcapWorkspaceUpdateOne {
	return NewPcapWorkspaceClient(pw.config).UpdateOne(pw)
}

// Unwrap unwraps the PcapWorkspace entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (pw *PcapWorkspace) Unwrap() *PcapWorkspace {
	_tx, ok := pw.config.driver.(*txDriver)
	if !ok {
		panic("ent: PcapWorkspace is not a transactional entity")
	}
	pw.config.driver = _tx.drv
	return pw
}

// String implements the fmt.Stringer.
func (pw *PcapWorkspace) String() string {
	var builder strings.Builder
	builder.WriteString("PcapWorkspace(")
	builder.WriteString(fmt.Sprintf("id=%v, ", pw.ID))
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", pw.UserID))
	builder.WriteString(", ")
	builder.WriteString("file_name=")
	builder.WriteString(pw.FileName)
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(fmt.Sprintf("%v", pw.Status))
	builder.WriteByte(')')
	return builder.String()
}

// PcapWorkspaces is a parsable slice of PcapWorkspace.
type PcapWorkspaces []*PcapWorkspace
