// Code generated by ent, DO NOT EDIT.

package ent

import (
	"altron/core/repositories/ent/filter"
	"altron/core/repositories/ent/plugin"
	"altron/core/repositories/ent/predicate"
	"altron/core/repositories/ent/service"
	"altron/core/repositories/ent/session"
	"altron/core/repositories/ent/user"
	"altron/core/repositories/ent/workspace"
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// ServiceUpdate is the builder for updating Service entities.
type ServiceUpdate struct {
	config
	hooks    []Hook
	mutation *ServiceMutation
}

// Where appends a list predicates to the ServiceUpdate builder.
func (su *ServiceUpdate) Where(ps ...predicate.Service) *ServiceUpdate {
	su.mutation.Where(ps...)
	return su
}

// SetUserID sets the "user_id" field.
func (su *ServiceUpdate) SetUserID(u uuid.UUID) *ServiceUpdate {
	su.mutation.SetUserID(u)
	return su
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (su *ServiceUpdate) SetNillableUserID(u *uuid.UUID) *ServiceUpdate {
	if u != nil {
		su.SetUserID(*u)
	}
	return su
}

// SetName sets the "name" field.
func (su *ServiceUpdate) SetName(s string) *ServiceUpdate {
	su.mutation.SetName(s)
	return su
}

// SetNillableName sets the "name" field if the given value is not nil.
func (su *ServiceUpdate) SetNillableName(s *string) *ServiceUpdate {
	if s != nil {
		su.SetName(*s)
	}
	return su
}

// SetLink sets the "link" field.
func (su *ServiceUpdate) SetLink(s string) *ServiceUpdate {
	su.mutation.SetLink(s)
	return su
}

// SetNillableLink sets the "link" field if the given value is not nil.
func (su *ServiceUpdate) SetNillableLink(s *string) *ServiceUpdate {
	if s != nil {
		su.SetLink(*s)
	}
	return su
}

// SetPort sets the "port" field.
func (su *ServiceUpdate) SetPort(u uint32) *ServiceUpdate {
	su.mutation.ResetPort()
	su.mutation.SetPort(u)
	return su
}

// SetNillablePort sets the "port" field if the given value is not nil.
func (su *ServiceUpdate) SetNillablePort(u *uint32) *ServiceUpdate {
	if u != nil {
		su.SetPort(*u)
	}
	return su
}

// AddPort adds u to the "port" field.
func (su *ServiceUpdate) AddPort(u int32) *ServiceUpdate {
	su.mutation.AddPort(u)
	return su
}

// SetContainerID sets the "container_id" field.
func (su *ServiceUpdate) SetContainerID(s string) *ServiceUpdate {
	su.mutation.SetContainerID(s)
	return su
}

// SetNillableContainerID sets the "container_id" field if the given value is not nil.
func (su *ServiceUpdate) SetNillableContainerID(s *string) *ServiceUpdate {
	if s != nil {
		su.SetContainerID(*s)
	}
	return su
}

// ClearContainerID clears the value of the "container_id" field.
func (su *ServiceUpdate) ClearContainerID() *ServiceUpdate {
	su.mutation.ClearContainerID()
	return su
}

// SetUser sets the "user" edge to the User entity.
func (su *ServiceUpdate) SetUser(u *User) *ServiceUpdate {
	return su.SetUserID(u.ID)
}

// AddPluginIDs adds the "plugins" edge to the Plugin entity by IDs.
func (su *ServiceUpdate) AddPluginIDs(ids ...uuid.UUID) *ServiceUpdate {
	su.mutation.AddPluginIDs(ids...)
	return su
}

// AddPlugins adds the "plugins" edges to the Plugin entity.
func (su *ServiceUpdate) AddPlugins(p ...*Plugin) *ServiceUpdate {
	ids := make([]uuid.UUID, len(p))
	for i := range p {
		ids[i] = p[i].ID
	}
	return su.AddPluginIDs(ids...)
}

// AddWorkspaceIDs adds the "workspaces" edge to the Workspace entity by IDs.
func (su *ServiceUpdate) AddWorkspaceIDs(ids ...uuid.UUID) *ServiceUpdate {
	su.mutation.AddWorkspaceIDs(ids...)
	return su
}

// AddWorkspaces adds the "workspaces" edges to the Workspace entity.
func (su *ServiceUpdate) AddWorkspaces(w ...*Workspace) *ServiceUpdate {
	ids := make([]uuid.UUID, len(w))
	for i := range w {
		ids[i] = w[i].ID
	}
	return su.AddWorkspaceIDs(ids...)
}

// AddFilterIDs adds the "filters" edge to the Filter entity by IDs.
func (su *ServiceUpdate) AddFilterIDs(ids ...uuid.UUID) *ServiceUpdate {
	su.mutation.AddFilterIDs(ids...)
	return su
}

// AddFilters adds the "filters" edges to the Filter entity.
func (su *ServiceUpdate) AddFilters(f ...*Filter) *ServiceUpdate {
	ids := make([]uuid.UUID, len(f))
	for i := range f {
		ids[i] = f[i].ID
	}
	return su.AddFilterIDs(ids...)
}

// AddSessionIDs adds the "sessions" edge to the Session entity by IDs.
func (su *ServiceUpdate) AddSessionIDs(ids ...uuid.UUID) *ServiceUpdate {
	su.mutation.AddSessionIDs(ids...)
	return su
}

// AddSessions adds the "sessions" edges to the Session entity.
func (su *ServiceUpdate) AddSessions(s ...*Session) *ServiceUpdate {
	ids := make([]uuid.UUID, len(s))
	for i := range s {
		ids[i] = s[i].ID
	}
	return su.AddSessionIDs(ids...)
}

// Mutation returns the ServiceMutation object of the builder.
func (su *ServiceUpdate) Mutation() *ServiceMutation {
	return su.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (su *ServiceUpdate) ClearUser() *ServiceUpdate {
	su.mutation.ClearUser()
	return su
}

// ClearPlugins clears all "plugins" edges to the Plugin entity.
func (su *ServiceUpdate) ClearPlugins() *ServiceUpdate {
	su.mutation.ClearPlugins()
	return su
}

// RemovePluginIDs removes the "plugins" edge to Plugin entities by IDs.
func (su *ServiceUpdate) RemovePluginIDs(ids ...uuid.UUID) *ServiceUpdate {
	su.mutation.RemovePluginIDs(ids...)
	return su
}

// RemovePlugins removes "plugins" edges to Plugin entities.
func (su *ServiceUpdate) RemovePlugins(p ...*Plugin) *ServiceUpdate {
	ids := make([]uuid.UUID, len(p))
	for i := range p {
		ids[i] = p[i].ID
	}
	return su.RemovePluginIDs(ids...)
}

// ClearWorkspaces clears all "workspaces" edges to the Workspace entity.
func (su *ServiceUpdate) ClearWorkspaces() *ServiceUpdate {
	su.mutation.ClearWorkspaces()
	return su
}

// RemoveWorkspaceIDs removes the "workspaces" edge to Workspace entities by IDs.
func (su *ServiceUpdate) RemoveWorkspaceIDs(ids ...uuid.UUID) *ServiceUpdate {
	su.mutation.RemoveWorkspaceIDs(ids...)
	return su
}

// RemoveWorkspaces removes "workspaces" edges to Workspace entities.
func (su *ServiceUpdate) RemoveWorkspaces(w ...*Workspace) *ServiceUpdate {
	ids := make([]uuid.UUID, len(w))
	for i := range w {
		ids[i] = w[i].ID
	}
	return su.RemoveWorkspaceIDs(ids...)
}

// ClearFilters clears all "filters" edges to the Filter entity.
func (su *ServiceUpdate) ClearFilters() *ServiceUpdate {
	su.mutation.ClearFilters()
	return su
}

// RemoveFilterIDs removes the "filters" edge to Filter entities by IDs.
func (su *ServiceUpdate) RemoveFilterIDs(ids ...uuid.UUID) *ServiceUpdate {
	su.mutation.RemoveFilterIDs(ids...)
	return su
}

// RemoveFilters removes "filters" edges to Filter entities.
func (su *ServiceUpdate) RemoveFilters(f ...*Filter) *ServiceUpdate {
	ids := make([]uuid.UUID, len(f))
	for i := range f {
		ids[i] = f[i].ID
	}
	return su.RemoveFilterIDs(ids...)
}

// ClearSessions clears all "sessions" edges to the Session entity.
func (su *ServiceUpdate) ClearSessions() *ServiceUpdate {
	su.mutation.ClearSessions()
	return su
}

// RemoveSessionIDs removes the "sessions" edge to Session entities by IDs.
func (su *ServiceUpdate) RemoveSessionIDs(ids ...uuid.UUID) *ServiceUpdate {
	su.mutation.RemoveSessionIDs(ids...)
	return su
}

// RemoveSessions removes "sessions" edges to Session entities.
func (su *ServiceUpdate) RemoveSessions(s ...*Session) *ServiceUpdate {
	ids := make([]uuid.UUID, len(s))
	for i := range s {
		ids[i] = s[i].ID
	}
	return su.RemoveSessionIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (su *ServiceUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, su.sqlSave, su.mutation, su.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (su *ServiceUpdate) SaveX(ctx context.Context) int {
	affected, err := su.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (su *ServiceUpdate) Exec(ctx context.Context) error {
	_, err := su.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (su *ServiceUpdate) ExecX(ctx context.Context) {
	if err := su.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (su *ServiceUpdate) check() error {
	if _, ok := su.mutation.UserID(); su.mutation.UserCleared() && !ok {
		return errors.New(`ent: clearing a required unique edge "Service.user"`)
	}
	return nil
}

func (su *ServiceUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := su.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(service.Table, service.Columns, sqlgraph.NewFieldSpec(service.FieldID, field.TypeUUID))
	if ps := su.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := su.mutation.Name(); ok {
		_spec.SetField(service.FieldName, field.TypeString, value)
	}
	if value, ok := su.mutation.Link(); ok {
		_spec.SetField(service.FieldLink, field.TypeString, value)
	}
	if value, ok := su.mutation.Port(); ok {
		_spec.SetField(service.FieldPort, field.TypeUint32, value)
	}
	if value, ok := su.mutation.AddedPort(); ok {
		_spec.AddField(service.FieldPort, field.TypeUint32, value)
	}
	if value, ok := su.mutation.ContainerID(); ok {
		_spec.SetField(service.FieldContainerID, field.TypeString, value)
	}
	if su.mutation.ContainerIDCleared() {
		_spec.ClearField(service.FieldContainerID, field.TypeString)
	}
	if su.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   service.UserTable,
			Columns: []string{service.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := su.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   service.UserTable,
			Columns: []string{service.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if su.mutation.PluginsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   service.PluginsTable,
			Columns: service.PluginsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(plugin.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := su.mutation.RemovedPluginsIDs(); len(nodes) > 0 && !su.mutation.PluginsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   service.PluginsTable,
			Columns: service.PluginsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(plugin.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := su.mutation.PluginsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   service.PluginsTable,
			Columns: service.PluginsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(plugin.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if su.mutation.WorkspacesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   service.WorkspacesTable,
			Columns: []string{service.WorkspacesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(workspace.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := su.mutation.RemovedWorkspacesIDs(); len(nodes) > 0 && !su.mutation.WorkspacesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   service.WorkspacesTable,
			Columns: []string{service.WorkspacesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(workspace.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := su.mutation.WorkspacesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   service.WorkspacesTable,
			Columns: []string{service.WorkspacesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(workspace.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if su.mutation.FiltersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   service.FiltersTable,
			Columns: []string{service.FiltersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(filter.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := su.mutation.RemovedFiltersIDs(); len(nodes) > 0 && !su.mutation.FiltersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   service.FiltersTable,
			Columns: []string{service.FiltersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(filter.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := su.mutation.FiltersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   service.FiltersTable,
			Columns: []string{service.FiltersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(filter.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if su.mutation.SessionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   service.SessionsTable,
			Columns: []string{service.SessionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(session.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := su.mutation.RemovedSessionsIDs(); len(nodes) > 0 && !su.mutation.SessionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   service.SessionsTable,
			Columns: []string{service.SessionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(session.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := su.mutation.SessionsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   service.SessionsTable,
			Columns: []string{service.SessionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(session.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, su.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{service.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	su.mutation.done = true
	return n, nil
}

// ServiceUpdateOne is the builder for updating a single Service entity.
type ServiceUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ServiceMutation
}

// SetUserID sets the "user_id" field.
func (suo *ServiceUpdateOne) SetUserID(u uuid.UUID) *ServiceUpdateOne {
	suo.mutation.SetUserID(u)
	return suo
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (suo *ServiceUpdateOne) SetNillableUserID(u *uuid.UUID) *ServiceUpdateOne {
	if u != nil {
		suo.SetUserID(*u)
	}
	return suo
}

// SetName sets the "name" field.
func (suo *ServiceUpdateOne) SetName(s string) *ServiceUpdateOne {
	suo.mutation.SetName(s)
	return suo
}

// SetNillableName sets the "name" field if the given value is not nil.
func (suo *ServiceUpdateOne) SetNillableName(s *string) *ServiceUpdateOne {
	if s != nil {
		suo.SetName(*s)
	}
	return suo
}

// SetLink sets the "link" field.
func (suo *ServiceUpdateOne) SetLink(s string) *ServiceUpdateOne {
	suo.mutation.SetLink(s)
	return suo
}

// SetNillableLink sets the "link" field if the given value is not nil.
func (suo *ServiceUpdateOne) SetNillableLink(s *string) *ServiceUpdateOne {
	if s != nil {
		suo.SetLink(*s)
	}
	return suo
}

// SetPort sets the "port" field.
func (suo *ServiceUpdateOne) SetPort(u uint32) *ServiceUpdateOne {
	suo.mutation.ResetPort()
	suo.mutation.SetPort(u)
	return suo
}

// SetNillablePort sets the "port" field if the given value is not nil.
func (suo *ServiceUpdateOne) SetNillablePort(u *uint32) *ServiceUpdateOne {
	if u != nil {
		suo.SetPort(*u)
	}
	return suo
}

// AddPort adds u to the "port" field.
func (suo *ServiceUpdateOne) AddPort(u int32) *ServiceUpdateOne {
	suo.mutation.AddPort(u)
	return suo
}

// SetContainerID sets the "container_id" field.
func (suo *ServiceUpdateOne) SetContainerID(s string) *ServiceUpdateOne {
	suo.mutation.SetContainerID(s)
	return suo
}

// SetNillableContainerID sets the "container_id" field if the given value is not nil.
func (suo *ServiceUpdateOne) SetNillableContainerID(s *string) *ServiceUpdateOne {
	if s != nil {
		suo.SetContainerID(*s)
	}
	return suo
}

// ClearContainerID clears the value of the "container_id" field.
func (suo *ServiceUpdateOne) ClearContainerID() *ServiceUpdateOne {
	suo.mutation.ClearContainerID()
	return suo
}

// SetUser sets the "user" edge to the User entity.
func (suo *ServiceUpdateOne) SetUser(u *User) *ServiceUpdateOne {
	return suo.SetUserID(u.ID)
}

// AddPluginIDs adds the "plugins" edge to the Plugin entity by IDs.
func (suo *ServiceUpdateOne) AddPluginIDs(ids ...uuid.UUID) *ServiceUpdateOne {
	suo.mutation.AddPluginIDs(ids...)
	return suo
}

// AddPlugins adds the "plugins" edges to the Plugin entity.
func (suo *ServiceUpdateOne) AddPlugins(p ...*Plugin) *ServiceUpdateOne {
	ids := make([]uuid.UUID, len(p))
	for i := range p {
		ids[i] = p[i].ID
	}
	return suo.AddPluginIDs(ids...)
}

// AddWorkspaceIDs adds the "workspaces" edge to the Workspace entity by IDs.
func (suo *ServiceUpdateOne) AddWorkspaceIDs(ids ...uuid.UUID) *ServiceUpdateOne {
	suo.mutation.AddWorkspaceIDs(ids...)
	return suo
}

// AddWorkspaces adds the "workspaces" edges to the Workspace entity.
func (suo *ServiceUpdateOne) AddWorkspaces(w ...*Workspace) *ServiceUpdateOne {
	ids := make([]uuid.UUID, len(w))
	for i := range w {
		ids[i] = w[i].ID
	}
	return suo.AddWorkspaceIDs(ids...)
}

// AddFilterIDs adds the "filters" edge to the Filter entity by IDs.
func (suo *ServiceUpdateOne) AddFilterIDs(ids ...uuid.UUID) *ServiceUpdateOne {
	suo.mutation.AddFilterIDs(ids...)
	return suo
}

// AddFilters adds the "filters" edges to the Filter entity.
func (suo *ServiceUpdateOne) AddFilters(f ...*Filter) *ServiceUpdateOne {
	ids := make([]uuid.UUID, len(f))
	for i := range f {
		ids[i] = f[i].ID
	}
	return suo.AddFilterIDs(ids...)
}

// AddSessionIDs adds the "sessions" edge to the Session entity by IDs.
func (suo *ServiceUpdateOne) AddSessionIDs(ids ...uuid.UUID) *ServiceUpdateOne {
	suo.mutation.AddSessionIDs(ids...)
	return suo
}

// AddSessions adds the "sessions" edges to the Session entity.
func (suo *ServiceUpdateOne) AddSessions(s ...*Session) *ServiceUpdateOne {
	ids := make([]uuid.UUID, len(s))
	for i := range s {
		ids[i] = s[i].ID
	}
	return suo.AddSessionIDs(ids...)
}

// Mutation returns the ServiceMutation object of the builder.
func (suo *ServiceUpdateOne) Mutation() *ServiceMutation {
	return suo.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (suo *ServiceUpdateOne) ClearUser() *ServiceUpdateOne {
	suo.mutation.ClearUser()
	return suo
}

// ClearPlugins clears all "plugins" edges to the Plugin entity.
func (suo *ServiceUpdateOne) ClearPlugins() *ServiceUpdateOne {
	suo.mutation.ClearPlugins()
	return suo
}

// RemovePluginIDs removes the "plugins" edge to Plugin entities by IDs.
func (suo *ServiceUpdateOne) RemovePluginIDs(ids ...uuid.UUID) *ServiceUpdateOne {
	suo.mutation.RemovePluginIDs(ids...)
	return suo
}

// RemovePlugins removes "plugins" edges to Plugin entities.
func (suo *ServiceUpdateOne) RemovePlugins(p ...*Plugin) *ServiceUpdateOne {
	ids := make([]uuid.UUID, len(p))
	for i := range p {
		ids[i] = p[i].ID
	}
	return suo.RemovePluginIDs(ids...)
}

// ClearWorkspaces clears all "workspaces" edges to the Workspace entity.
func (suo *ServiceUpdateOne) ClearWorkspaces() *ServiceUpdateOne {
	suo.mutation.ClearWorkspaces()
	return suo
}

// RemoveWorkspaceIDs removes the "workspaces" edge to Workspace entities by IDs.
func (suo *ServiceUpdateOne) RemoveWorkspaceIDs(ids ...uuid.UUID) *ServiceUpdateOne {
	suo.mutation.RemoveWorkspaceIDs(ids...)
	return suo
}

// RemoveWorkspaces removes "workspaces" edges to Workspace entities.
func (suo *ServiceUpdateOne) RemoveWorkspaces(w ...*Workspace) *ServiceUpdateOne {
	ids := make([]uuid.UUID, len(w))
	for i := range w {
		ids[i] = w[i].ID
	}
	return suo.RemoveWorkspaceIDs(ids...)
}

// ClearFilters clears all "filters" edges to the Filter entity.
func (suo *ServiceUpdateOne) ClearFilters() *ServiceUpdateOne {
	suo.mutation.ClearFilters()
	return suo
}

// RemoveFilterIDs removes the "filters" edge to Filter entities by IDs.
func (suo *ServiceUpdateOne) RemoveFilterIDs(ids ...uuid.UUID) *ServiceUpdateOne {
	suo.mutation.RemoveFilterIDs(ids...)
	return suo
}

// RemoveFilters removes "filters" edges to Filter entities.
func (suo *ServiceUpdateOne) RemoveFilters(f ...*Filter) *ServiceUpdateOne {
	ids := make([]uuid.UUID, len(f))
	for i := range f {
		ids[i] = f[i].ID
	}
	return suo.RemoveFilterIDs(ids...)
}

// ClearSessions clears all "sessions" edges to the Session entity.
func (suo *ServiceUpdateOne) ClearSessions() *ServiceUpdateOne {
	suo.mutation.ClearSessions()
	return suo
}

// RemoveSessionIDs removes the "sessions" edge to Session entities by IDs.
func (suo *ServiceUpdateOne) RemoveSessionIDs(ids ...uuid.UUID) *ServiceUpdateOne {
	suo.mutation.RemoveSessionIDs(ids...)
	return suo
}

// RemoveSessions removes "sessions" edges to Session entities.
func (suo *ServiceUpdateOne) RemoveSessions(s ...*Session) *ServiceUpdateOne {
	ids := make([]uuid.UUID, len(s))
	for i := range s {
		ids[i] = s[i].ID
	}
	return suo.RemoveSessionIDs(ids...)
}

// Where appends a list predicates to the ServiceUpdate builder.
func (suo *ServiceUpdateOne) Where(ps ...predicate.Service) *ServiceUpdateOne {
	suo.mutation.Where(ps...)
	return suo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (suo *ServiceUpdateOne) Select(field string, fields ...string) *ServiceUpdateOne {
	suo.fields = append([]string{field}, fields...)
	return suo
}

// Save executes the query and returns the updated Service entity.
func (suo *ServiceUpdateOne) Save(ctx context.Context) (*Service, error) {
	return withHooks(ctx, suo.sqlSave, suo.mutation, suo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (suo *ServiceUpdateOne) SaveX(ctx context.Context) *Service {
	node, err := suo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (suo *ServiceUpdateOne) Exec(ctx context.Context) error {
	_, err := suo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (suo *ServiceUpdateOne) ExecX(ctx context.Context) {
	if err := suo.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (suo *ServiceUpdateOne) check() error {
	if _, ok := suo.mutation.UserID(); suo.mutation.UserCleared() && !ok {
		return errors.New(`ent: clearing a required unique edge "Service.user"`)
	}
	return nil
}

func (suo *ServiceUpdateOne) sqlSave(ctx context.Context) (_node *Service, err error) {
	if err := suo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(service.Table, service.Columns, sqlgraph.NewFieldSpec(service.FieldID, field.TypeUUID))
	id, ok := suo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Service.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := suo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, service.FieldID)
		for _, f := range fields {
			if !service.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != service.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := suo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := suo.mutation.Name(); ok {
		_spec.SetField(service.FieldName, field.TypeString, value)
	}
	if value, ok := suo.mutation.Link(); ok {
		_spec.SetField(service.FieldLink, field.TypeString, value)
	}
	if value, ok := suo.mutation.Port(); ok {
		_spec.SetField(service.FieldPort, field.TypeUint32, value)
	}
	if value, ok := suo.mutation.AddedPort(); ok {
		_spec.AddField(service.FieldPort, field.TypeUint32, value)
	}
	if value, ok := suo.mutation.ContainerID(); ok {
		_spec.SetField(service.FieldContainerID, field.TypeString, value)
	}
	if suo.mutation.ContainerIDCleared() {
		_spec.ClearField(service.FieldContainerID, field.TypeString)
	}
	if suo.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   service.UserTable,
			Columns: []string{service.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := suo.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   service.UserTable,
			Columns: []string{service.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if suo.mutation.PluginsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   service.PluginsTable,
			Columns: service.PluginsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(plugin.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := suo.mutation.RemovedPluginsIDs(); len(nodes) > 0 && !suo.mutation.PluginsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   service.PluginsTable,
			Columns: service.PluginsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(plugin.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := suo.mutation.PluginsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   service.PluginsTable,
			Columns: service.PluginsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(plugin.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if suo.mutation.WorkspacesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   service.WorkspacesTable,
			Columns: []string{service.WorkspacesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(workspace.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := suo.mutation.RemovedWorkspacesIDs(); len(nodes) > 0 && !suo.mutation.WorkspacesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   service.WorkspacesTable,
			Columns: []string{service.WorkspacesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(workspace.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := suo.mutation.WorkspacesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   service.WorkspacesTable,
			Columns: []string{service.WorkspacesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(workspace.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if suo.mutation.FiltersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   service.FiltersTable,
			Columns: []string{service.FiltersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(filter.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := suo.mutation.RemovedFiltersIDs(); len(nodes) > 0 && !suo.mutation.FiltersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   service.FiltersTable,
			Columns: []string{service.FiltersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(filter.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := suo.mutation.FiltersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   service.FiltersTable,
			Columns: []string{service.FiltersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(filter.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if suo.mutation.SessionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   service.SessionsTable,
			Columns: []string{service.SessionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(session.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := suo.mutation.RemovedSessionsIDs(); len(nodes) > 0 && !suo.mutation.SessionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   service.SessionsTable,
			Columns: []string{service.SessionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(session.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := suo.mutation.SessionsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   service.SessionsTable,
			Columns: []string{service.SessionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(session.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Service{config: suo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, suo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{service.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	suo.mutation.done = true
	return _node, nil
}
