// Code generated by ent, DO NOT EDIT.

package ent

import (
	"altron/core/repositories/ent/filter"
	"altron/core/repositories/ent/matchedpacket"
	"altron/core/repositories/ent/predicate"
	"altron/core/repositories/ent/session"
	"altron/core/repositories/ent/sessionfilter"
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// SessionFilterUpdate is the builder for updating SessionFilter entities.
type SessionFilterUpdate struct {
	config
	hooks    []Hook
	mutation *SessionFilterMutation
}

// Where appends a list predicates to the SessionFilterUpdate builder.
func (sfu *SessionFilterUpdate) Where(ps ...predicate.SessionFilter) *SessionFilterUpdate {
	sfu.mutation.Where(ps...)
	return sfu
}

// SetSessionID sets the "session_id" field.
func (sfu *SessionFilterUpdate) SetSessionID(u uuid.UUID) *SessionFilterUpdate {
	sfu.mutation.SetSessionID(u)
	return sfu
}

// SetNillableSessionID sets the "session_id" field if the given value is not nil.
func (sfu *SessionFilterUpdate) SetNillableSessionID(u *uuid.UUID) *SessionFilterUpdate {
	if u != nil {
		sfu.SetSessionID(*u)
	}
	return sfu
}

// SetFilterID sets the "filter_id" field.
func (sfu *SessionFilterUpdate) SetFilterID(u uuid.UUID) *SessionFilterUpdate {
	sfu.mutation.SetFilterID(u)
	return sfu
}

// SetNillableFilterID sets the "filter_id" field if the given value is not nil.
func (sfu *SessionFilterUpdate) SetNillableFilterID(u *uuid.UUID) *SessionFilterUpdate {
	if u != nil {
		sfu.SetFilterID(*u)
	}
	return sfu
}

// SetMatchesCount sets the "matches_count" field.
func (sfu *SessionFilterUpdate) SetMatchesCount(i int) *SessionFilterUpdate {
	sfu.mutation.ResetMatchesCount()
	sfu.mutation.SetMatchesCount(i)
	return sfu
}

// SetNillableMatchesCount sets the "matches_count" field if the given value is not nil.
func (sfu *SessionFilterUpdate) SetNillableMatchesCount(i *int) *SessionFilterUpdate {
	if i != nil {
		sfu.SetMatchesCount(*i)
	}
	return sfu
}

// AddMatchesCount adds i to the "matches_count" field.
func (sfu *SessionFilterUpdate) AddMatchesCount(i int) *SessionFilterUpdate {
	sfu.mutation.AddMatchesCount(i)
	return sfu
}

// SetSession sets the "session" edge to the Session entity.
func (sfu *SessionFilterUpdate) SetSession(s *Session) *SessionFilterUpdate {
	return sfu.SetSessionID(s.ID)
}

// SetFilter sets the "filter" edge to the Filter entity.
func (sfu *SessionFilterUpdate) SetFilter(f *Filter) *SessionFilterUpdate {
	return sfu.SetFilterID(f.ID)
}

// AddMatchedPacketIDs adds the "matched_packets" edge to the MatchedPacket entity by IDs.
func (sfu *SessionFilterUpdate) AddMatchedPacketIDs(ids ...uuid.UUID) *SessionFilterUpdate {
	sfu.mutation.AddMatchedPacketIDs(ids...)
	return sfu
}

// AddMatchedPackets adds the "matched_packets" edges to the MatchedPacket entity.
func (sfu *SessionFilterUpdate) AddMatchedPackets(m ...*MatchedPacket) *SessionFilterUpdate {
	ids := make([]uuid.UUID, len(m))
	for i := range m {
		ids[i] = m[i].ID
	}
	return sfu.AddMatchedPacketIDs(ids...)
}

// Mutation returns the SessionFilterMutation object of the builder.
func (sfu *SessionFilterUpdate) Mutation() *SessionFilterMutation {
	return sfu.mutation
}

// ClearSession clears the "session" edge to the Session entity.
func (sfu *SessionFilterUpdate) ClearSession() *SessionFilterUpdate {
	sfu.mutation.ClearSession()
	return sfu
}

// ClearFilter clears the "filter" edge to the Filter entity.
func (sfu *SessionFilterUpdate) ClearFilter() *SessionFilterUpdate {
	sfu.mutation.ClearFilter()
	return sfu
}

// ClearMatchedPackets clears all "matched_packets" edges to the MatchedPacket entity.
func (sfu *SessionFilterUpdate) ClearMatchedPackets() *SessionFilterUpdate {
	sfu.mutation.ClearMatchedPackets()
	return sfu
}

// RemoveMatchedPacketIDs removes the "matched_packets" edge to MatchedPacket entities by IDs.
func (sfu *SessionFilterUpdate) RemoveMatchedPacketIDs(ids ...uuid.UUID) *SessionFilterUpdate {
	sfu.mutation.RemoveMatchedPacketIDs(ids...)
	return sfu
}

// RemoveMatchedPackets removes "matched_packets" edges to MatchedPacket entities.
func (sfu *SessionFilterUpdate) RemoveMatchedPackets(m ...*MatchedPacket) *SessionFilterUpdate {
	ids := make([]uuid.UUID, len(m))
	for i := range m {
		ids[i] = m[i].ID
	}
	return sfu.RemoveMatchedPacketIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (sfu *SessionFilterUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, sfu.sqlSave, sfu.mutation, sfu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (sfu *SessionFilterUpdate) SaveX(ctx context.Context) int {
	affected, err := sfu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (sfu *SessionFilterUpdate) Exec(ctx context.Context) error {
	_, err := sfu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (sfu *SessionFilterUpdate) ExecX(ctx context.Context) {
	if err := sfu.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (sfu *SessionFilterUpdate) check() error {
	if _, ok := sfu.mutation.SessionID(); sfu.mutation.SessionCleared() && !ok {
		return errors.New(`ent: clearing a required unique edge "SessionFilter.session"`)
	}
	if _, ok := sfu.mutation.FilterID(); sfu.mutation.FilterCleared() && !ok {
		return errors.New(`ent: clearing a required unique edge "SessionFilter.filter"`)
	}
	return nil
}

func (sfu *SessionFilterUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := sfu.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(sessionfilter.Table, sessionfilter.Columns, sqlgraph.NewFieldSpec(sessionfilter.FieldID, field.TypeUUID))
	if ps := sfu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := sfu.mutation.MatchesCount(); ok {
		_spec.SetField(sessionfilter.FieldMatchesCount, field.TypeInt, value)
	}
	if value, ok := sfu.mutation.AddedMatchesCount(); ok {
		_spec.AddField(sessionfilter.FieldMatchesCount, field.TypeInt, value)
	}
	if sfu.mutation.SessionCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   sessionfilter.SessionTable,
			Columns: []string{sessionfilter.SessionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(session.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := sfu.mutation.SessionIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   sessionfilter.SessionTable,
			Columns: []string{sessionfilter.SessionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(session.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if sfu.mutation.FilterCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   sessionfilter.FilterTable,
			Columns: []string{sessionfilter.FilterColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(filter.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := sfu.mutation.FilterIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   sessionfilter.FilterTable,
			Columns: []string{sessionfilter.FilterColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(filter.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if sfu.mutation.MatchedPacketsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   sessionfilter.MatchedPacketsTable,
			Columns: []string{sessionfilter.MatchedPacketsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(matchedpacket.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := sfu.mutation.RemovedMatchedPacketsIDs(); len(nodes) > 0 && !sfu.mutation.MatchedPacketsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   sessionfilter.MatchedPacketsTable,
			Columns: []string{sessionfilter.MatchedPacketsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(matchedpacket.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := sfu.mutation.MatchedPacketsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   sessionfilter.MatchedPacketsTable,
			Columns: []string{sessionfilter.MatchedPacketsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(matchedpacket.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, sfu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{sessionfilter.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	sfu.mutation.done = true
	return n, nil
}

// SessionFilterUpdateOne is the builder for updating a single SessionFilter entity.
type SessionFilterUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *SessionFilterMutation
}

// SetSessionID sets the "session_id" field.
func (sfuo *SessionFilterUpdateOne) SetSessionID(u uuid.UUID) *SessionFilterUpdateOne {
	sfuo.mutation.SetSessionID(u)
	return sfuo
}

// SetNillableSessionID sets the "session_id" field if the given value is not nil.
func (sfuo *SessionFilterUpdateOne) SetNillableSessionID(u *uuid.UUID) *SessionFilterUpdateOne {
	if u != nil {
		sfuo.SetSessionID(*u)
	}
	return sfuo
}

// SetFilterID sets the "filter_id" field.
func (sfuo *SessionFilterUpdateOne) SetFilterID(u uuid.UUID) *SessionFilterUpdateOne {
	sfuo.mutation.SetFilterID(u)
	return sfuo
}

// SetNillableFilterID sets the "filter_id" field if the given value is not nil.
func (sfuo *SessionFilterUpdateOne) SetNillableFilterID(u *uuid.UUID) *SessionFilterUpdateOne {
	if u != nil {
		sfuo.SetFilterID(*u)
	}
	return sfuo
}

// SetMatchesCount sets the "matches_count" field.
func (sfuo *SessionFilterUpdateOne) SetMatchesCount(i int) *SessionFilterUpdateOne {
	sfuo.mutation.ResetMatchesCount()
	sfuo.mutation.SetMatchesCount(i)
	return sfuo
}

// SetNillableMatchesCount sets the "matches_count" field if the given value is not nil.
func (sfuo *SessionFilterUpdateOne) SetNillableMatchesCount(i *int) *SessionFilterUpdateOne {
	if i != nil {
		sfuo.SetMatchesCount(*i)
	}
	return sfuo
}

// AddMatchesCount adds i to the "matches_count" field.
func (sfuo *SessionFilterUpdateOne) AddMatchesCount(i int) *SessionFilterUpdateOne {
	sfuo.mutation.AddMatchesCount(i)
	return sfuo
}

// SetSession sets the "session" edge to the Session entity.
func (sfuo *SessionFilterUpdateOne) SetSession(s *Session) *SessionFilterUpdateOne {
	return sfuo.SetSessionID(s.ID)
}

// SetFilter sets the "filter" edge to the Filter entity.
func (sfuo *SessionFilterUpdateOne) SetFilter(f *Filter) *SessionFilterUpdateOne {
	return sfuo.SetFilterID(f.ID)
}

// AddMatchedPacketIDs adds the "matched_packets" edge to the MatchedPacket entity by IDs.
func (sfuo *SessionFilterUpdateOne) AddMatchedPacketIDs(ids ...uuid.UUID) *SessionFilterUpdateOne {
	sfuo.mutation.AddMatchedPacketIDs(ids...)
	return sfuo
}

// AddMatchedPackets adds the "matched_packets" edges to the MatchedPacket entity.
func (sfuo *SessionFilterUpdateOne) AddMatchedPackets(m ...*MatchedPacket) *SessionFilterUpdateOne {
	ids := make([]uuid.UUID, len(m))
	for i := range m {
		ids[i] = m[i].ID
	}
	return sfuo.AddMatchedPacketIDs(ids...)
}

// Mutation returns the SessionFilterMutation object of the builder.
func (sfuo *SessionFilterUpdateOne) Mutation() *SessionFilterMutation {
	return sfuo.mutation
}

// ClearSession clears the "session" edge to the Session entity.
func (sfuo *SessionFilterUpdateOne) ClearSession() *SessionFilterUpdateOne {
	sfuo.mutation.ClearSession()
	return sfuo
}

// ClearFilter clears the "filter" edge to the Filter entity.
func (sfuo *SessionFilterUpdateOne) ClearFilter() *SessionFilterUpdateOne {
	sfuo.mutation.ClearFilter()
	return sfuo
}

// ClearMatchedPackets clears all "matched_packets" edges to the MatchedPacket entity.
func (sfuo *SessionFilterUpdateOne) ClearMatchedPackets() *SessionFilterUpdateOne {
	sfuo.mutation.ClearMatchedPackets()
	return sfuo
}

// RemoveMatchedPacketIDs removes the "matched_packets" edge to MatchedPacket entities by IDs.
func (sfuo *SessionFilterUpdateOne) RemoveMatchedPacketIDs(ids ...uuid.UUID) *SessionFilterUpdateOne {
	sfuo.mutation.RemoveMatchedPacketIDs(ids...)
	return sfuo
}

// RemoveMatchedPackets removes "matched_packets" edges to MatchedPacket entities.
func (sfuo *SessionFilterUpdateOne) RemoveMatchedPackets(m ...*MatchedPacket) *SessionFilterUpdateOne {
	ids := make([]uuid.UUID, len(m))
	for i := range m {
		ids[i] = m[i].ID
	}
	return sfuo.RemoveMatchedPacketIDs(ids...)
}

// Where appends a list predicates to the SessionFilterUpdate builder.
func (sfuo *SessionFilterUpdateOne) Where(ps ...predicate.SessionFilter) *SessionFilterUpdateOne {
	sfuo.mutation.Where(ps...)
	return sfuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (sfuo *SessionFilterUpdateOne) Select(field string, fields ...string) *SessionFilterUpdateOne {
	sfuo.fields = append([]string{field}, fields...)
	return sfuo
}

// Save executes the query and returns the updated SessionFilter entity.
func (sfuo *SessionFilterUpdateOne) Save(ctx context.Context) (*SessionFilter, error) {
	return withHooks(ctx, sfuo.sqlSave, sfuo.mutation, sfuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (sfuo *SessionFilterUpdateOne) SaveX(ctx context.Context) *SessionFilter {
	node, err := sfuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (sfuo *SessionFilterUpdateOne) Exec(ctx context.Context) error {
	_, err := sfuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (sfuo *SessionFilterUpdateOne) ExecX(ctx context.Context) {
	if err := sfuo.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (sfuo *SessionFilterUpdateOne) check() error {
	if _, ok := sfuo.mutation.SessionID(); sfuo.mutation.SessionCleared() && !ok {
		return errors.New(`ent: clearing a required unique edge "SessionFilter.session"`)
	}
	if _, ok := sfuo.mutation.FilterID(); sfuo.mutation.FilterCleared() && !ok {
		return errors.New(`ent: clearing a required unique edge "SessionFilter.filter"`)
	}
	return nil
}

func (sfuo *SessionFilterUpdateOne) sqlSave(ctx context.Context) (_node *SessionFilter, err error) {
	if err := sfuo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(sessionfilter.Table, sessionfilter.Columns, sqlgraph.NewFieldSpec(sessionfilter.FieldID, field.TypeUUID))
	id, ok := sfuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "SessionFilter.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := sfuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, sessionfilter.FieldID)
		for _, f := range fields {
			if !sessionfilter.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != sessionfilter.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := sfuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := sfuo.mutation.MatchesCount(); ok {
		_spec.SetField(sessionfilter.FieldMatchesCount, field.TypeInt, value)
	}
	if value, ok := sfuo.mutation.AddedMatchesCount(); ok {
		_spec.AddField(sessionfilter.FieldMatchesCount, field.TypeInt, value)
	}
	if sfuo.mutation.SessionCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   sessionfilter.SessionTable,
			Columns: []string{sessionfilter.SessionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(session.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := sfuo.mutation.SessionIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   sessionfilter.SessionTable,
			Columns: []string{sessionfilter.SessionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(session.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if sfuo.mutation.FilterCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   sessionfilter.FilterTable,
			Columns: []string{sessionfilter.FilterColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(filter.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := sfuo.mutation.FilterIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   sessionfilter.FilterTable,
			Columns: []string{sessionfilter.FilterColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(filter.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if sfuo.mutation.MatchedPacketsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   sessionfilter.MatchedPacketsTable,
			Columns: []string{sessionfilter.MatchedPacketsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(matchedpacket.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := sfuo.mutation.RemovedMatchedPacketsIDs(); len(nodes) > 0 && !sfuo.mutation.MatchedPacketsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   sessionfilter.MatchedPacketsTable,
			Columns: []string{sessionfilter.MatchedPacketsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(matchedpacket.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := sfuo.mutation.MatchedPacketsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   sessionfilter.MatchedPacketsTable,
			Columns: []string{sessionfilter.MatchedPacketsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(matchedpacket.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &SessionFilter{config: sfuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, sfuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{sessionfilter.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	sfuo.mutation.done = true
	return _node, nil
}
