// Code generated by ent, DO NOT EDIT.

package ent

import (
	"altron/core/repositories/ent/cartsession"
	"altron/core/repositories/ent/packet"
	"altron/core/repositories/ent/pcapworkspace"
	"altron/core/repositories/ent/predicate"
	"altron/core/repositories/ent/session"
	"altron/core/repositories/ent/sessionfilter"
	"altron/core/repositories/ent/workspace"
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// SessionUpdate is the builder for updating Session entities.
type SessionUpdate struct {
	config
	hooks    []Hook
	mutation *SessionMutation
}

// Where appends a list predicates to the SessionUpdate builder.
func (su *SessionUpdate) Where(ps ...predicate.Session) *SessionUpdate {
	su.mutation.Where(ps...)
	return su
}

// SetSentAt sets the "sent_at" field.
func (su *SessionUpdate) SetSentAt(t time.Time) *SessionUpdate {
	su.mutation.SetSentAt(t)
	return su
}

// SetNillableSentAt sets the "sent_at" field if the given value is not nil.
func (su *SessionUpdate) SetNillableSentAt(t *time.Time) *SessionUpdate {
	if t != nil {
		su.SetSentAt(*t)
	}
	return su
}

// SetClientHost sets the "client_host" field.
func (su *SessionUpdate) SetClientHost(s string) *SessionUpdate {
	su.mutation.SetClientHost(s)
	return su
}

// SetNillableClientHost sets the "client_host" field if the given value is not nil.
func (su *SessionUpdate) SetNillableClientHost(s *string) *SessionUpdate {
	if s != nil {
		su.SetClientHost(*s)
	}
	return su
}

// SetServerPort sets the "server_port" field.
func (su *SessionUpdate) SetServerPort(u uint32) *SessionUpdate {
	su.mutation.ResetServerPort()
	su.mutation.SetServerPort(u)
	return su
}

// SetNillableServerPort sets the "server_port" field if the given value is not nil.
func (su *SessionUpdate) SetNillableServerPort(u *uint32) *SessionUpdate {
	if u != nil {
		su.SetServerPort(*u)
	}
	return su
}

// AddServerPort adds u to the "server_port" field.
func (su *SessionUpdate) AddServerPort(u int32) *SessionUpdate {
	su.mutation.AddServerPort(u)
	return su
}

// SetTTL sets the "ttl" field.
func (su *SessionUpdate) SetTTL(u uint8) *SessionUpdate {
	su.mutation.ResetTTL()
	su.mutation.SetTTL(u)
	return su
}

// SetNillableTTL sets the "ttl" field if the given value is not nil.
func (su *SessionUpdate) SetNillableTTL(u *uint8) *SessionUpdate {
	if u != nil {
		su.SetTTL(*u)
	}
	return su
}

// AddTTL adds u to the "ttl" field.
func (su *SessionUpdate) AddTTL(u int8) *SessionUpdate {
	su.mutation.AddTTL(u)
	return su
}

// SetPacketsCount sets the "packets_count" field.
func (su *SessionUpdate) SetPacketsCount(i int) *SessionUpdate {
	su.mutation.ResetPacketsCount()
	su.mutation.SetPacketsCount(i)
	return su
}

// SetNillablePacketsCount sets the "packets_count" field if the given value is not nil.
func (su *SessionUpdate) SetNillablePacketsCount(i *int) *SessionUpdate {
	if i != nil {
		su.SetPacketsCount(*i)
	}
	return su
}

// AddPacketsCount adds i to the "packets_count" field.
func (su *SessionUpdate) AddPacketsCount(i int) *SessionUpdate {
	su.mutation.AddPacketsCount(i)
	return su
}

// SetClientUserAgent sets the "client_user_agent" field.
func (su *SessionUpdate) SetClientUserAgent(s string) *SessionUpdate {
	su.mutation.SetClientUserAgent(s)
	return su
}

// SetNillableClientUserAgent sets the "client_user_agent" field if the given value is not nil.
func (su *SessionUpdate) SetNillableClientUserAgent(s *string) *SessionUpdate {
	if s != nil {
		su.SetClientUserAgent(*s)
	}
	return su
}

// ClearClientUserAgent clears the value of the "client_user_agent" field.
func (su *SessionUpdate) ClearClientUserAgent() *SessionUpdate {
	su.mutation.ClearClientUserAgent()
	return su
}

// SetProtocol sets the "protocol" field.
func (su *SessionUpdate) SetProtocol(s string) *SessionUpdate {
	su.mutation.SetProtocol(s)
	return su
}

// SetNillableProtocol sets the "protocol" field if the given value is not nil.
func (su *SessionUpdate) SetNillableProtocol(s *string) *SessionUpdate {
	if s != nil {
		su.SetProtocol(*s)
	}
	return su
}

// SetAverageResponseTime sets the "average_response_time" field.
func (su *SessionUpdate) SetAverageResponseTime(f float64) *SessionUpdate {
	su.mutation.ResetAverageResponseTime()
	su.mutation.SetAverageResponseTime(f)
	return su
}

// SetNillableAverageResponseTime sets the "average_response_time" field if the given value is not nil.
func (su *SessionUpdate) SetNillableAverageResponseTime(f *float64) *SessionUpdate {
	if f != nil {
		su.SetAverageResponseTime(*f)
	}
	return su
}

// AddAverageResponseTime adds f to the "average_response_time" field.
func (su *SessionUpdate) AddAverageResponseTime(f float64) *SessionUpdate {
	su.mutation.AddAverageResponseTime(f)
	return su
}

// SetRequestsNumber sets the "requests_number" field.
func (su *SessionUpdate) SetRequestsNumber(i int) *SessionUpdate {
	su.mutation.ResetRequestsNumber()
	su.mutation.SetRequestsNumber(i)
	return su
}

// SetNillableRequestsNumber sets the "requests_number" field if the given value is not nil.
func (su *SessionUpdate) SetNillableRequestsNumber(i *int) *SessionUpdate {
	if i != nil {
		su.SetRequestsNumber(*i)
	}
	return su
}

// AddRequestsNumber adds i to the "requests_number" field.
func (su *SessionUpdate) AddRequestsNumber(i int) *SessionUpdate {
	su.mutation.AddRequestsNumber(i)
	return su
}

// SetWorkspaceID sets the "workspace" edge to the Workspace entity by ID.
func (su *SessionUpdate) SetWorkspaceID(id uuid.UUID) *SessionUpdate {
	su.mutation.SetWorkspaceID(id)
	return su
}

// SetWorkspace sets the "workspace" edge to the Workspace entity.
func (su *SessionUpdate) SetWorkspace(w *Workspace) *SessionUpdate {
	return su.SetWorkspaceID(w.ID)
}

// AddPcapWorkspaceIDs adds the "pcap_workspace" edge to the PcapWorkspace entity by IDs.
func (su *SessionUpdate) AddPcapWorkspaceIDs(ids ...uuid.UUID) *SessionUpdate {
	su.mutation.AddPcapWorkspaceIDs(ids...)
	return su
}

// AddPcapWorkspace adds the "pcap_workspace" edges to the PcapWorkspace entity.
func (su *SessionUpdate) AddPcapWorkspace(p ...*PcapWorkspace) *SessionUpdate {
	ids := make([]uuid.UUID, len(p))
	for i := range p {
		ids[i] = p[i].ID
	}
	return su.AddPcapWorkspaceIDs(ids...)
}

// SetInCartID sets the "in_cart" edge to the CartSession entity by ID.
func (su *SessionUpdate) SetInCartID(id uuid.UUID) *SessionUpdate {
	su.mutation.SetInCartID(id)
	return su
}

// SetNillableInCartID sets the "in_cart" edge to the CartSession entity by ID if the given value is not nil.
func (su *SessionUpdate) SetNillableInCartID(id *uuid.UUID) *SessionUpdate {
	if id != nil {
		su = su.SetInCartID(*id)
	}
	return su
}

// SetInCart sets the "in_cart" edge to the CartSession entity.
func (su *SessionUpdate) SetInCart(c *CartSession) *SessionUpdate {
	return su.SetInCartID(c.ID)
}

// AddPacketIDs adds the "packets" edge to the Packet entity by IDs.
func (su *SessionUpdate) AddPacketIDs(ids ...uuid.UUID) *SessionUpdate {
	su.mutation.AddPacketIDs(ids...)
	return su
}

// AddPackets adds the "packets" edges to the Packet entity.
func (su *SessionUpdate) AddPackets(p ...*Packet) *SessionUpdate {
	ids := make([]uuid.UUID, len(p))
	for i := range p {
		ids[i] = p[i].ID
	}
	return su.AddPacketIDs(ids...)
}

// AddSessionFilterIDs adds the "session_filters" edge to the SessionFilter entity by IDs.
func (su *SessionUpdate) AddSessionFilterIDs(ids ...uuid.UUID) *SessionUpdate {
	su.mutation.AddSessionFilterIDs(ids...)
	return su
}

// AddSessionFilters adds the "session_filters" edges to the SessionFilter entity.
func (su *SessionUpdate) AddSessionFilters(s ...*SessionFilter) *SessionUpdate {
	ids := make([]uuid.UUID, len(s))
	for i := range s {
		ids[i] = s[i].ID
	}
	return su.AddSessionFilterIDs(ids...)
}

// Mutation returns the SessionMutation object of the builder.
func (su *SessionUpdate) Mutation() *SessionMutation {
	return su.mutation
}

// ClearWorkspace clears the "workspace" edge to the Workspace entity.
func (su *SessionUpdate) ClearWorkspace() *SessionUpdate {
	su.mutation.ClearWorkspace()
	return su
}

// ClearPcapWorkspace clears all "pcap_workspace" edges to the PcapWorkspace entity.
func (su *SessionUpdate) ClearPcapWorkspace() *SessionUpdate {
	su.mutation.ClearPcapWorkspace()
	return su
}

// RemovePcapWorkspaceIDs removes the "pcap_workspace" edge to PcapWorkspace entities by IDs.
func (su *SessionUpdate) RemovePcapWorkspaceIDs(ids ...uuid.UUID) *SessionUpdate {
	su.mutation.RemovePcapWorkspaceIDs(ids...)
	return su
}

// RemovePcapWorkspace removes "pcap_workspace" edges to PcapWorkspace entities.
func (su *SessionUpdate) RemovePcapWorkspace(p ...*PcapWorkspace) *SessionUpdate {
	ids := make([]uuid.UUID, len(p))
	for i := range p {
		ids[i] = p[i].ID
	}
	return su.RemovePcapWorkspaceIDs(ids...)
}

// ClearInCart clears the "in_cart" edge to the CartSession entity.
func (su *SessionUpdate) ClearInCart() *SessionUpdate {
	su.mutation.ClearInCart()
	return su
}

// ClearPackets clears all "packets" edges to the Packet entity.
func (su *SessionUpdate) ClearPackets() *SessionUpdate {
	su.mutation.ClearPackets()
	return su
}

// RemovePacketIDs removes the "packets" edge to Packet entities by IDs.
func (su *SessionUpdate) RemovePacketIDs(ids ...uuid.UUID) *SessionUpdate {
	su.mutation.RemovePacketIDs(ids...)
	return su
}

// RemovePackets removes "packets" edges to Packet entities.
func (su *SessionUpdate) RemovePackets(p ...*Packet) *SessionUpdate {
	ids := make([]uuid.UUID, len(p))
	for i := range p {
		ids[i] = p[i].ID
	}
	return su.RemovePacketIDs(ids...)
}

// ClearSessionFilters clears all "session_filters" edges to the SessionFilter entity.
func (su *SessionUpdate) ClearSessionFilters() *SessionUpdate {
	su.mutation.ClearSessionFilters()
	return su
}

// RemoveSessionFilterIDs removes the "session_filters" edge to SessionFilter entities by IDs.
func (su *SessionUpdate) RemoveSessionFilterIDs(ids ...uuid.UUID) *SessionUpdate {
	su.mutation.RemoveSessionFilterIDs(ids...)
	return su
}

// RemoveSessionFilters removes "session_filters" edges to SessionFilter entities.
func (su *SessionUpdate) RemoveSessionFilters(s ...*SessionFilter) *SessionUpdate {
	ids := make([]uuid.UUID, len(s))
	for i := range s {
		ids[i] = s[i].ID
	}
	return su.RemoveSessionFilterIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (su *SessionUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, su.sqlSave, su.mutation, su.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (su *SessionUpdate) SaveX(ctx context.Context) int {
	affected, err := su.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (su *SessionUpdate) Exec(ctx context.Context) error {
	_, err := su.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (su *SessionUpdate) ExecX(ctx context.Context) {
	if err := su.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (su *SessionUpdate) check() error {
	if _, ok := su.mutation.WorkspaceID(); su.mutation.WorkspaceCleared() && !ok {
		return errors.New(`ent: clearing a required unique edge "Session.workspace"`)
	}
	return nil
}

func (su *SessionUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := su.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(session.Table, session.Columns, sqlgraph.NewFieldSpec(session.FieldID, field.TypeUUID))
	if ps := su.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := su.mutation.SentAt(); ok {
		_spec.SetField(session.FieldSentAt, field.TypeTime, value)
	}
	if value, ok := su.mutation.ClientHost(); ok {
		_spec.SetField(session.FieldClientHost, field.TypeString, value)
	}
	if value, ok := su.mutation.ServerPort(); ok {
		_spec.SetField(session.FieldServerPort, field.TypeUint32, value)
	}
	if value, ok := su.mutation.AddedServerPort(); ok {
		_spec.AddField(session.FieldServerPort, field.TypeUint32, value)
	}
	if value, ok := su.mutation.TTL(); ok {
		_spec.SetField(session.FieldTTL, field.TypeUint8, value)
	}
	if value, ok := su.mutation.AddedTTL(); ok {
		_spec.AddField(session.FieldTTL, field.TypeUint8, value)
	}
	if value, ok := su.mutation.PacketsCount(); ok {
		_spec.SetField(session.FieldPacketsCount, field.TypeInt, value)
	}
	if value, ok := su.mutation.AddedPacketsCount(); ok {
		_spec.AddField(session.FieldPacketsCount, field.TypeInt, value)
	}
	if value, ok := su.mutation.ClientUserAgent(); ok {
		_spec.SetField(session.FieldClientUserAgent, field.TypeString, value)
	}
	if su.mutation.ClientUserAgentCleared() {
		_spec.ClearField(session.FieldClientUserAgent, field.TypeString)
	}
	if value, ok := su.mutation.Protocol(); ok {
		_spec.SetField(session.FieldProtocol, field.TypeString, value)
	}
	if value, ok := su.mutation.AverageResponseTime(); ok {
		_spec.SetField(session.FieldAverageResponseTime, field.TypeFloat64, value)
	}
	if value, ok := su.mutation.AddedAverageResponseTime(); ok {
		_spec.AddField(session.FieldAverageResponseTime, field.TypeFloat64, value)
	}
	if value, ok := su.mutation.RequestsNumber(); ok {
		_spec.SetField(session.FieldRequestsNumber, field.TypeInt, value)
	}
	if value, ok := su.mutation.AddedRequestsNumber(); ok {
		_spec.AddField(session.FieldRequestsNumber, field.TypeInt, value)
	}
	if su.mutation.WorkspaceCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   session.WorkspaceTable,
			Columns: []string{session.WorkspaceColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(workspace.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := su.mutation.WorkspaceIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   session.WorkspaceTable,
			Columns: []string{session.WorkspaceColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(workspace.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if su.mutation.PcapWorkspaceCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   session.PcapWorkspaceTable,
			Columns: session.PcapWorkspacePrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(pcapworkspace.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := su.mutation.RemovedPcapWorkspaceIDs(); len(nodes) > 0 && !su.mutation.PcapWorkspaceCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   session.PcapWorkspaceTable,
			Columns: session.PcapWorkspacePrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(pcapworkspace.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := su.mutation.PcapWorkspaceIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   session.PcapWorkspaceTable,
			Columns: session.PcapWorkspacePrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(pcapworkspace.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if su.mutation.InCartCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   session.InCartTable,
			Columns: []string{session.InCartColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(cartsession.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := su.mutation.InCartIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   session.InCartTable,
			Columns: []string{session.InCartColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(cartsession.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if su.mutation.PacketsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   session.PacketsTable,
			Columns: []string{session.PacketsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(packet.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := su.mutation.RemovedPacketsIDs(); len(nodes) > 0 && !su.mutation.PacketsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   session.PacketsTable,
			Columns: []string{session.PacketsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(packet.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := su.mutation.PacketsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   session.PacketsTable,
			Columns: []string{session.PacketsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(packet.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if su.mutation.SessionFiltersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   session.SessionFiltersTable,
			Columns: []string{session.SessionFiltersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(sessionfilter.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := su.mutation.RemovedSessionFiltersIDs(); len(nodes) > 0 && !su.mutation.SessionFiltersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   session.SessionFiltersTable,
			Columns: []string{session.SessionFiltersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(sessionfilter.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := su.mutation.SessionFiltersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   session.SessionFiltersTable,
			Columns: []string{session.SessionFiltersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(sessionfilter.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, su.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{session.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	su.mutation.done = true
	return n, nil
}

// SessionUpdateOne is the builder for updating a single Session entity.
type SessionUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *SessionMutation
}

// SetSentAt sets the "sent_at" field.
func (suo *SessionUpdateOne) SetSentAt(t time.Time) *SessionUpdateOne {
	suo.mutation.SetSentAt(t)
	return suo
}

// SetNillableSentAt sets the "sent_at" field if the given value is not nil.
func (suo *SessionUpdateOne) SetNillableSentAt(t *time.Time) *SessionUpdateOne {
	if t != nil {
		suo.SetSentAt(*t)
	}
	return suo
}

// SetClientHost sets the "client_host" field.
func (suo *SessionUpdateOne) SetClientHost(s string) *SessionUpdateOne {
	suo.mutation.SetClientHost(s)
	return suo
}

// SetNillableClientHost sets the "client_host" field if the given value is not nil.
func (suo *SessionUpdateOne) SetNillableClientHost(s *string) *SessionUpdateOne {
	if s != nil {
		suo.SetClientHost(*s)
	}
	return suo
}

// SetServerPort sets the "server_port" field.
func (suo *SessionUpdateOne) SetServerPort(u uint32) *SessionUpdateOne {
	suo.mutation.ResetServerPort()
	suo.mutation.SetServerPort(u)
	return suo
}

// SetNillableServerPort sets the "server_port" field if the given value is not nil.
func (suo *SessionUpdateOne) SetNillableServerPort(u *uint32) *SessionUpdateOne {
	if u != nil {
		suo.SetServerPort(*u)
	}
	return suo
}

// AddServerPort adds u to the "server_port" field.
func (suo *SessionUpdateOne) AddServerPort(u int32) *SessionUpdateOne {
	suo.mutation.AddServerPort(u)
	return suo
}

// SetTTL sets the "ttl" field.
func (suo *SessionUpdateOne) SetTTL(u uint8) *SessionUpdateOne {
	suo.mutation.ResetTTL()
	suo.mutation.SetTTL(u)
	return suo
}

// SetNillableTTL sets the "ttl" field if the given value is not nil.
func (suo *SessionUpdateOne) SetNillableTTL(u *uint8) *SessionUpdateOne {
	if u != nil {
		suo.SetTTL(*u)
	}
	return suo
}

// AddTTL adds u to the "ttl" field.
func (suo *SessionUpdateOne) AddTTL(u int8) *SessionUpdateOne {
	suo.mutation.AddTTL(u)
	return suo
}

// SetPacketsCount sets the "packets_count" field.
func (suo *SessionUpdateOne) SetPacketsCount(i int) *SessionUpdateOne {
	suo.mutation.ResetPacketsCount()
	suo.mutation.SetPacketsCount(i)
	return suo
}

// SetNillablePacketsCount sets the "packets_count" field if the given value is not nil.
func (suo *SessionUpdateOne) SetNillablePacketsCount(i *int) *SessionUpdateOne {
	if i != nil {
		suo.SetPacketsCount(*i)
	}
	return suo
}

// AddPacketsCount adds i to the "packets_count" field.
func (suo *SessionUpdateOne) AddPacketsCount(i int) *SessionUpdateOne {
	suo.mutation.AddPacketsCount(i)
	return suo
}

// SetClientUserAgent sets the "client_user_agent" field.
func (suo *SessionUpdateOne) SetClientUserAgent(s string) *SessionUpdateOne {
	suo.mutation.SetClientUserAgent(s)
	return suo
}

// SetNillableClientUserAgent sets the "client_user_agent" field if the given value is not nil.
func (suo *SessionUpdateOne) SetNillableClientUserAgent(s *string) *SessionUpdateOne {
	if s != nil {
		suo.SetClientUserAgent(*s)
	}
	return suo
}

// ClearClientUserAgent clears the value of the "client_user_agent" field.
func (suo *SessionUpdateOne) ClearClientUserAgent() *SessionUpdateOne {
	suo.mutation.ClearClientUserAgent()
	return suo
}

// SetProtocol sets the "protocol" field.
func (suo *SessionUpdateOne) SetProtocol(s string) *SessionUpdateOne {
	suo.mutation.SetProtocol(s)
	return suo
}

// SetNillableProtocol sets the "protocol" field if the given value is not nil.
func (suo *SessionUpdateOne) SetNillableProtocol(s *string) *SessionUpdateOne {
	if s != nil {
		suo.SetProtocol(*s)
	}
	return suo
}

// SetAverageResponseTime sets the "average_response_time" field.
func (suo *SessionUpdateOne) SetAverageResponseTime(f float64) *SessionUpdateOne {
	suo.mutation.ResetAverageResponseTime()
	suo.mutation.SetAverageResponseTime(f)
	return suo
}

// SetNillableAverageResponseTime sets the "average_response_time" field if the given value is not nil.
func (suo *SessionUpdateOne) SetNillableAverageResponseTime(f *float64) *SessionUpdateOne {
	if f != nil {
		suo.SetAverageResponseTime(*f)
	}
	return suo
}

// AddAverageResponseTime adds f to the "average_response_time" field.
func (suo *SessionUpdateOne) AddAverageResponseTime(f float64) *SessionUpdateOne {
	suo.mutation.AddAverageResponseTime(f)
	return suo
}

// SetRequestsNumber sets the "requests_number" field.
func (suo *SessionUpdateOne) SetRequestsNumber(i int) *SessionUpdateOne {
	suo.mutation.ResetRequestsNumber()
	suo.mutation.SetRequestsNumber(i)
	return suo
}

// SetNillableRequestsNumber sets the "requests_number" field if the given value is not nil.
func (suo *SessionUpdateOne) SetNillableRequestsNumber(i *int) *SessionUpdateOne {
	if i != nil {
		suo.SetRequestsNumber(*i)
	}
	return suo
}

// AddRequestsNumber adds i to the "requests_number" field.
func (suo *SessionUpdateOne) AddRequestsNumber(i int) *SessionUpdateOne {
	suo.mutation.AddRequestsNumber(i)
	return suo
}

// SetWorkspaceID sets the "workspace" edge to the Workspace entity by ID.
func (suo *SessionUpdateOne) SetWorkspaceID(id uuid.UUID) *SessionUpdateOne {
	suo.mutation.SetWorkspaceID(id)
	return suo
}

// SetWorkspace sets the "workspace" edge to the Workspace entity.
func (suo *SessionUpdateOne) SetWorkspace(w *Workspace) *SessionUpdateOne {
	return suo.SetWorkspaceID(w.ID)
}

// AddPcapWorkspaceIDs adds the "pcap_workspace" edge to the PcapWorkspace entity by IDs.
func (suo *SessionUpdateOne) AddPcapWorkspaceIDs(ids ...uuid.UUID) *SessionUpdateOne {
	suo.mutation.AddPcapWorkspaceIDs(ids...)
	return suo
}

// AddPcapWorkspace adds the "pcap_workspace" edges to the PcapWorkspace entity.
func (suo *SessionUpdateOne) AddPcapWorkspace(p ...*PcapWorkspace) *SessionUpdateOne {
	ids := make([]uuid.UUID, len(p))
	for i := range p {
		ids[i] = p[i].ID
	}
	return suo.AddPcapWorkspaceIDs(ids...)
}

// SetInCartID sets the "in_cart" edge to the CartSession entity by ID.
func (suo *SessionUpdateOne) SetInCartID(id uuid.UUID) *SessionUpdateOne {
	suo.mutation.SetInCartID(id)
	return suo
}

// SetNillableInCartID sets the "in_cart" edge to the CartSession entity by ID if the given value is not nil.
func (suo *SessionUpdateOne) SetNillableInCartID(id *uuid.UUID) *SessionUpdateOne {
	if id != nil {
		suo = suo.SetInCartID(*id)
	}
	return suo
}

// SetInCart sets the "in_cart" edge to the CartSession entity.
func (suo *SessionUpdateOne) SetInCart(c *CartSession) *SessionUpdateOne {
	return suo.SetInCartID(c.ID)
}

// AddPacketIDs adds the "packets" edge to the Packet entity by IDs.
func (suo *SessionUpdateOne) AddPacketIDs(ids ...uuid.UUID) *SessionUpdateOne {
	suo.mutation.AddPacketIDs(ids...)
	return suo
}

// AddPackets adds the "packets" edges to the Packet entity.
func (suo *SessionUpdateOne) AddPackets(p ...*Packet) *SessionUpdateOne {
	ids := make([]uuid.UUID, len(p))
	for i := range p {
		ids[i] = p[i].ID
	}
	return suo.AddPacketIDs(ids...)
}

// AddSessionFilterIDs adds the "session_filters" edge to the SessionFilter entity by IDs.
func (suo *SessionUpdateOne) AddSessionFilterIDs(ids ...uuid.UUID) *SessionUpdateOne {
	suo.mutation.AddSessionFilterIDs(ids...)
	return suo
}

// AddSessionFilters adds the "session_filters" edges to the SessionFilter entity.
func (suo *SessionUpdateOne) AddSessionFilters(s ...*SessionFilter) *SessionUpdateOne {
	ids := make([]uuid.UUID, len(s))
	for i := range s {
		ids[i] = s[i].ID
	}
	return suo.AddSessionFilterIDs(ids...)
}

// Mutation returns the SessionMutation object of the builder.
func (suo *SessionUpdateOne) Mutation() *SessionMutation {
	return suo.mutation
}

// ClearWorkspace clears the "workspace" edge to the Workspace entity.
func (suo *SessionUpdateOne) ClearWorkspace() *SessionUpdateOne {
	suo.mutation.ClearWorkspace()
	return suo
}

// ClearPcapWorkspace clears all "pcap_workspace" edges to the PcapWorkspace entity.
func (suo *SessionUpdateOne) ClearPcapWorkspace() *SessionUpdateOne {
	suo.mutation.ClearPcapWorkspace()
	return suo
}

// RemovePcapWorkspaceIDs removes the "pcap_workspace" edge to PcapWorkspace entities by IDs.
func (suo *SessionUpdateOne) RemovePcapWorkspaceIDs(ids ...uuid.UUID) *SessionUpdateOne {
	suo.mutation.RemovePcapWorkspaceIDs(ids...)
	return suo
}

// RemovePcapWorkspace removes "pcap_workspace" edges to PcapWorkspace entities.
func (suo *SessionUpdateOne) RemovePcapWorkspace(p ...*PcapWorkspace) *SessionUpdateOne {
	ids := make([]uuid.UUID, len(p))
	for i := range p {
		ids[i] = p[i].ID
	}
	return suo.RemovePcapWorkspaceIDs(ids...)
}

// ClearInCart clears the "in_cart" edge to the CartSession entity.
func (suo *SessionUpdateOne) ClearInCart() *SessionUpdateOne {
	suo.mutation.ClearInCart()
	return suo
}

// ClearPackets clears all "packets" edges to the Packet entity.
func (suo *SessionUpdateOne) ClearPackets() *SessionUpdateOne {
	suo.mutation.ClearPackets()
	return suo
}

// RemovePacketIDs removes the "packets" edge to Packet entities by IDs.
func (suo *SessionUpdateOne) RemovePacketIDs(ids ...uuid.UUID) *SessionUpdateOne {
	suo.mutation.RemovePacketIDs(ids...)
	return suo
}

// RemovePackets removes "packets" edges to Packet entities.
func (suo *SessionUpdateOne) RemovePackets(p ...*Packet) *SessionUpdateOne {
	ids := make([]uuid.UUID, len(p))
	for i := range p {
		ids[i] = p[i].ID
	}
	return suo.RemovePacketIDs(ids...)
}

// ClearSessionFilters clears all "session_filters" edges to the SessionFilter entity.
func (suo *SessionUpdateOne) ClearSessionFilters() *SessionUpdateOne {
	suo.mutation.ClearSessionFilters()
	return suo
}

// RemoveSessionFilterIDs removes the "session_filters" edge to SessionFilter entities by IDs.
func (suo *SessionUpdateOne) RemoveSessionFilterIDs(ids ...uuid.UUID) *SessionUpdateOne {
	suo.mutation.RemoveSessionFilterIDs(ids...)
	return suo
}

// RemoveSessionFilters removes "session_filters" edges to SessionFilter entities.
func (suo *SessionUpdateOne) RemoveSessionFilters(s ...*SessionFilter) *SessionUpdateOne {
	ids := make([]uuid.UUID, len(s))
	for i := range s {
		ids[i] = s[i].ID
	}
	return suo.RemoveSessionFilterIDs(ids...)
}

// Where appends a list predicates to the SessionUpdate builder.
func (suo *SessionUpdateOne) Where(ps ...predicate.Session) *SessionUpdateOne {
	suo.mutation.Where(ps...)
	return suo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (suo *SessionUpdateOne) Select(field string, fields ...string) *SessionUpdateOne {
	suo.fields = append([]string{field}, fields...)
	return suo
}

// Save executes the query and returns the updated Session entity.
func (suo *SessionUpdateOne) Save(ctx context.Context) (*Session, error) {
	return withHooks(ctx, suo.sqlSave, suo.mutation, suo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (suo *SessionUpdateOne) SaveX(ctx context.Context) *Session {
	node, err := suo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (suo *SessionUpdateOne) Exec(ctx context.Context) error {
	_, err := suo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (suo *SessionUpdateOne) ExecX(ctx context.Context) {
	if err := suo.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (suo *SessionUpdateOne) check() error {
	if _, ok := suo.mutation.WorkspaceID(); suo.mutation.WorkspaceCleared() && !ok {
		return errors.New(`ent: clearing a required unique edge "Session.workspace"`)
	}
	return nil
}

func (suo *SessionUpdateOne) sqlSave(ctx context.Context) (_node *Session, err error) {
	if err := suo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(session.Table, session.Columns, sqlgraph.NewFieldSpec(session.FieldID, field.TypeUUID))
	id, ok := suo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Session.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := suo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, session.FieldID)
		for _, f := range fields {
			if !session.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != session.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := suo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := suo.mutation.SentAt(); ok {
		_spec.SetField(session.FieldSentAt, field.TypeTime, value)
	}
	if value, ok := suo.mutation.ClientHost(); ok {
		_spec.SetField(session.FieldClientHost, field.TypeString, value)
	}
	if value, ok := suo.mutation.ServerPort(); ok {
		_spec.SetField(session.FieldServerPort, field.TypeUint32, value)
	}
	if value, ok := suo.mutation.AddedServerPort(); ok {
		_spec.AddField(session.FieldServerPort, field.TypeUint32, value)
	}
	if value, ok := suo.mutation.TTL(); ok {
		_spec.SetField(session.FieldTTL, field.TypeUint8, value)
	}
	if value, ok := suo.mutation.AddedTTL(); ok {
		_spec.AddField(session.FieldTTL, field.TypeUint8, value)
	}
	if value, ok := suo.mutation.PacketsCount(); ok {
		_spec.SetField(session.FieldPacketsCount, field.TypeInt, value)
	}
	if value, ok := suo.mutation.AddedPacketsCount(); ok {
		_spec.AddField(session.FieldPacketsCount, field.TypeInt, value)
	}
	if value, ok := suo.mutation.ClientUserAgent(); ok {
		_spec.SetField(session.FieldClientUserAgent, field.TypeString, value)
	}
	if suo.mutation.ClientUserAgentCleared() {
		_spec.ClearField(session.FieldClientUserAgent, field.TypeString)
	}
	if value, ok := suo.mutation.Protocol(); ok {
		_spec.SetField(session.FieldProtocol, field.TypeString, value)
	}
	if value, ok := suo.mutation.AverageResponseTime(); ok {
		_spec.SetField(session.FieldAverageResponseTime, field.TypeFloat64, value)
	}
	if value, ok := suo.mutation.AddedAverageResponseTime(); ok {
		_spec.AddField(session.FieldAverageResponseTime, field.TypeFloat64, value)
	}
	if value, ok := suo.mutation.RequestsNumber(); ok {
		_spec.SetField(session.FieldRequestsNumber, field.TypeInt, value)
	}
	if value, ok := suo.mutation.AddedRequestsNumber(); ok {
		_spec.AddField(session.FieldRequestsNumber, field.TypeInt, value)
	}
	if suo.mutation.WorkspaceCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   session.WorkspaceTable,
			Columns: []string{session.WorkspaceColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(workspace.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := suo.mutation.WorkspaceIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   session.WorkspaceTable,
			Columns: []string{session.WorkspaceColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(workspace.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if suo.mutation.PcapWorkspaceCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   session.PcapWorkspaceTable,
			Columns: session.PcapWorkspacePrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(pcapworkspace.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := suo.mutation.RemovedPcapWorkspaceIDs(); len(nodes) > 0 && !suo.mutation.PcapWorkspaceCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   session.PcapWorkspaceTable,
			Columns: session.PcapWorkspacePrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(pcapworkspace.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := suo.mutation.PcapWorkspaceIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   session.PcapWorkspaceTable,
			Columns: session.PcapWorkspacePrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(pcapworkspace.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if suo.mutation.InCartCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   session.InCartTable,
			Columns: []string{session.InCartColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(cartsession.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := suo.mutation.InCartIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   session.InCartTable,
			Columns: []string{session.InCartColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(cartsession.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if suo.mutation.PacketsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   session.PacketsTable,
			Columns: []string{session.PacketsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(packet.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := suo.mutation.RemovedPacketsIDs(); len(nodes) > 0 && !suo.mutation.PacketsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   session.PacketsTable,
			Columns: []string{session.PacketsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(packet.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := suo.mutation.PacketsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   session.PacketsTable,
			Columns: []string{session.PacketsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(packet.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if suo.mutation.SessionFiltersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   session.SessionFiltersTable,
			Columns: []string{session.SessionFiltersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(sessionfilter.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := suo.mutation.RemovedSessionFiltersIDs(); len(nodes) > 0 && !suo.mutation.SessionFiltersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   session.SessionFiltersTable,
			Columns: []string{session.SessionFiltersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(sessionfilter.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := suo.mutation.SessionFiltersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   session.SessionFiltersTable,
			Columns: []string{session.SessionFiltersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(sessionfilter.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Session{config: suo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, suo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{session.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	suo.mutation.done = true
	return _node, nil
}
