// Code generated by ent, DO NOT EDIT.

package ent

import (
	"altron/core/repositories/ent/cartsession"
	"altron/core/repositories/ent/packet"
	"altron/core/repositories/ent/pcapworkspace"
	"altron/core/repositories/ent/session"
	"altron/core/repositories/ent/sessionfilter"
	"altron/core/repositories/ent/workspace"
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// SessionCreate is the builder for creating a Session entity.
type SessionCreate struct {
	config
	mutation *SessionMutation
	hooks    []Hook
}

// SetSentAt sets the "sent_at" field.
func (sc *SessionCreate) SetSentAt(t time.Time) *SessionCreate {
	sc.mutation.SetSentAt(t)
	return sc
}

// SetNillableSentAt sets the "sent_at" field if the given value is not nil.
func (sc *SessionCreate) SetNillableSentAt(t *time.Time) *SessionCreate {
	if t != nil {
		sc.SetSentAt(*t)
	}
	return sc
}

// SetClientHost sets the "client_host" field.
func (sc *SessionCreate) SetClientHost(s string) *SessionCreate {
	sc.mutation.SetClientHost(s)
	return sc
}

// SetServerPort sets the "server_port" field.
func (sc *SessionCreate) SetServerPort(u uint32) *SessionCreate {
	sc.mutation.SetServerPort(u)
	return sc
}

// SetTTL sets the "ttl" field.
func (sc *SessionCreate) SetTTL(u uint8) *SessionCreate {
	sc.mutation.SetTTL(u)
	return sc
}

// SetPacketsCount sets the "packets_count" field.
func (sc *SessionCreate) SetPacketsCount(i int) *SessionCreate {
	sc.mutation.SetPacketsCount(i)
	return sc
}

// SetClientUserAgent sets the "client_user_agent" field.
func (sc *SessionCreate) SetClientUserAgent(s string) *SessionCreate {
	sc.mutation.SetClientUserAgent(s)
	return sc
}

// SetNillableClientUserAgent sets the "client_user_agent" field if the given value is not nil.
func (sc *SessionCreate) SetNillableClientUserAgent(s *string) *SessionCreate {
	if s != nil {
		sc.SetClientUserAgent(*s)
	}
	return sc
}

// SetProtocol sets the "protocol" field.
func (sc *SessionCreate) SetProtocol(s string) *SessionCreate {
	sc.mutation.SetProtocol(s)
	return sc
}

// SetAverageResponseTime sets the "average_response_time" field.
func (sc *SessionCreate) SetAverageResponseTime(f float64) *SessionCreate {
	sc.mutation.SetAverageResponseTime(f)
	return sc
}

// SetRequestsNumber sets the "requests_number" field.
func (sc *SessionCreate) SetRequestsNumber(i int) *SessionCreate {
	sc.mutation.SetRequestsNumber(i)
	return sc
}

// SetID sets the "id" field.
func (sc *SessionCreate) SetID(u uuid.UUID) *SessionCreate {
	sc.mutation.SetID(u)
	return sc
}

// SetWorkspaceID sets the "workspace" edge to the Workspace entity by ID.
func (sc *SessionCreate) SetWorkspaceID(id uuid.UUID) *SessionCreate {
	sc.mutation.SetWorkspaceID(id)
	return sc
}

// SetWorkspace sets the "workspace" edge to the Workspace entity.
func (sc *SessionCreate) SetWorkspace(w *Workspace) *SessionCreate {
	return sc.SetWorkspaceID(w.ID)
}

// AddPcapWorkspaceIDs adds the "pcap_workspace" edge to the PcapWorkspace entity by IDs.
func (sc *SessionCreate) AddPcapWorkspaceIDs(ids ...uuid.UUID) *SessionCreate {
	sc.mutation.AddPcapWorkspaceIDs(ids...)
	return sc
}

// AddPcapWorkspace adds the "pcap_workspace" edges to the PcapWorkspace entity.
func (sc *SessionCreate) AddPcapWorkspace(p ...*PcapWorkspace) *SessionCreate {
	ids := make([]uuid.UUID, len(p))
	for i := range p {
		ids[i] = p[i].ID
	}
	return sc.AddPcapWorkspaceIDs(ids...)
}

// SetInCartID sets the "in_cart" edge to the CartSession entity by ID.
func (sc *SessionCreate) SetInCartID(id uuid.UUID) *SessionCreate {
	sc.mutation.SetInCartID(id)
	return sc
}

// SetNillableInCartID sets the "in_cart" edge to the CartSession entity by ID if the given value is not nil.
func (sc *SessionCreate) SetNillableInCartID(id *uuid.UUID) *SessionCreate {
	if id != nil {
		sc = sc.SetInCartID(*id)
	}
	return sc
}

// SetInCart sets the "in_cart" edge to the CartSession entity.
func (sc *SessionCreate) SetInCart(c *CartSession) *SessionCreate {
	return sc.SetInCartID(c.ID)
}

// AddPacketIDs adds the "packets" edge to the Packet entity by IDs.
func (sc *SessionCreate) AddPacketIDs(ids ...uuid.UUID) *SessionCreate {
	sc.mutation.AddPacketIDs(ids...)
	return sc
}

// AddPackets adds the "packets" edges to the Packet entity.
func (sc *SessionCreate) AddPackets(p ...*Packet) *SessionCreate {
	ids := make([]uuid.UUID, len(p))
	for i := range p {
		ids[i] = p[i].ID
	}
	return sc.AddPacketIDs(ids...)
}

// AddSessionFilterIDs adds the "session_filters" edge to the SessionFilter entity by IDs.
func (sc *SessionCreate) AddSessionFilterIDs(ids ...uuid.UUID) *SessionCreate {
	sc.mutation.AddSessionFilterIDs(ids...)
	return sc
}

// AddSessionFilters adds the "session_filters" edges to the SessionFilter entity.
func (sc *SessionCreate) AddSessionFilters(s ...*SessionFilter) *SessionCreate {
	ids := make([]uuid.UUID, len(s))
	for i := range s {
		ids[i] = s[i].ID
	}
	return sc.AddSessionFilterIDs(ids...)
}

// Mutation returns the SessionMutation object of the builder.
func (sc *SessionCreate) Mutation() *SessionMutation {
	return sc.mutation
}

// Save creates the Session in the database.
func (sc *SessionCreate) Save(ctx context.Context) (*Session, error) {
	sc.defaults()
	return withHooks(ctx, sc.sqlSave, sc.mutation, sc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (sc *SessionCreate) SaveX(ctx context.Context) *Session {
	v, err := sc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (sc *SessionCreate) Exec(ctx context.Context) error {
	_, err := sc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (sc *SessionCreate) ExecX(ctx context.Context) {
	if err := sc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (sc *SessionCreate) defaults() {
	if _, ok := sc.mutation.SentAt(); !ok {
		v := session.DefaultSentAt
		sc.mutation.SetSentAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (sc *SessionCreate) check() error {
	if _, ok := sc.mutation.SentAt(); !ok {
		return &ValidationError{Name: "sent_at", err: errors.New(`ent: missing required field "Session.sent_at"`)}
	}
	if _, ok := sc.mutation.ClientHost(); !ok {
		return &ValidationError{Name: "client_host", err: errors.New(`ent: missing required field "Session.client_host"`)}
	}
	if _, ok := sc.mutation.ServerPort(); !ok {
		return &ValidationError{Name: "server_port", err: errors.New(`ent: missing required field "Session.server_port"`)}
	}
	if _, ok := sc.mutation.TTL(); !ok {
		return &ValidationError{Name: "ttl", err: errors.New(`ent: missing required field "Session.ttl"`)}
	}
	if _, ok := sc.mutation.PacketsCount(); !ok {
		return &ValidationError{Name: "packets_count", err: errors.New(`ent: missing required field "Session.packets_count"`)}
	}
	if _, ok := sc.mutation.Protocol(); !ok {
		return &ValidationError{Name: "protocol", err: errors.New(`ent: missing required field "Session.protocol"`)}
	}
	if _, ok := sc.mutation.AverageResponseTime(); !ok {
		return &ValidationError{Name: "average_response_time", err: errors.New(`ent: missing required field "Session.average_response_time"`)}
	}
	if _, ok := sc.mutation.RequestsNumber(); !ok {
		return &ValidationError{Name: "requests_number", err: errors.New(`ent: missing required field "Session.requests_number"`)}
	}
	if _, ok := sc.mutation.WorkspaceID(); !ok {
		return &ValidationError{Name: "workspace", err: errors.New(`ent: missing required edge "Session.workspace"`)}
	}
	return nil
}

func (sc *SessionCreate) sqlSave(ctx context.Context) (*Session, error) {
	if err := sc.check(); err != nil {
		return nil, err
	}
	_node, _spec := sc.createSpec()
	if err := sqlgraph.CreateNode(ctx, sc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	sc.mutation.id = &_node.ID
	sc.mutation.done = true
	return _node, nil
}

func (sc *SessionCreate) createSpec() (*Session, *sqlgraph.CreateSpec) {
	var (
		_node = &Session{config: sc.config}
		_spec = sqlgraph.NewCreateSpec(session.Table, sqlgraph.NewFieldSpec(session.FieldID, field.TypeUUID))
	)
	if id, ok := sc.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := sc.mutation.SentAt(); ok {
		_spec.SetField(session.FieldSentAt, field.TypeTime, value)
		_node.SentAt = value
	}
	if value, ok := sc.mutation.ClientHost(); ok {
		_spec.SetField(session.FieldClientHost, field.TypeString, value)
		_node.ClientHost = value
	}
	if value, ok := sc.mutation.ServerPort(); ok {
		_spec.SetField(session.FieldServerPort, field.TypeUint32, value)
		_node.ServerPort = value
	}
	if value, ok := sc.mutation.TTL(); ok {
		_spec.SetField(session.FieldTTL, field.TypeUint8, value)
		_node.TTL = value
	}
	if value, ok := sc.mutation.PacketsCount(); ok {
		_spec.SetField(session.FieldPacketsCount, field.TypeInt, value)
		_node.PacketsCount = value
	}
	if value, ok := sc.mutation.ClientUserAgent(); ok {
		_spec.SetField(session.FieldClientUserAgent, field.TypeString, value)
		_node.ClientUserAgent = value
	}
	if value, ok := sc.mutation.Protocol(); ok {
		_spec.SetField(session.FieldProtocol, field.TypeString, value)
		_node.Protocol = value
	}
	if value, ok := sc.mutation.AverageResponseTime(); ok {
		_spec.SetField(session.FieldAverageResponseTime, field.TypeFloat64, value)
		_node.AverageResponseTime = value
	}
	if value, ok := sc.mutation.RequestsNumber(); ok {
		_spec.SetField(session.FieldRequestsNumber, field.TypeInt, value)
		_node.RequestsNumber = value
	}
	if nodes := sc.mutation.WorkspaceIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   session.WorkspaceTable,
			Columns: []string{session.WorkspaceColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(workspace.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.workspace_sessions = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := sc.mutation.PcapWorkspaceIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   session.PcapWorkspaceTable,
			Columns: session.PcapWorkspacePrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(pcapworkspace.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := sc.mutation.InCartIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   session.InCartTable,
			Columns: []string{session.InCartColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(cartsession.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := sc.mutation.PacketsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   session.PacketsTable,
			Columns: []string{session.PacketsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(packet.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := sc.mutation.SessionFiltersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   session.SessionFiltersTable,
			Columns: []string{session.SessionFiltersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(sessionfilter.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// SessionCreateBulk is the builder for creating many Session entities in bulk.
type SessionCreateBulk struct {
	config
	err      error
	builders []*SessionCreate
}

// Save creates the Session entities in the database.
func (scb *SessionCreateBulk) Save(ctx context.Context) ([]*Session, error) {
	if scb.err != nil {
		return nil, scb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(scb.builders))
	nodes := make([]*Session, len(scb.builders))
	mutators := make([]Mutator, len(scb.builders))
	for i := range scb.builders {
		func(i int, root context.Context) {
			builder := scb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*SessionMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, scb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, scb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, scb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (scb *SessionCreateBulk) SaveX(ctx context.Context) []*Session {
	v, err := scb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (scb *SessionCreateBulk) Exec(ctx context.Context) error {
	_, err := scb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (scb *SessionCreateBulk) ExecX(ctx context.Context) {
	if err := scb.Exec(ctx); err != nil {
		panic(err)
	}
}
