// Code generated by ent, DO NOT EDIT.

package ent

import (
	"altron/core/repositories/ent/predicate"
	"altron/core/repositories/ent/sessionfilter"
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// SessionFilterDelete is the builder for deleting a SessionFilter entity.
type SessionFilterDelete struct {
	config
	hooks    []Hook
	mutation *SessionFilterMutation
}

// Where appends a list predicates to the SessionFilterDelete builder.
func (sfd *SessionFilterDelete) Where(ps ...predicate.SessionFilter) *SessionFilterDelete {
	sfd.mutation.Where(ps...)
	return sfd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (sfd *SessionFilterDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, sfd.sqlExec, sfd.mutation, sfd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (sfd *SessionFilterDelete) ExecX(ctx context.Context) int {
	n, err := sfd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (sfd *SessionFilterDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(sessionfilter.Table, sqlgraph.NewFieldSpec(sessionfilter.FieldID, field.TypeUUID))
	if ps := sfd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, sfd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	sfd.mutation.done = true
	return affected, err
}

// SessionFilterDeleteOne is the builder for deleting a single SessionFilter entity.
type SessionFilterDeleteOne struct {
	sfd *SessionFilterDelete
}

// Where appends a list predicates to the SessionFilterDelete builder.
func (sfdo *SessionFilterDeleteOne) Where(ps ...predicate.SessionFilter) *SessionFilterDeleteOne {
	sfdo.sfd.mutation.Where(ps...)
	return sfdo
}

// Exec executes the deletion query.
func (sfdo *SessionFilterDeleteOne) Exec(ctx context.Context) error {
	n, err := sfdo.sfd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{sessionfilter.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (sfdo *SessionFilterDeleteOne) ExecX(ctx context.Context) {
	if err := sfdo.Exec(ctx); err != nil {
		panic(err)
	}
}
