// Code generated by ent, DO NOT EDIT.

package ent

import (
	"altron/core/repositories/ent/filter"
	"altron/core/repositories/ent/matchedpacket"
	"altron/core/repositories/ent/session"
	"altron/core/repositories/ent/sessionfilter"
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// SessionFilterCreate is the builder for creating a SessionFilter entity.
type SessionFilterCreate struct {
	config
	mutation *SessionFilterMutation
	hooks    []Hook
}

// SetSessionID sets the "session_id" field.
func (sfc *SessionFilterCreate) SetSessionID(u uuid.UUID) *SessionFilterCreate {
	sfc.mutation.SetSessionID(u)
	return sfc
}

// SetFilterID sets the "filter_id" field.
func (sfc *SessionFilterCreate) SetFilterID(u uuid.UUID) *SessionFilterCreate {
	sfc.mutation.SetFilterID(u)
	return sfc
}

// SetMatchesCount sets the "matches_count" field.
func (sfc *SessionFilterCreate) SetMatchesCount(i int) *SessionFilterCreate {
	sfc.mutation.SetMatchesCount(i)
	return sfc
}

// SetNillableMatchesCount sets the "matches_count" field if the given value is not nil.
func (sfc *SessionFilterCreate) SetNillableMatchesCount(i *int) *SessionFilterCreate {
	if i != nil {
		sfc.SetMatchesCount(*i)
	}
	return sfc
}

// SetID sets the "id" field.
func (sfc *SessionFilterCreate) SetID(u uuid.UUID) *SessionFilterCreate {
	sfc.mutation.SetID(u)
	return sfc
}

// SetNillableID sets the "id" field if the given value is not nil.
func (sfc *SessionFilterCreate) SetNillableID(u *uuid.UUID) *SessionFilterCreate {
	if u != nil {
		sfc.SetID(*u)
	}
	return sfc
}

// SetSession sets the "session" edge to the Session entity.
func (sfc *SessionFilterCreate) SetSession(s *Session) *SessionFilterCreate {
	return sfc.SetSessionID(s.ID)
}

// SetFilter sets the "filter" edge to the Filter entity.
func (sfc *SessionFilterCreate) SetFilter(f *Filter) *SessionFilterCreate {
	return sfc.SetFilterID(f.ID)
}

// AddMatchedPacketIDs adds the "matched_packets" edge to the MatchedPacket entity by IDs.
func (sfc *SessionFilterCreate) AddMatchedPacketIDs(ids ...uuid.UUID) *SessionFilterCreate {
	sfc.mutation.AddMatchedPacketIDs(ids...)
	return sfc
}

// AddMatchedPackets adds the "matched_packets" edges to the MatchedPacket entity.
func (sfc *SessionFilterCreate) AddMatchedPackets(m ...*MatchedPacket) *SessionFilterCreate {
	ids := make([]uuid.UUID, len(m))
	for i := range m {
		ids[i] = m[i].ID
	}
	return sfc.AddMatchedPacketIDs(ids...)
}

// Mutation returns the SessionFilterMutation object of the builder.
func (sfc *SessionFilterCreate) Mutation() *SessionFilterMutation {
	return sfc.mutation
}

// Save creates the SessionFilter in the database.
func (sfc *SessionFilterCreate) Save(ctx context.Context) (*SessionFilter, error) {
	sfc.defaults()
	return withHooks(ctx, sfc.sqlSave, sfc.mutation, sfc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (sfc *SessionFilterCreate) SaveX(ctx context.Context) *SessionFilter {
	v, err := sfc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (sfc *SessionFilterCreate) Exec(ctx context.Context) error {
	_, err := sfc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (sfc *SessionFilterCreate) ExecX(ctx context.Context) {
	if err := sfc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (sfc *SessionFilterCreate) defaults() {
	if _, ok := sfc.mutation.MatchesCount(); !ok {
		v := sessionfilter.DefaultMatchesCount
		sfc.mutation.SetMatchesCount(v)
	}
	if _, ok := sfc.mutation.ID(); !ok {
		v := sessionfilter.DefaultID()
		sfc.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (sfc *SessionFilterCreate) check() error {
	if _, ok := sfc.mutation.SessionID(); !ok {
		return &ValidationError{Name: "session_id", err: errors.New(`ent: missing required field "SessionFilter.session_id"`)}
	}
	if _, ok := sfc.mutation.FilterID(); !ok {
		return &ValidationError{Name: "filter_id", err: errors.New(`ent: missing required field "SessionFilter.filter_id"`)}
	}
	if _, ok := sfc.mutation.MatchesCount(); !ok {
		return &ValidationError{Name: "matches_count", err: errors.New(`ent: missing required field "SessionFilter.matches_count"`)}
	}
	if _, ok := sfc.mutation.SessionID(); !ok {
		return &ValidationError{Name: "session", err: errors.New(`ent: missing required edge "SessionFilter.session"`)}
	}
	if _, ok := sfc.mutation.FilterID(); !ok {
		return &ValidationError{Name: "filter", err: errors.New(`ent: missing required edge "SessionFilter.filter"`)}
	}
	return nil
}

func (sfc *SessionFilterCreate) sqlSave(ctx context.Context) (*SessionFilter, error) {
	if err := sfc.check(); err != nil {
		return nil, err
	}
	_node, _spec := sfc.createSpec()
	if err := sqlgraph.CreateNode(ctx, sfc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	sfc.mutation.id = &_node.ID
	sfc.mutation.done = true
	return _node, nil
}

func (sfc *SessionFilterCreate) createSpec() (*SessionFilter, *sqlgraph.CreateSpec) {
	var (
		_node = &SessionFilter{config: sfc.config}
		_spec = sqlgraph.NewCreateSpec(sessionfilter.Table, sqlgraph.NewFieldSpec(sessionfilter.FieldID, field.TypeUUID))
	)
	if id, ok := sfc.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := sfc.mutation.MatchesCount(); ok {
		_spec.SetField(sessionfilter.FieldMatchesCount, field.TypeInt, value)
		_node.MatchesCount = value
	}
	if nodes := sfc.mutation.SessionIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   sessionfilter.SessionTable,
			Columns: []string{sessionfilter.SessionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(session.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.SessionID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := sfc.mutation.FilterIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   sessionfilter.FilterTable,
			Columns: []string{sessionfilter.FilterColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(filter.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.FilterID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := sfc.mutation.MatchedPacketsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   sessionfilter.MatchedPacketsTable,
			Columns: []string{sessionfilter.MatchedPacketsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(matchedpacket.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// SessionFilterCreateBulk is the builder for creating many SessionFilter entities in bulk.
type SessionFilterCreateBulk struct {
	config
	err      error
	builders []*SessionFilterCreate
}

// Save creates the SessionFilter entities in the database.
func (sfcb *SessionFilterCreateBulk) Save(ctx context.Context) ([]*SessionFilter, error) {
	if sfcb.err != nil {
		return nil, sfcb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(sfcb.builders))
	nodes := make([]*SessionFilter, len(sfcb.builders))
	mutators := make([]Mutator, len(sfcb.builders))
	for i := range sfcb.builders {
		func(i int, root context.Context) {
			builder := sfcb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*SessionFilterMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, sfcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, sfcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, sfcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (sfcb *SessionFilterCreateBulk) SaveX(ctx context.Context) []*SessionFilter {
	v, err := sfcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (sfcb *SessionFilterCreateBulk) Exec(ctx context.Context) error {
	_, err := sfcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (sfcb *SessionFilterCreateBulk) ExecX(ctx context.Context) {
	if err := sfcb.Exec(ctx); err != nil {
		panic(err)
	}
}
