// Code generated by ent, DO NOT EDIT.

package ent

import (
	"altron/core/repositories/ent/service"
	"altron/core/repositories/ent/workspace"
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
)

// Workspace is the model entity for the Workspace schema.
type Workspace struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// Status holds the value of the "status" field.
	Status workspace.Status `json:"status,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the WorkspaceQuery when eager-loading is set.
	Edges              WorkspaceEdges `json:"edges"`
	service_workspaces *uuid.UUID
	selectValues       sql.SelectValues
}

// WorkspaceEdges holds the relations/edges for other nodes in the graph.
type WorkspaceEdges struct {
	// Sessions holds the value of the sessions edge.
	Sessions []*Session `json:"sessions,omitempty"`
	// Service holds the value of the service edge.
	Service *Service `json:"service,omitempty"`
	// AnalyzerPayloads holds the value of the analyzer_payloads edge.
	AnalyzerPayloads []*AnalyzerPayload `json:"analyzer_payloads,omitempty"`
	// CartSessions holds the value of the cart_sessions edge.
	CartSessions []*CartSession `json:"cart_sessions,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [4]bool
}

// SessionsOrErr returns the Sessions value or an error if the edge
// was not loaded in eager-loading.
func (e WorkspaceEdges) SessionsOrErr() ([]*Session, error) {
	if e.loadedTypes[0] {
		return e.Sessions, nil
	}
	return nil, &NotLoadedError{edge: "sessions"}
}

// ServiceOrErr returns the Service value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e WorkspaceEdges) ServiceOrErr() (*Service, error) {
	if e.loadedTypes[1] {
		if e.Service == nil {
			// Edge was loaded but was not found.
			return nil, &NotFoundError{label: service.Label}
		}
		return e.Service, nil
	}
	return nil, &NotLoadedError{edge: "service"}
}

// AnalyzerPayloadsOrErr returns the AnalyzerPayloads value or an error if the edge
// was not loaded in eager-loading.
func (e WorkspaceEdges) AnalyzerPayloadsOrErr() ([]*AnalyzerPayload, error) {
	if e.loadedTypes[2] {
		return e.AnalyzerPayloads, nil
	}
	return nil, &NotLoadedError{edge: "analyzer_payloads"}
}

// CartSessionsOrErr returns the CartSessions value or an error if the edge
// was not loaded in eager-loading.
func (e WorkspaceEdges) CartSessionsOrErr() ([]*CartSession, error) {
	if e.loadedTypes[3] {
		return e.CartSessions, nil
	}
	return nil, &NotLoadedError{edge: "cart_sessions"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Workspace) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case workspace.FieldName, workspace.FieldStatus:
			values[i] = new(sql.NullString)
		case workspace.FieldID:
			values[i] = new(uuid.UUID)
		case workspace.ForeignKeys[0]: // service_workspaces
			values[i] = &sql.NullScanner{S: new(uuid.UUID)}
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Workspace fields.
func (w *Workspace) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case workspace.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				w.ID = *value
			}
		case workspace.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				w.Name = value.String
			}
		case workspace.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				w.Status = workspace.Status(value.String)
			}
		case workspace.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field service_workspaces", values[i])
			} else if value.Valid {
				w.service_workspaces = new(uuid.UUID)
				*w.service_workspaces = *value.S.(*uuid.UUID)
			}
		default:
			w.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Workspace.
// This includes values selected through modifiers, order, etc.
func (w *Workspace) Value(name string) (ent.Value, error) {
	return w.selectValues.Get(name)
}

// QuerySessions queries the "sessions" edge of the Workspace entity.
func (w *Workspace) QuerySessions() *SessionQuery {
	return NewWorkspaceClient(w.config).QuerySessions(w)
}

// QueryService queries the "service" edge of the Workspace entity.
func (w *Workspace) QueryService() *ServiceQuery {
	return NewWorkspaceClient(w.config).QueryService(w)
}

// QueryAnalyzerPayloads queries the "analyzer_payloads" edge of the Workspace entity.
func (w *Workspace) QueryAnalyzerPayloads() *AnalyzerPayloadQuery {
	return NewWorkspaceClient(w.config).QueryAnalyzerPayloads(w)
}

// QueryCartSessions queries the "cart_sessions" edge of the Workspace entity.
func (w *Workspace) QueryCartSessions() *CartSessionQuery {
	return NewWorkspaceClient(w.config).QueryCartSessions(w)
}

// Update returns a builder for updating this Workspace.
// Note that you need to call Workspace.Unwrap() before calling this method if this Workspace
// was returned from a transaction, and the transaction was committed or rolled back.
func (w *Workspace) Update() *WorkspaceUpdateOne {
	return NewWorkspaceClient(w.config).UpdateOne(w)
}

// Unwrap unwraps the Workspace entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (w *Workspace) Unwrap() *Workspace {
	_tx, ok := w.config.driver.(*txDriver)
	if !ok {
		panic("ent: Workspace is not a transactional entity")
	}
	w.config.driver = _tx.drv
	return w
}

// String implements the fmt.Stringer.
func (w *Workspace) String() string {
	var builder strings.Builder
	builder.WriteString("Workspace(")
	builder.WriteString(fmt.Sprintf("id=%v, ", w.ID))
	builder.WriteString("name=")
	builder.WriteString(w.Name)
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(fmt.Sprintf("%v", w.Status))
	builder.WriteByte(')')
	return builder.String()
}

// Workspaces is a parsable slice of Workspace.
type Workspaces []*Workspace
