// Code generated by ent, DO NOT EDIT.

package ent

import (
	"altron/core/repositories/ent/analyzerpayload"
	"altron/core/repositories/ent/cartsession"
	"altron/core/repositories/ent/predicate"
	"altron/core/repositories/ent/service"
	"altron/core/repositories/ent/session"
	"altron/core/repositories/ent/workspace"
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// WorkspaceUpdate is the builder for updating Workspace entities.
type WorkspaceUpdate struct {
	config
	hooks    []Hook
	mutation *WorkspaceMutation
}

// Where appends a list predicates to the WorkspaceUpdate builder.
func (wu *WorkspaceUpdate) Where(ps ...predicate.Workspace) *WorkspaceUpdate {
	wu.mutation.Where(ps...)
	return wu
}

// SetName sets the "name" field.
func (wu *WorkspaceUpdate) SetName(s string) *WorkspaceUpdate {
	wu.mutation.SetName(s)
	return wu
}

// SetNillableName sets the "name" field if the given value is not nil.
func (wu *WorkspaceUpdate) SetNillableName(s *string) *WorkspaceUpdate {
	if s != nil {
		wu.SetName(*s)
	}
	return wu
}

// SetStatus sets the "status" field.
func (wu *WorkspaceUpdate) SetStatus(w workspace.Status) *WorkspaceUpdate {
	wu.mutation.SetStatus(w)
	return wu
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (wu *WorkspaceUpdate) SetNillableStatus(w *workspace.Status) *WorkspaceUpdate {
	if w != nil {
		wu.SetStatus(*w)
	}
	return wu
}

// AddSessionIDs adds the "sessions" edge to the Session entity by IDs.
func (wu *WorkspaceUpdate) AddSessionIDs(ids ...uuid.UUID) *WorkspaceUpdate {
	wu.mutation.AddSessionIDs(ids...)
	return wu
}

// AddSessions adds the "sessions" edges to the Session entity.
func (wu *WorkspaceUpdate) AddSessions(s ...*Session) *WorkspaceUpdate {
	ids := make([]uuid.UUID, len(s))
	for i := range s {
		ids[i] = s[i].ID
	}
	return wu.AddSessionIDs(ids...)
}

// SetServiceID sets the "service" edge to the Service entity by ID.
func (wu *WorkspaceUpdate) SetServiceID(id uuid.UUID) *WorkspaceUpdate {
	wu.mutation.SetServiceID(id)
	return wu
}

// SetNillableServiceID sets the "service" edge to the Service entity by ID if the given value is not nil.
func (wu *WorkspaceUpdate) SetNillableServiceID(id *uuid.UUID) *WorkspaceUpdate {
	if id != nil {
		wu = wu.SetServiceID(*id)
	}
	return wu
}

// SetService sets the "service" edge to the Service entity.
func (wu *WorkspaceUpdate) SetService(s *Service) *WorkspaceUpdate {
	return wu.SetServiceID(s.ID)
}

// AddAnalyzerPayloadIDs adds the "analyzer_payloads" edge to the AnalyzerPayload entity by IDs.
func (wu *WorkspaceUpdate) AddAnalyzerPayloadIDs(ids ...uuid.UUID) *WorkspaceUpdate {
	wu.mutation.AddAnalyzerPayloadIDs(ids...)
	return wu
}

// AddAnalyzerPayloads adds the "analyzer_payloads" edges to the AnalyzerPayload entity.
func (wu *WorkspaceUpdate) AddAnalyzerPayloads(a ...*AnalyzerPayload) *WorkspaceUpdate {
	ids := make([]uuid.UUID, len(a))
	for i := range a {
		ids[i] = a[i].ID
	}
	return wu.AddAnalyzerPayloadIDs(ids...)
}

// AddCartSessionIDs adds the "cart_sessions" edge to the CartSession entity by IDs.
func (wu *WorkspaceUpdate) AddCartSessionIDs(ids ...uuid.UUID) *WorkspaceUpdate {
	wu.mutation.AddCartSessionIDs(ids...)
	return wu
}

// AddCartSessions adds the "cart_sessions" edges to the CartSession entity.
func (wu *WorkspaceUpdate) AddCartSessions(c ...*CartSession) *WorkspaceUpdate {
	ids := make([]uuid.UUID, len(c))
	for i := range c {
		ids[i] = c[i].ID
	}
	return wu.AddCartSessionIDs(ids...)
}

// Mutation returns the WorkspaceMutation object of the builder.
func (wu *WorkspaceUpdate) Mutation() *WorkspaceMutation {
	return wu.mutation
}

// ClearSessions clears all "sessions" edges to the Session entity.
func (wu *WorkspaceUpdate) ClearSessions() *WorkspaceUpdate {
	wu.mutation.ClearSessions()
	return wu
}

// RemoveSessionIDs removes the "sessions" edge to Session entities by IDs.
func (wu *WorkspaceUpdate) RemoveSessionIDs(ids ...uuid.UUID) *WorkspaceUpdate {
	wu.mutation.RemoveSessionIDs(ids...)
	return wu
}

// RemoveSessions removes "sessions" edges to Session entities.
func (wu *WorkspaceUpdate) RemoveSessions(s ...*Session) *WorkspaceUpdate {
	ids := make([]uuid.UUID, len(s))
	for i := range s {
		ids[i] = s[i].ID
	}
	return wu.RemoveSessionIDs(ids...)
}

// ClearService clears the "service" edge to the Service entity.
func (wu *WorkspaceUpdate) ClearService() *WorkspaceUpdate {
	wu.mutation.ClearService()
	return wu
}

// ClearAnalyzerPayloads clears all "analyzer_payloads" edges to the AnalyzerPayload entity.
func (wu *WorkspaceUpdate) ClearAnalyzerPayloads() *WorkspaceUpdate {
	wu.mutation.ClearAnalyzerPayloads()
	return wu
}

// RemoveAnalyzerPayloadIDs removes the "analyzer_payloads" edge to AnalyzerPayload entities by IDs.
func (wu *WorkspaceUpdate) RemoveAnalyzerPayloadIDs(ids ...uuid.UUID) *WorkspaceUpdate {
	wu.mutation.RemoveAnalyzerPayloadIDs(ids...)
	return wu
}

// RemoveAnalyzerPayloads removes "analyzer_payloads" edges to AnalyzerPayload entities.
func (wu *WorkspaceUpdate) RemoveAnalyzerPayloads(a ...*AnalyzerPayload) *WorkspaceUpdate {
	ids := make([]uuid.UUID, len(a))
	for i := range a {
		ids[i] = a[i].ID
	}
	return wu.RemoveAnalyzerPayloadIDs(ids...)
}

// ClearCartSessions clears all "cart_sessions" edges to the CartSession entity.
func (wu *WorkspaceUpdate) ClearCartSessions() *WorkspaceUpdate {
	wu.mutation.ClearCartSessions()
	return wu
}

// RemoveCartSessionIDs removes the "cart_sessions" edge to CartSession entities by IDs.
func (wu *WorkspaceUpdate) RemoveCartSessionIDs(ids ...uuid.UUID) *WorkspaceUpdate {
	wu.mutation.RemoveCartSessionIDs(ids...)
	return wu
}

// RemoveCartSessions removes "cart_sessions" edges to CartSession entities.
func (wu *WorkspaceUpdate) RemoveCartSessions(c ...*CartSession) *WorkspaceUpdate {
	ids := make([]uuid.UUID, len(c))
	for i := range c {
		ids[i] = c[i].ID
	}
	return wu.RemoveCartSessionIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (wu *WorkspaceUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, wu.sqlSave, wu.mutation, wu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (wu *WorkspaceUpdate) SaveX(ctx context.Context) int {
	affected, err := wu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (wu *WorkspaceUpdate) Exec(ctx context.Context) error {
	_, err := wu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (wu *WorkspaceUpdate) ExecX(ctx context.Context) {
	if err := wu.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (wu *WorkspaceUpdate) check() error {
	if v, ok := wu.mutation.Status(); ok {
		if err := workspace.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Workspace.status": %w`, err)}
		}
	}
	return nil
}

func (wu *WorkspaceUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := wu.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(workspace.Table, workspace.Columns, sqlgraph.NewFieldSpec(workspace.FieldID, field.TypeUUID))
	if ps := wu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := wu.mutation.Name(); ok {
		_spec.SetField(workspace.FieldName, field.TypeString, value)
	}
	if value, ok := wu.mutation.Status(); ok {
		_spec.SetField(workspace.FieldStatus, field.TypeEnum, value)
	}
	if wu.mutation.SessionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   workspace.SessionsTable,
			Columns: []string{workspace.SessionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(session.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := wu.mutation.RemovedSessionsIDs(); len(nodes) > 0 && !wu.mutation.SessionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   workspace.SessionsTable,
			Columns: []string{workspace.SessionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(session.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := wu.mutation.SessionsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   workspace.SessionsTable,
			Columns: []string{workspace.SessionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(session.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if wu.mutation.ServiceCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   workspace.ServiceTable,
			Columns: []string{workspace.ServiceColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(service.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := wu.mutation.ServiceIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   workspace.ServiceTable,
			Columns: []string{workspace.ServiceColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(service.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if wu.mutation.AnalyzerPayloadsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   workspace.AnalyzerPayloadsTable,
			Columns: []string{workspace.AnalyzerPayloadsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(analyzerpayload.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := wu.mutation.RemovedAnalyzerPayloadsIDs(); len(nodes) > 0 && !wu.mutation.AnalyzerPayloadsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   workspace.AnalyzerPayloadsTable,
			Columns: []string{workspace.AnalyzerPayloadsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(analyzerpayload.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := wu.mutation.AnalyzerPayloadsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   workspace.AnalyzerPayloadsTable,
			Columns: []string{workspace.AnalyzerPayloadsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(analyzerpayload.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if wu.mutation.CartSessionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   workspace.CartSessionsTable,
			Columns: []string{workspace.CartSessionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(cartsession.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := wu.mutation.RemovedCartSessionsIDs(); len(nodes) > 0 && !wu.mutation.CartSessionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   workspace.CartSessionsTable,
			Columns: []string{workspace.CartSessionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(cartsession.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := wu.mutation.CartSessionsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   workspace.CartSessionsTable,
			Columns: []string{workspace.CartSessionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(cartsession.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, wu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{workspace.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	wu.mutation.done = true
	return n, nil
}

// WorkspaceUpdateOne is the builder for updating a single Workspace entity.
type WorkspaceUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *WorkspaceMutation
}

// SetName sets the "name" field.
func (wuo *WorkspaceUpdateOne) SetName(s string) *WorkspaceUpdateOne {
	wuo.mutation.SetName(s)
	return wuo
}

// SetNillableName sets the "name" field if the given value is not nil.
func (wuo *WorkspaceUpdateOne) SetNillableName(s *string) *WorkspaceUpdateOne {
	if s != nil {
		wuo.SetName(*s)
	}
	return wuo
}

// SetStatus sets the "status" field.
func (wuo *WorkspaceUpdateOne) SetStatus(w workspace.Status) *WorkspaceUpdateOne {
	wuo.mutation.SetStatus(w)
	return wuo
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (wuo *WorkspaceUpdateOne) SetNillableStatus(w *workspace.Status) *WorkspaceUpdateOne {
	if w != nil {
		wuo.SetStatus(*w)
	}
	return wuo
}

// AddSessionIDs adds the "sessions" edge to the Session entity by IDs.
func (wuo *WorkspaceUpdateOne) AddSessionIDs(ids ...uuid.UUID) *WorkspaceUpdateOne {
	wuo.mutation.AddSessionIDs(ids...)
	return wuo
}

// AddSessions adds the "sessions" edges to the Session entity.
func (wuo *WorkspaceUpdateOne) AddSessions(s ...*Session) *WorkspaceUpdateOne {
	ids := make([]uuid.UUID, len(s))
	for i := range s {
		ids[i] = s[i].ID
	}
	return wuo.AddSessionIDs(ids...)
}

// SetServiceID sets the "service" edge to the Service entity by ID.
func (wuo *WorkspaceUpdateOne) SetServiceID(id uuid.UUID) *WorkspaceUpdateOne {
	wuo.mutation.SetServiceID(id)
	return wuo
}

// SetNillableServiceID sets the "service" edge to the Service entity by ID if the given value is not nil.
func (wuo *WorkspaceUpdateOne) SetNillableServiceID(id *uuid.UUID) *WorkspaceUpdateOne {
	if id != nil {
		wuo = wuo.SetServiceID(*id)
	}
	return wuo
}

// SetService sets the "service" edge to the Service entity.
func (wuo *WorkspaceUpdateOne) SetService(s *Service) *WorkspaceUpdateOne {
	return wuo.SetServiceID(s.ID)
}

// AddAnalyzerPayloadIDs adds the "analyzer_payloads" edge to the AnalyzerPayload entity by IDs.
func (wuo *WorkspaceUpdateOne) AddAnalyzerPayloadIDs(ids ...uuid.UUID) *WorkspaceUpdateOne {
	wuo.mutation.AddAnalyzerPayloadIDs(ids...)
	return wuo
}

// AddAnalyzerPayloads adds the "analyzer_payloads" edges to the AnalyzerPayload entity.
func (wuo *WorkspaceUpdateOne) AddAnalyzerPayloads(a ...*AnalyzerPayload) *WorkspaceUpdateOne {
	ids := make([]uuid.UUID, len(a))
	for i := range a {
		ids[i] = a[i].ID
	}
	return wuo.AddAnalyzerPayloadIDs(ids...)
}

// AddCartSessionIDs adds the "cart_sessions" edge to the CartSession entity by IDs.
func (wuo *WorkspaceUpdateOne) AddCartSessionIDs(ids ...uuid.UUID) *WorkspaceUpdateOne {
	wuo.mutation.AddCartSessionIDs(ids...)
	return wuo
}

// AddCartSessions adds the "cart_sessions" edges to the CartSession entity.
func (wuo *WorkspaceUpdateOne) AddCartSessions(c ...*CartSession) *WorkspaceUpdateOne {
	ids := make([]uuid.UUID, len(c))
	for i := range c {
		ids[i] = c[i].ID
	}
	return wuo.AddCartSessionIDs(ids...)
}

// Mutation returns the WorkspaceMutation object of the builder.
func (wuo *WorkspaceUpdateOne) Mutation() *WorkspaceMutation {
	return wuo.mutation
}

// ClearSessions clears all "sessions" edges to the Session entity.
func (wuo *WorkspaceUpdateOne) ClearSessions() *WorkspaceUpdateOne {
	wuo.mutation.ClearSessions()
	return wuo
}

// RemoveSessionIDs removes the "sessions" edge to Session entities by IDs.
func (wuo *WorkspaceUpdateOne) RemoveSessionIDs(ids ...uuid.UUID) *WorkspaceUpdateOne {
	wuo.mutation.RemoveSessionIDs(ids...)
	return wuo
}

// RemoveSessions removes "sessions" edges to Session entities.
func (wuo *WorkspaceUpdateOne) RemoveSessions(s ...*Session) *WorkspaceUpdateOne {
	ids := make([]uuid.UUID, len(s))
	for i := range s {
		ids[i] = s[i].ID
	}
	return wuo.RemoveSessionIDs(ids...)
}

// ClearService clears the "service" edge to the Service entity.
func (wuo *WorkspaceUpdateOne) ClearService() *WorkspaceUpdateOne {
	wuo.mutation.ClearService()
	return wuo
}

// ClearAnalyzerPayloads clears all "analyzer_payloads" edges to the AnalyzerPayload entity.
func (wuo *WorkspaceUpdateOne) ClearAnalyzerPayloads() *WorkspaceUpdateOne {
	wuo.mutation.ClearAnalyzerPayloads()
	return wuo
}

// RemoveAnalyzerPayloadIDs removes the "analyzer_payloads" edge to AnalyzerPayload entities by IDs.
func (wuo *WorkspaceUpdateOne) RemoveAnalyzerPayloadIDs(ids ...uuid.UUID) *WorkspaceUpdateOne {
	wuo.mutation.RemoveAnalyzerPayloadIDs(ids...)
	return wuo
}

// RemoveAnalyzerPayloads removes "analyzer_payloads" edges to AnalyzerPayload entities.
func (wuo *WorkspaceUpdateOne) RemoveAnalyzerPayloads(a ...*AnalyzerPayload) *WorkspaceUpdateOne {
	ids := make([]uuid.UUID, len(a))
	for i := range a {
		ids[i] = a[i].ID
	}
	return wuo.RemoveAnalyzerPayloadIDs(ids...)
}

// ClearCartSessions clears all "cart_sessions" edges to the CartSession entity.
func (wuo *WorkspaceUpdateOne) ClearCartSessions() *WorkspaceUpdateOne {
	wuo.mutation.ClearCartSessions()
	return wuo
}

// RemoveCartSessionIDs removes the "cart_sessions" edge to CartSession entities by IDs.
func (wuo *WorkspaceUpdateOne) RemoveCartSessionIDs(ids ...uuid.UUID) *WorkspaceUpdateOne {
	wuo.mutation.RemoveCartSessionIDs(ids...)
	return wuo
}

// RemoveCartSessions removes "cart_sessions" edges to CartSession entities.
func (wuo *WorkspaceUpdateOne) RemoveCartSessions(c ...*CartSession) *WorkspaceUpdateOne {
	ids := make([]uuid.UUID, len(c))
	for i := range c {
		ids[i] = c[i].ID
	}
	return wuo.RemoveCartSessionIDs(ids...)
}

// Where appends a list predicates to the WorkspaceUpdate builder.
func (wuo *WorkspaceUpdateOne) Where(ps ...predicate.Workspace) *WorkspaceUpdateOne {
	wuo.mutation.Where(ps...)
	return wuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (wuo *WorkspaceUpdateOne) Select(field string, fields ...string) *WorkspaceUpdateOne {
	wuo.fields = append([]string{field}, fields...)
	return wuo
}

// Save executes the query and returns the updated Workspace entity.
func (wuo *WorkspaceUpdateOne) Save(ctx context.Context) (*Workspace, error) {
	return withHooks(ctx, wuo.sqlSave, wuo.mutation, wuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (wuo *WorkspaceUpdateOne) SaveX(ctx context.Context) *Workspace {
	node, err := wuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (wuo *WorkspaceUpdateOne) Exec(ctx context.Context) error {
	_, err := wuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (wuo *WorkspaceUpdateOne) ExecX(ctx context.Context) {
	if err := wuo.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (wuo *WorkspaceUpdateOne) check() error {
	if v, ok := wuo.mutation.Status(); ok {
		if err := workspace.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Workspace.status": %w`, err)}
		}
	}
	return nil
}

func (wuo *WorkspaceUpdateOne) sqlSave(ctx context.Context) (_node *Workspace, err error) {
	if err := wuo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(workspace.Table, workspace.Columns, sqlgraph.NewFieldSpec(workspace.FieldID, field.TypeUUID))
	id, ok := wuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Workspace.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := wuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, workspace.FieldID)
		for _, f := range fields {
			if !workspace.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != workspace.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := wuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := wuo.mutation.Name(); ok {
		_spec.SetField(workspace.FieldName, field.TypeString, value)
	}
	if value, ok := wuo.mutation.Status(); ok {
		_spec.SetField(workspace.FieldStatus, field.TypeEnum, value)
	}
	if wuo.mutation.SessionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   workspace.SessionsTable,
			Columns: []string{workspace.SessionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(session.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := wuo.mutation.RemovedSessionsIDs(); len(nodes) > 0 && !wuo.mutation.SessionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   workspace.SessionsTable,
			Columns: []string{workspace.SessionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(session.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := wuo.mutation.SessionsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   workspace.SessionsTable,
			Columns: []string{workspace.SessionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(session.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if wuo.mutation.ServiceCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   workspace.ServiceTable,
			Columns: []string{workspace.ServiceColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(service.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := wuo.mutation.ServiceIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   workspace.ServiceTable,
			Columns: []string{workspace.ServiceColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(service.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if wuo.mutation.AnalyzerPayloadsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   workspace.AnalyzerPayloadsTable,
			Columns: []string{workspace.AnalyzerPayloadsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(analyzerpayload.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := wuo.mutation.RemovedAnalyzerPayloadsIDs(); len(nodes) > 0 && !wuo.mutation.AnalyzerPayloadsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   workspace.AnalyzerPayloadsTable,
			Columns: []string{workspace.AnalyzerPayloadsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(analyzerpayload.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := wuo.mutation.AnalyzerPayloadsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   workspace.AnalyzerPayloadsTable,
			Columns: []string{workspace.AnalyzerPayloadsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(analyzerpayload.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if wuo.mutation.CartSessionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   workspace.CartSessionsTable,
			Columns: []string{workspace.CartSessionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(cartsession.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := wuo.mutation.RemovedCartSessionsIDs(); len(nodes) > 0 && !wuo.mutation.CartSessionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   workspace.CartSessionsTable,
			Columns: []string{workspace.CartSessionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(cartsession.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := wuo.mutation.CartSessionsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   workspace.CartSessionsTable,
			Columns: []string{workspace.CartSessionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(cartsession.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Workspace{config: wuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, wuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{workspace.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	wuo.mutation.done = true
	return _node, nil
}
