// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// AnalyzerComponent is the predicate function for analyzercomponent builders.
type AnalyzerComponent func(*sql.Selector)

// AnalyzerPayload is the predicate function for analyzerpayload builders.
type AnalyzerPayload func(*sql.Selector)

// CartSession is the predicate function for cartsession builders.
type CartSession func(*sql.Selector)

// Filter is the predicate function for filter builders.
type Filter func(*sql.Selector)

// MatchedPacket is the predicate function for matchedpacket builders.
type MatchedPacket func(*sql.Selector)

// Packet is the predicate function for packet builders.
type Packet func(*sql.Selector)

// PcapWorkspace is the predicate function for pcapworkspace builders.
type PcapWorkspace func(*sql.Selector)

// Plugin is the predicate function for plugin builders.
type Plugin func(*sql.Selector)

// Service is the predicate function for service builders.
type Service func(*sql.Selector)

// Session is the predicate function for session builders.
type Session func(*sql.Selector)

// SessionFilter is the predicate function for sessionfilter builders.
type SessionFilter func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)

// Workspace is the predicate function for workspace builders.
type Workspace func(*sql.Selector)
