// Code generated by ent, DO NOT EDIT.

package session

import (
	"altron/core/repositories/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.Session {
	return predicate.Session(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.Session {
	return predicate.Session(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.Session {
	return predicate.Session(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.Session {
	return predicate.Session(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.Session {
	return predicate.Session(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.Session {
	return predicate.Session(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.Session {
	return predicate.Session(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.Session {
	return predicate.Session(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.Session {
	return predicate.Session(sql.FieldLTE(FieldID, id))
}

// SentAt applies equality check predicate on the "sent_at" field. It's identical to SentAtEQ.
func SentAt(v time.Time) predicate.Session {
	return predicate.Session(sql.FieldEQ(FieldSentAt, v))
}

// ClientHost applies equality check predicate on the "client_host" field. It's identical to ClientHostEQ.
func ClientHost(v string) predicate.Session {
	return predicate.Session(sql.FieldEQ(FieldClientHost, v))
}

// ServerPort applies equality check predicate on the "server_port" field. It's identical to ServerPortEQ.
func ServerPort(v uint32) predicate.Session {
	return predicate.Session(sql.FieldEQ(FieldServerPort, v))
}

// TTL applies equality check predicate on the "ttl" field. It's identical to TTLEQ.
func TTL(v uint8) predicate.Session {
	return predicate.Session(sql.FieldEQ(FieldTTL, v))
}

// PacketsCount applies equality check predicate on the "packets_count" field. It's identical to PacketsCountEQ.
func PacketsCount(v int) predicate.Session {
	return predicate.Session(sql.FieldEQ(FieldPacketsCount, v))
}

// ClientUserAgent applies equality check predicate on the "client_user_agent" field. It's identical to ClientUserAgentEQ.
func ClientUserAgent(v string) predicate.Session {
	return predicate.Session(sql.FieldEQ(FieldClientUserAgent, v))
}

// Protocol applies equality check predicate on the "protocol" field. It's identical to ProtocolEQ.
func Protocol(v string) predicate.Session {
	return predicate.Session(sql.FieldEQ(FieldProtocol, v))
}

// AverageResponseTime applies equality check predicate on the "average_response_time" field. It's identical to AverageResponseTimeEQ.
func AverageResponseTime(v float64) predicate.Session {
	return predicate.Session(sql.FieldEQ(FieldAverageResponseTime, v))
}

// RequestsNumber applies equality check predicate on the "requests_number" field. It's identical to RequestsNumberEQ.
func RequestsNumber(v int) predicate.Session {
	return predicate.Session(sql.FieldEQ(FieldRequestsNumber, v))
}

// SentAtEQ applies the EQ predicate on the "sent_at" field.
func SentAtEQ(v time.Time) predicate.Session {
	return predicate.Session(sql.FieldEQ(FieldSentAt, v))
}

// SentAtNEQ applies the NEQ predicate on the "sent_at" field.
func SentAtNEQ(v time.Time) predicate.Session {
	return predicate.Session(sql.FieldNEQ(FieldSentAt, v))
}

// SentAtIn applies the In predicate on the "sent_at" field.
func SentAtIn(vs ...time.Time) predicate.Session {
	return predicate.Session(sql.FieldIn(FieldSentAt, vs...))
}

// SentAtNotIn applies the NotIn predicate on the "sent_at" field.
func SentAtNotIn(vs ...time.Time) predicate.Session {
	return predicate.Session(sql.FieldNotIn(FieldSentAt, vs...))
}

// SentAtGT applies the GT predicate on the "sent_at" field.
func SentAtGT(v time.Time) predicate.Session {
	return predicate.Session(sql.FieldGT(FieldSentAt, v))
}

// SentAtGTE applies the GTE predicate on the "sent_at" field.
func SentAtGTE(v time.Time) predicate.Session {
	return predicate.Session(sql.FieldGTE(FieldSentAt, v))
}

// SentAtLT applies the LT predicate on the "sent_at" field.
func SentAtLT(v time.Time) predicate.Session {
	return predicate.Session(sql.FieldLT(FieldSentAt, v))
}

// SentAtLTE applies the LTE predicate on the "sent_at" field.
func SentAtLTE(v time.Time) predicate.Session {
	return predicate.Session(sql.FieldLTE(FieldSentAt, v))
}

// ClientHostEQ applies the EQ predicate on the "client_host" field.
func ClientHostEQ(v string) predicate.Session {
	return predicate.Session(sql.FieldEQ(FieldClientHost, v))
}

// ClientHostNEQ applies the NEQ predicate on the "client_host" field.
func ClientHostNEQ(v string) predicate.Session {
	return predicate.Session(sql.FieldNEQ(FieldClientHost, v))
}

// ClientHostIn applies the In predicate on the "client_host" field.
func ClientHostIn(vs ...string) predicate.Session {
	return predicate.Session(sql.FieldIn(FieldClientHost, vs...))
}

// ClientHostNotIn applies the NotIn predicate on the "client_host" field.
func ClientHostNotIn(vs ...string) predicate.Session {
	return predicate.Session(sql.FieldNotIn(FieldClientHost, vs...))
}

// ClientHostGT applies the GT predicate on the "client_host" field.
func ClientHostGT(v string) predicate.Session {
	return predicate.Session(sql.FieldGT(FieldClientHost, v))
}

// ClientHostGTE applies the GTE predicate on the "client_host" field.
func ClientHostGTE(v string) predicate.Session {
	return predicate.Session(sql.FieldGTE(FieldClientHost, v))
}

// ClientHostLT applies the LT predicate on the "client_host" field.
func ClientHostLT(v string) predicate.Session {
	return predicate.Session(sql.FieldLT(FieldClientHost, v))
}

// ClientHostLTE applies the LTE predicate on the "client_host" field.
func ClientHostLTE(v string) predicate.Session {
	return predicate.Session(sql.FieldLTE(FieldClientHost, v))
}

// ClientHostContains applies the Contains predicate on the "client_host" field.
func ClientHostContains(v string) predicate.Session {
	return predicate.Session(sql.FieldContains(FieldClientHost, v))
}

// ClientHostHasPrefix applies the HasPrefix predicate on the "client_host" field.
func ClientHostHasPrefix(v string) predicate.Session {
	return predicate.Session(sql.FieldHasPrefix(FieldClientHost, v))
}

// ClientHostHasSuffix applies the HasSuffix predicate on the "client_host" field.
func ClientHostHasSuffix(v string) predicate.Session {
	return predicate.Session(sql.FieldHasSuffix(FieldClientHost, v))
}

// ClientHostEqualFold applies the EqualFold predicate on the "client_host" field.
func ClientHostEqualFold(v string) predicate.Session {
	return predicate.Session(sql.FieldEqualFold(FieldClientHost, v))
}

// ClientHostContainsFold applies the ContainsFold predicate on the "client_host" field.
func ClientHostContainsFold(v string) predicate.Session {
	return predicate.Session(sql.FieldContainsFold(FieldClientHost, v))
}

// ServerPortEQ applies the EQ predicate on the "server_port" field.
func ServerPortEQ(v uint32) predicate.Session {
	return predicate.Session(sql.FieldEQ(FieldServerPort, v))
}

// ServerPortNEQ applies the NEQ predicate on the "server_port" field.
func ServerPortNEQ(v uint32) predicate.Session {
	return predicate.Session(sql.FieldNEQ(FieldServerPort, v))
}

// ServerPortIn applies the In predicate on the "server_port" field.
func ServerPortIn(vs ...uint32) predicate.Session {
	return predicate.Session(sql.FieldIn(FieldServerPort, vs...))
}

// ServerPortNotIn applies the NotIn predicate on the "server_port" field.
func ServerPortNotIn(vs ...uint32) predicate.Session {
	return predicate.Session(sql.FieldNotIn(FieldServerPort, vs...))
}

// ServerPortGT applies the GT predicate on the "server_port" field.
func ServerPortGT(v uint32) predicate.Session {
	return predicate.Session(sql.FieldGT(FieldServerPort, v))
}

// ServerPortGTE applies the GTE predicate on the "server_port" field.
func ServerPortGTE(v uint32) predicate.Session {
	return predicate.Session(sql.FieldGTE(FieldServerPort, v))
}

// ServerPortLT applies the LT predicate on the "server_port" field.
func ServerPortLT(v uint32) predicate.Session {
	return predicate.Session(sql.FieldLT(FieldServerPort, v))
}

// ServerPortLTE applies the LTE predicate on the "server_port" field.
func ServerPortLTE(v uint32) predicate.Session {
	return predicate.Session(sql.FieldLTE(FieldServerPort, v))
}

// TTLEQ applies the EQ predicate on the "ttl" field.
func TTLEQ(v uint8) predicate.Session {
	return predicate.Session(sql.FieldEQ(FieldTTL, v))
}

// TTLNEQ applies the NEQ predicate on the "ttl" field.
func TTLNEQ(v uint8) predicate.Session {
	return predicate.Session(sql.FieldNEQ(FieldTTL, v))
}

// TTLIn applies the In predicate on the "ttl" field.
func TTLIn(vs ...uint8) predicate.Session {
	return predicate.Session(sql.FieldIn(FieldTTL, vs...))
}

// TTLNotIn applies the NotIn predicate on the "ttl" field.
func TTLNotIn(vs ...uint8) predicate.Session {
	return predicate.Session(sql.FieldNotIn(FieldTTL, vs...))
}

// TTLGT applies the GT predicate on the "ttl" field.
func TTLGT(v uint8) predicate.Session {
	return predicate.Session(sql.FieldGT(FieldTTL, v))
}

// TTLGTE applies the GTE predicate on the "ttl" field.
func TTLGTE(v uint8) predicate.Session {
	return predicate.Session(sql.FieldGTE(FieldTTL, v))
}

// TTLLT applies the LT predicate on the "ttl" field.
func TTLLT(v uint8) predicate.Session {
	return predicate.Session(sql.FieldLT(FieldTTL, v))
}

// TTLLTE applies the LTE predicate on the "ttl" field.
func TTLLTE(v uint8) predicate.Session {
	return predicate.Session(sql.FieldLTE(FieldTTL, v))
}

// PacketsCountEQ applies the EQ predicate on the "packets_count" field.
func PacketsCountEQ(v int) predicate.Session {
	return predicate.Session(sql.FieldEQ(FieldPacketsCount, v))
}

// PacketsCountNEQ applies the NEQ predicate on the "packets_count" field.
func PacketsCountNEQ(v int) predicate.Session {
	return predicate.Session(sql.FieldNEQ(FieldPacketsCount, v))
}

// PacketsCountIn applies the In predicate on the "packets_count" field.
func PacketsCountIn(vs ...int) predicate.Session {
	return predicate.Session(sql.FieldIn(FieldPacketsCount, vs...))
}

// PacketsCountNotIn applies the NotIn predicate on the "packets_count" field.
func PacketsCountNotIn(vs ...int) predicate.Session {
	return predicate.Session(sql.FieldNotIn(FieldPacketsCount, vs...))
}

// PacketsCountGT applies the GT predicate on the "packets_count" field.
func PacketsCountGT(v int) predicate.Session {
	return predicate.Session(sql.FieldGT(FieldPacketsCount, v))
}

// PacketsCountGTE applies the GTE predicate on the "packets_count" field.
func PacketsCountGTE(v int) predicate.Session {
	return predicate.Session(sql.FieldGTE(FieldPacketsCount, v))
}

// PacketsCountLT applies the LT predicate on the "packets_count" field.
func PacketsCountLT(v int) predicate.Session {
	return predicate.Session(sql.FieldLT(FieldPacketsCount, v))
}

// PacketsCountLTE applies the LTE predicate on the "packets_count" field.
func PacketsCountLTE(v int) predicate.Session {
	return predicate.Session(sql.FieldLTE(FieldPacketsCount, v))
}

// ClientUserAgentEQ applies the EQ predicate on the "client_user_agent" field.
func ClientUserAgentEQ(v string) predicate.Session {
	return predicate.Session(sql.FieldEQ(FieldClientUserAgent, v))
}

// ClientUserAgentNEQ applies the NEQ predicate on the "client_user_agent" field.
func ClientUserAgentNEQ(v string) predicate.Session {
	return predicate.Session(sql.FieldNEQ(FieldClientUserAgent, v))
}

// ClientUserAgentIn applies the In predicate on the "client_user_agent" field.
func ClientUserAgentIn(vs ...string) predicate.Session {
	return predicate.Session(sql.FieldIn(FieldClientUserAgent, vs...))
}

// ClientUserAgentNotIn applies the NotIn predicate on the "client_user_agent" field.
func ClientUserAgentNotIn(vs ...string) predicate.Session {
	return predicate.Session(sql.FieldNotIn(FieldClientUserAgent, vs...))
}

// ClientUserAgentGT applies the GT predicate on the "client_user_agent" field.
func ClientUserAgentGT(v string) predicate.Session {
	return predicate.Session(sql.FieldGT(FieldClientUserAgent, v))
}

// ClientUserAgentGTE applies the GTE predicate on the "client_user_agent" field.
func ClientUserAgentGTE(v string) predicate.Session {
	return predicate.Session(sql.FieldGTE(FieldClientUserAgent, v))
}

// ClientUserAgentLT applies the LT predicate on the "client_user_agent" field.
func ClientUserAgentLT(v string) predicate.Session {
	return predicate.Session(sql.FieldLT(FieldClientUserAgent, v))
}

// ClientUserAgentLTE applies the LTE predicate on the "client_user_agent" field.
func ClientUserAgentLTE(v string) predicate.Session {
	return predicate.Session(sql.FieldLTE(FieldClientUserAgent, v))
}

// ClientUserAgentContains applies the Contains predicate on the "client_user_agent" field.
func ClientUserAgentContains(v string) predicate.Session {
	return predicate.Session(sql.FieldContains(FieldClientUserAgent, v))
}

// ClientUserAgentHasPrefix applies the HasPrefix predicate on the "client_user_agent" field.
func ClientUserAgentHasPrefix(v string) predicate.Session {
	return predicate.Session(sql.FieldHasPrefix(FieldClientUserAgent, v))
}

// ClientUserAgentHasSuffix applies the HasSuffix predicate on the "client_user_agent" field.
func ClientUserAgentHasSuffix(v string) predicate.Session {
	return predicate.Session(sql.FieldHasSuffix(FieldClientUserAgent, v))
}

// ClientUserAgentIsNil applies the IsNil predicate on the "client_user_agent" field.
func ClientUserAgentIsNil() predicate.Session {
	return predicate.Session(sql.FieldIsNull(FieldClientUserAgent))
}

// ClientUserAgentNotNil applies the NotNil predicate on the "client_user_agent" field.
func ClientUserAgentNotNil() predicate.Session {
	return predicate.Session(sql.FieldNotNull(FieldClientUserAgent))
}

// ClientUserAgentEqualFold applies the EqualFold predicate on the "client_user_agent" field.
func ClientUserAgentEqualFold(v string) predicate.Session {
	return predicate.Session(sql.FieldEqualFold(FieldClientUserAgent, v))
}

// ClientUserAgentContainsFold applies the ContainsFold predicate on the "client_user_agent" field.
func ClientUserAgentContainsFold(v string) predicate.Session {
	return predicate.Session(sql.FieldContainsFold(FieldClientUserAgent, v))
}

// ProtocolEQ applies the EQ predicate on the "protocol" field.
func ProtocolEQ(v string) predicate.Session {
	return predicate.Session(sql.FieldEQ(FieldProtocol, v))
}

// ProtocolNEQ applies the NEQ predicate on the "protocol" field.
func ProtocolNEQ(v string) predicate.Session {
	return predicate.Session(sql.FieldNEQ(FieldProtocol, v))
}

// ProtocolIn applies the In predicate on the "protocol" field.
func ProtocolIn(vs ...string) predicate.Session {
	return predicate.Session(sql.FieldIn(FieldProtocol, vs...))
}

// ProtocolNotIn applies the NotIn predicate on the "protocol" field.
func ProtocolNotIn(vs ...string) predicate.Session {
	return predicate.Session(sql.FieldNotIn(FieldProtocol, vs...))
}

// ProtocolGT applies the GT predicate on the "protocol" field.
func ProtocolGT(v string) predicate.Session {
	return predicate.Session(sql.FieldGT(FieldProtocol, v))
}

// ProtocolGTE applies the GTE predicate on the "protocol" field.
func ProtocolGTE(v string) predicate.Session {
	return predicate.Session(sql.FieldGTE(FieldProtocol, v))
}

// ProtocolLT applies the LT predicate on the "protocol" field.
func ProtocolLT(v string) predicate.Session {
	return predicate.Session(sql.FieldLT(FieldProtocol, v))
}

// ProtocolLTE applies the LTE predicate on the "protocol" field.
func ProtocolLTE(v string) predicate.Session {
	return predicate.Session(sql.FieldLTE(FieldProtocol, v))
}

// ProtocolContains applies the Contains predicate on the "protocol" field.
func ProtocolContains(v string) predicate.Session {
	return predicate.Session(sql.FieldContains(FieldProtocol, v))
}

// ProtocolHasPrefix applies the HasPrefix predicate on the "protocol" field.
func ProtocolHasPrefix(v string) predicate.Session {
	return predicate.Session(sql.FieldHasPrefix(FieldProtocol, v))
}

// ProtocolHasSuffix applies the HasSuffix predicate on the "protocol" field.
func ProtocolHasSuffix(v string) predicate.Session {
	return predicate.Session(sql.FieldHasSuffix(FieldProtocol, v))
}

// ProtocolEqualFold applies the EqualFold predicate on the "protocol" field.
func ProtocolEqualFold(v string) predicate.Session {
	return predicate.Session(sql.FieldEqualFold(FieldProtocol, v))
}

// ProtocolContainsFold applies the ContainsFold predicate on the "protocol" field.
func ProtocolContainsFold(v string) predicate.Session {
	return predicate.Session(sql.FieldContainsFold(FieldProtocol, v))
}

// AverageResponseTimeEQ applies the EQ predicate on the "average_response_time" field.
func AverageResponseTimeEQ(v float64) predicate.Session {
	return predicate.Session(sql.FieldEQ(FieldAverageResponseTime, v))
}

// AverageResponseTimeNEQ applies the NEQ predicate on the "average_response_time" field.
func AverageResponseTimeNEQ(v float64) predicate.Session {
	return predicate.Session(sql.FieldNEQ(FieldAverageResponseTime, v))
}

// AverageResponseTimeIn applies the In predicate on the "average_response_time" field.
func AverageResponseTimeIn(vs ...float64) predicate.Session {
	return predicate.Session(sql.FieldIn(FieldAverageResponseTime, vs...))
}

// AverageResponseTimeNotIn applies the NotIn predicate on the "average_response_time" field.
func AverageResponseTimeNotIn(vs ...float64) predicate.Session {
	return predicate.Session(sql.FieldNotIn(FieldAverageResponseTime, vs...))
}

// AverageResponseTimeGT applies the GT predicate on the "average_response_time" field.
func AverageResponseTimeGT(v float64) predicate.Session {
	return predicate.Session(sql.FieldGT(FieldAverageResponseTime, v))
}

// AverageResponseTimeGTE applies the GTE predicate on the "average_response_time" field.
func AverageResponseTimeGTE(v float64) predicate.Session {
	return predicate.Session(sql.FieldGTE(FieldAverageResponseTime, v))
}

// AverageResponseTimeLT applies the LT predicate on the "average_response_time" field.
func AverageResponseTimeLT(v float64) predicate.Session {
	return predicate.Session(sql.FieldLT(FieldAverageResponseTime, v))
}

// AverageResponseTimeLTE applies the LTE predicate on the "average_response_time" field.
func AverageResponseTimeLTE(v float64) predicate.Session {
	return predicate.Session(sql.FieldLTE(FieldAverageResponseTime, v))
}

// RequestsNumberEQ applies the EQ predicate on the "requests_number" field.
func RequestsNumberEQ(v int) predicate.Session {
	return predicate.Session(sql.FieldEQ(FieldRequestsNumber, v))
}

// RequestsNumberNEQ applies the NEQ predicate on the "requests_number" field.
func RequestsNumberNEQ(v int) predicate.Session {
	return predicate.Session(sql.FieldNEQ(FieldRequestsNumber, v))
}

// RequestsNumberIn applies the In predicate on the "requests_number" field.
func RequestsNumberIn(vs ...int) predicate.Session {
	return predicate.Session(sql.FieldIn(FieldRequestsNumber, vs...))
}

// RequestsNumberNotIn applies the NotIn predicate on the "requests_number" field.
func RequestsNumberNotIn(vs ...int) predicate.Session {
	return predicate.Session(sql.FieldNotIn(FieldRequestsNumber, vs...))
}

// RequestsNumberGT applies the GT predicate on the "requests_number" field.
func RequestsNumberGT(v int) predicate.Session {
	return predicate.Session(sql.FieldGT(FieldRequestsNumber, v))
}

// RequestsNumberGTE applies the GTE predicate on the "requests_number" field.
func RequestsNumberGTE(v int) predicate.Session {
	return predicate.Session(sql.FieldGTE(FieldRequestsNumber, v))
}

// RequestsNumberLT applies the LT predicate on the "requests_number" field.
func RequestsNumberLT(v int) predicate.Session {
	return predicate.Session(sql.FieldLT(FieldRequestsNumber, v))
}

// RequestsNumberLTE applies the LTE predicate on the "requests_number" field.
func RequestsNumberLTE(v int) predicate.Session {
	return predicate.Session(sql.FieldLTE(FieldRequestsNumber, v))
}

// HasWorkspace applies the HasEdge predicate on the "workspace" edge.
func HasWorkspace() predicate.Session {
	return predicate.Session(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, WorkspaceTable, WorkspaceColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasWorkspaceWith applies the HasEdge predicate on the "workspace" edge with a given conditions (other predicates).
func HasWorkspaceWith(preds ...predicate.Workspace) predicate.Session {
	return predicate.Session(func(s *sql.Selector) {
		step := newWorkspaceStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasPcapWorkspace applies the HasEdge predicate on the "pcap_workspace" edge.
func HasPcapWorkspace() predicate.Session {
	return predicate.Session(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2M, true, PcapWorkspaceTable, PcapWorkspacePrimaryKey...),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasPcapWorkspaceWith applies the HasEdge predicate on the "pcap_workspace" edge with a given conditions (other predicates).
func HasPcapWorkspaceWith(preds ...predicate.PcapWorkspace) predicate.Session {
	return predicate.Session(func(s *sql.Selector) {
		step := newPcapWorkspaceStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasInCart applies the HasEdge predicate on the "in_cart" edge.
func HasInCart() predicate.Session {
	return predicate.Session(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2O, false, InCartTable, InCartColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasInCartWith applies the HasEdge predicate on the "in_cart" edge with a given conditions (other predicates).
func HasInCartWith(preds ...predicate.CartSession) predicate.Session {
	return predicate.Session(func(s *sql.Selector) {
		step := newInCartStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasPackets applies the HasEdge predicate on the "packets" edge.
func HasPackets() predicate.Session {
	return predicate.Session(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, PacketsTable, PacketsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasPacketsWith applies the HasEdge predicate on the "packets" edge with a given conditions (other predicates).
func HasPacketsWith(preds ...predicate.Packet) predicate.Session {
	return predicate.Session(func(s *sql.Selector) {
		step := newPacketsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasSessionFilters applies the HasEdge predicate on the "session_filters" edge.
func HasSessionFilters() predicate.Session {
	return predicate.Session(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, SessionFiltersTable, SessionFiltersColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasSessionFiltersWith applies the HasEdge predicate on the "session_filters" edge with a given conditions (other predicates).
func HasSessionFiltersWith(preds ...predicate.SessionFilter) predicate.Session {
	return predicate.Session(func(s *sql.Selector) {
		step := newSessionFiltersStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Session) predicate.Session {
	return predicate.Session(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Session) predicate.Session {
	return predicate.Session(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Session) predicate.Session {
	return predicate.Session(sql.NotPredicates(p))
}
