import i18n from 'i18next';
import { initReactI18next } from 'react-i18next';

const resources = {
    en: {
      translation: {
        greet_message: 'May the Force be with you, Omsk_Hackers!',
        sign_in: 'Sign in',
        password: 'Password',
        submit: 'Submit',
        cancel: 'Cancel',
        service: 'service',
        workspace: 'workspace',
        services: 'Services',
        workspaces: 'Workspaces',
        create_service: 'Create Service',
        name: 'name',
        link: 'link',
        port: 'port',
        plugins: 'Plugins',
        create_workspace_for_service: 'Create Workspace for service',
        scan_localhost: 'Scan localhost',
        localhost_services: 'Localhost services',
        create_workspace: 'Create Workspace',
        create_filter: 'Create Filter',
        regex: 'regex',
        matches: 'matches',
        request: 'request',
        response: 'response',
        both: "both",
        update: 'update',
        delete: 'delete',
        yes: 'Yes',
        error: 'ERROR',
        warning: "WARNING",
        info: "INFO",
        vulnbox: "vulnbox",
        listen_to_service: "Listen to service...",
        update_service: "Update service",
        get_exploit: "export",
        share_sessions: "Share {{sessionsLength}} session(s) to...",
        share_sessions_success: "sessions successfully shared to workspace '{{targetWorkspaceName}}'",
        create_workspace_success: "added new workspace '{{workspaceName}}'",
        update_workspace: "Update workspace",
        update_workspace_success: "workspace '{{workspaceName}}' updated",
        create_service_success: "added new service '{{serviceName}}'",
        delete_service_confirm: "Are you sure you want to delete this service?",
        delete_service_success: "service '{{serviceName}}' deleted",
        delete_workspace_confirm: "Are you sure you want to delete this workspace?",
        delete_workspace_success: "workspace '{{workspaceName}}' deleted",
        add_sessions_to_workspace_success: "{{sessionsLength}} sessions successfully added to workspace '{{workspaceName}}'",
        select_at_least_one_session_warning: "you have to select at least one session",
        unable_to_connect_error: 'unable to connect',
        delete_sessions_confirm: 'Are you sure you want to delete these sessions?',
        delete_sessions_success: "sessions deleted",
        create_filter_success: "added new filter '{{filterName}}'",
        delete_filter_success: "filter deleted",
        update_filter_success: "filter {{filterName}} updated",
        update_filter: 'Update filter',
        happy_hacking: "Happy hacking!",
        copied_to_clipboard: "Data copied to clipboard",
        choose_theme: "Choose theme",
        filters: "FILTERS",
        search_type: "Search type",
        block_content: "Block content",
        listening_start_time: "listening start time",
        checker_workspace_only_by_checkbox: "Checker workspace can be created only by checkbox",
        global: 'Global',
        presets: 'Presets',
        localhost_containers: 'Localhost containers',
        update_logs_container: 'Update logs container',
        drag_drop_title: 'Drag and drop file here',
        import_pcap: 'Import pcap file',
        upload: 'Upload',
        no_pcap_file: 'You need to upload pcap file',
        listening_timeout: 'Recording time'
      }
    },
    ru: {
        translation: {
            greet_message: 'Да пребудет с вами Сила, Омск_Хакерс!',
            sign_in: 'Войти',
            password: 'Пароль',
            submit: 'Подтвердить',
            cancel: 'Отмена',
            service: 'сервис',
            workspace: 'воркспейс',
            services: 'Сервисы',
            workspaces: 'Воркспейсы',
            create_service: 'Создать сервис',
            name: 'название',
            link: 'ссылка/команда',
            port: 'порт',
            plugins: 'Плагины',
            create_workspace_for_service: 'Создать воркспейс к сервису',
            scan_localhost: 'Сканировать порты',
            localhost_services: 'Сервисы хоста',
            create_workspace: 'Создать воркспейс',
            create_filter: 'Создать фильтр',
            regex: 'паттерн',
            matches: 'искать в...',
            request: 'запрос',
            response: 'ответ',
            both: "любой",
            update: 'обновить',
            delete: 'удалить',
            yes: 'Агась',
            error: 'ОШИБКА',
            warning: "ВНИМАНИЕ",
            info: "ИНФО",
            vulnbox: "вулнбокс",
            listen_to_service: "Прослушать сервис...",
            get_exploit: 'экспорт',
            share_sessions: "Поделиться {{sessionsLength}} сеансами...",
            share_sessions_success: "сеансы успешно скопированы в воркспейс '{{targetWorkspaceName}}'",
            create_workspace_success: "добавлен новый воркспейс '{{workspaceName}}'",
            update_service: "Обновить сервис",
            update_workspace: "Обновить воркспейс",
            update_workspace_success: "воркспейс '{{workspaceName}}' обновлен",
            create_service_success: "добавлен новый сервис '{{serviceName}}'",
            delete_service_confirm: "Вы уверены, что хотите удалить этот сервис?",
            delete_service_success: "сервис '{{serviceName}}' удален",
            delete_workspace_confirm: "Вы уверены, что хотите удалить этот воркспейс?",
            delete_workspace_success: "воркспейс '{{workspaceName}}' удален",
            add_sessions_to_workspace_success: "{{sessionsLength}} сеансов успешно добавлено в воркспейс '{{workspaceName}}'",
            select_at_least_one_session_warning: "вам необходимо выбрать как минимум один сеанс",
            unable_to_connect_error: 'ошибка при подключении',
            delete_sessions_confirm: 'Вы уверены, что хотите удалить данные сеансы?',
            create_filter_success: "добавлен новый фильтр '{{filterName}}'",
            delete_sessions_success: "сеансы удалены",
            delete_filter_success: "фильтр удален",
            update_filter_success: "фильтр {{filterName}} обновлен",
            update_filter: "Обновить фильтр",
            happy_hacking: "Приятного хакинга!",
            copied_to_clipboard: "Данные скопированы в буфер обмена",
            choose_theme: "Выбор темы",
            filters: "ФИЛЬТРЫ",
            search_type: "Тип поиска",
            block_content: "Фильтрация пакетов",
            listening_start_time: "Время начала прослушки",
            checker_workspace_only_by_checkbox: "Воркспейс чекеров может быть создан только с помощью чекбокса",
            global: 'Глобальный',
            presets: 'Пресеты',
            localhost_containers: 'Контейнеры хоста',
            update_logs_container: 'Обновить контейнер логов',
            drag_drop_title: 'Перетащите файл сюда',
            import_pcap: 'Импорт pcap дампа',
            upload: 'Загрузить',
            no_pcap_file: 'Вы не загрузили pcap файл',
            listening_timeout: 'Время записи'
        }
    }
};
  
i18n.use(initReactI18next)
    .init({
        resources,
        lng: 'en',
        fallbackLng: ['en', 'ru'],
        interpolation: {
            escapeValue: false
        },
        returnNull: false
    });
  
export default i18n;