server {
    listen ${PORT};
    server_name altron;

    client_max_body_size 100M;

    location / {
        root /;
        index index.html;
        try_files $uri /index.html;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /api/ {
        proxy_pass http://${HOSTNAME}:64001;
        proxy_set_header User-Agent "client";
        proxy_http_version 1.1;
        proxy_set_header Connection "";
    }

    location /connect/ {
        proxy_pass http://${HOSTNAME}:64005;
        proxy_http_version 1.1;
        proxy_read_timeout 86400s;
        proxy_send_timeout 86400s;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "Upgrade";
    }
}