// Code generated by ent, DO NOT EDIT.

package analyzercomponent

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the analyzercomponent type in the database.
	Label = "analyzer_component"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// EdgeAnalyzerPayloads holds the string denoting the analyzer_payloads edge name in mutations.
	EdgeAnalyzerPayloads = "analyzer_payloads"
	// Table holds the table name of the analyzercomponent in the database.
	Table = "analyzer_components"
	// AnalyzerPayloadsTable is the table that holds the analyzer_payloads relation/edge.
	AnalyzerPayloadsTable = "analyzer_payloads"
	// AnalyzerPayloadsInverseTable is the table name for the AnalyzerPayload entity.
	// It exists in this package in order to avoid circular dependency with the "analyzerpayload" package.
	AnalyzerPayloadsInverseTable = "analyzer_payloads"
	// AnalyzerPayloadsColumn is the table column denoting the analyzer_payloads relation/edge.
	AnalyzerPayloadsColumn = "analyzer_component_id"
)

// Columns holds all SQL columns for analyzercomponent fields.
var Columns = []string{
	FieldID,
	FieldName,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// OrderOption defines the ordering options for the AnalyzerComponent queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByAnalyzerPayloadsCount orders the results by analyzer_payloads count.
func ByAnalyzerPayloadsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newAnalyzerPayloadsStep(), opts...)
	}
}

// ByAnalyzerPayloads orders the results by analyzer_payloads terms.
func ByAnalyzerPayloads(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newAnalyzerPayloadsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newAnalyzerPayloadsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(AnalyzerPayloadsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, AnalyzerPayloadsTable, AnalyzerPayloadsColumn),
	)
}
